### ISSUE TITLE
Data Mgmt - CoreLogic ParcelPoint updates

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#10]
Background:  Parcel data is useful for many facets of TNC’s work, such as the identification of landowners in priority areas and generating parcel boundaries for documenting our protection work.  The CoreLogic ParcelPoint data product gives us access to parcel data by county for almost the entire United States.  New data is added quarterly, but often we download it as needed so sometimes more current data is available.

Need: I’d like to make sure we have access to the most current CA parcel data by county available

1)  Sign the 2016 ParcelPoint data use agreement
Go to: https://connect.tnc.org/programs/northamerica/science/Pages/GIS-Data.aspx to download agreement and send signed copy to Jan Slaats and cc me
2)  Go to TNC’s internal site to view/download data by county
 http://mnspatial.tnc.org/parcelpoint/
3)  View available data and check that we have current data by county in N:\Projects\Parcels\
4)  If updates are available, select and download. Unzip data and place shapefile in the county folder using our exiting naming convention (e.g. Alpine_CoreLogic_2008).  The year comes from the date acquired field on the download page.

Let me know if you have any questions, etc. Thanks!
Megan

**Comment by megrwebb** [comment]
@cgrainger431 quarterly parcel updates from CoreLogic are now available for some CA counties (~10). I'll forward the email with the list.  If you could download these, that would be helpful.  For the naming convention we'll now include year, month, and day (e.g. Alameda_CoreLogic_20160217).  This is not time sensitive. Thanks!

**Comment by cgrainger431** [comment]
Hi Megan, 

All of the new parcel data has been downloaded!

**Comment by megrwebb** [comment]
Great, thanks Cori!

**Comment by megrwebb** [comment]
Hi Cori,
We've received the first quarter, 2017 ParcelPoint updates from CoreLogic. I'll forward the email with the list.  When convenient (not time sensitive), please download the updated CA counties to N:\Projects\Parcels.  Rename including county name and vintage e.g. Amador_CoreLogic_20170117 (by year, month, and day).  Thank you.

**Comment by cgrainger431** [comment]
Hi Megan - All of the new parcel data has been downloaded!

**Comment by megrwebb** [comment]
Great!  Thank you.

**Comment by megrwebb** [comment]
Cori, we've received the second quarter, 2017 ParcelPoint updates from CoreLogic.  I'll forward the email.  Again, please fit this in when convenient.

**Comment by megrwebb** [comment]
I went ahead and downloaded the county parcel updates for this quarter.  We'll be receiving our next updates in September.
