### ISSUE TITLE
Four forest maps for Board of Trustee presentation by Eric and Rodd

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#100]
4 powerpoint maps needed:

1. Biomass infrastructure map (see other task)
2. Remake of the board book TSCI map without properties
3. Remake of the board book TSCI map with properties
4. Remake of the board book french meadows map in powerpoint format

No title on the maps
No frame around the maps
Size landscape 10x7.5in
JPG format
Draft Due 9/28
Final before 10/5

**Comment by kklausmeyer** [comment]
Eric needs a two maps for powerpoint- 1  of the Tahoe Central Sierra Initiative then another that has I Lake, Carpenter Valley and French Meadows appear.  Start with the board book map of the TCSI and convert to powerpoint format.
In the second map, it would be great if those projects really popped out visually (so some other color than a shade of green).

Draft Due 9/28
Final before 10/5

No title on map
Simple legend

**Comment by kklausmeyer** [comment]
Description of Map 4 in the list above:

Remake the French meadows / fire risk map from the board book into powerpoint format.  Move the legend onto the map and remove the frame

**Comment by kklausmeyer** [comment]
Description of Map 1 in the list above:

See "Wood Processing Infrastructure Map for board presentation by Eric and Rodd #99" task.

**Comment by connorshank** [comment]
mxd located here:
N:\Projects\TNC_Board_Meetings\2017_October\mxds\TCSI_properties_ppt_map_Connor_9252017.mxd

Final jpegs and pdfs located here:
N:\Projects\TNC_Board_Meetings\2017_October\plots
