### ISSUE TITLE
French Meadows Implementation Maps

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#105]
Download : FM_Implementation Folder from box
https://tnc.box.com/s/easzw7xgzyk7p1hy1dnbxl9uvu3hdbwl

Open MXD : dated Sept 25
Map the path of datasets to data within DATA Folder 
FireHistory, FM study area, 
Treatment folder : RobertGilliano

In the ppt see the extent of the larger study area (slide 1) zoom to that area, load Fire history, and show all the fires within the larger study extent. 

Thanks
Tanu

**Comment by TB2016** [comment]
Thanks Connor, 

Where are the Implementations stored on N drive let me know the link. I uploaded more datasets on BOX and updated version of MXD and Powerpoint. Please grab the ppt and mxd dated Oct 4, save them on N drive. Hopefully all links are working on this verison.

Thanks again
Tanu

**Comment by connorshank** [comment]
I've put all the data, maps, and powerpoints from box at the following location: N:\Sierra_Nevada\Projects\FM_ImplementationMaps

**Comment by connorshank** [comment]
Tanu, 
     I've downloaded the new data, mxd, and ppt and placed tem in the appropriate folders on the N: drive.   The links in the mxd are still broken (but that's to be expected), however it shouldn't be an issue to reconnect them now that I have all the relevant shapefiles and grids.   I'll send you and updated jpeg and pdf of the map at the extent you requested.

**Comment by TB2016** [comment]
can you please post the link to N Drive here?
I am creating a way to keep track of maps being produced out of SAC office.

Thanks
Tanu
