### ISSUE TITLE
Map for WO Global Diversity, Equity and Inclusion team (10/10 very flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#106]
As per the email of 10/5, this WO (world office) team would like help creating this map.  Selam used to work in CA, so as a "One Conservancy" gesture it'd be great if we can help.
They'd love to have this for a 10/10 meeting, but I told them that's unlikely and we'll do this when we can fit it into our workload.
They have "locations" they'd like mapped, but we don't know when in what format the location data is in (lat/long, street address, etc)... 
When you have time for this you can work with them to flesh out their needs a bit more (size, imager format, audience, purpose + message, ETC).

**Comment by connorshank** [comment]
I've looked over the email chain, and agree with what you said about the nature of the location data.   I'd be happy to help out on this!

**Comment by kklausmeyer** [comment]
Just a thought-  a google my maps or arcGIS online map might be a good way to go with this-  easy to update and share.

**Comment by connorshank** [comment]
I've created a folder for the maps, data, tables, etc, for this project at the following location
N:\World\Projects\GDEI

The first draft maps can be found here:
N:\World\Projects\GDEI\plots
