### ISSUE TITLE
TNC Points of Diversion (Update 7/25) 7/30 flex

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#107]

**Comment by kklausmeyer** [comment]
Connor-

I would like your help to make a spatial database of the points of diversion associated with TNC's water rights.  I have started a point feature class here that you can build on:  N:\Projects\CA_FWA\projects\WaterRights\gdbs\TNC_Water_Rights.gdb\Points_of_Diversion_TNC_Interest.

You can save all the files associated with this project here:  N:\Projects\CA_FWA\projects\WaterRights

Please make a new feature class with the name:  CA_TNC_PointsofDiversion

Delete all records where "TNC_INTEREST" = null OR "TNC HISTORIC"

Update the schema to match the files outlined here:  N:\Projects\CA_FWA\projects\WaterRights\tables\CA_TNC_PointsofDiversion_Schema.xlsx

**Comment by kklausmeyer** [comment]
Phase 2 of this project is to reconcile the POD data from the water board with actual field conditions.  I went out with a GPS unit and recorded the actual locations of the siphons and 1 diversion pump and their number this past summer on Staten Island.  

N:\Projects\CA_FWA\projects\SB88\StatenIsland\shapes\Staten_Pumps_20170407.shp
N:\Projects\CA_FWA\projects\SB88\StatenIsland\shapes\Staten_Siphons_20170407.shp

Task- move the points to match up better with the actual locations.  Update the POD_Name field with the number of the siphon.  Write notes in the TNC_comment field for any change you make, even a minor one.

There are some times when there is a siphon but no POD and vice versa.  Talk to me when you get to this point and we can see if we can figure out how to align the two datasets.  If you follow the link in the "eWRIMS_URL" field, it will take you to a webpage.  Click on "View Statement" and you will see a PDF.  Many of these give the name of the diversion works, so try to match the siphon number and the name of the diversion works.  But I think the numbers have changed over the years, so they may not be correct in all cases on the PDF files. 

![image](https://user-images.githubusercontent.com/11560493/31256177-b5828cea-a9e5-11e7-8883-a9720552df30.png)

**Comment by kklausmeyer** [comment]
Here is what Katie wrote about the broader work flow for this project: 

"I think it’s possible we can do this before end of year:

We need to create the geodata model, populate and get it published:
	Kirk, why don’t you add data type/format details to your sketch, share with Connor and then make a Github issue asking him to create a blank feature class in a gdb for you?
	Once the fc is created, you can point me to your data and I’ll import it and then import the whole thing to the enterprise gdb
	Then I’ll set the appropriate permissions, create a layer file, create the 1-way replica to our GIS Server Waspatial, set up a synchronization script and publish the replica to the web (for use in the online resources).

We need to ensure the data model in Salesforce will meet your need: 
	Let’s meet with Barbara to discuss the data model she created, give her content about the POD data you’ve been working with (download eWrims and fix locally, etc), and then discuss your needs and vision for how you’d like Salesforce to serve as our system of record for our PODs (with mapping integration). 

Kirk, Barbara how does this sound? Barbara, does this loose plan fit into your schedule? I know you have a ton of items on your list.

Lmk what you both thing about timing this work for late October through December.

Kirk I’m happy to lead pulling the various pieces and people together to get this done – lmk, K"

**Comment by kklausmeyer** [comment]
Connor, there may also be a field work component to this task-  We need to get the actual locations of the diversion on the McCormack Williams track.  We need to coordinate with Dawit to get permission to go on that farm.  But you should be able to drive around the levee road and take a picture and record a GPS point for each diversion structure on the island.

**Comment by kklausmeyer** [comment]
Finally, there may be some PODs that are not recorded in the shapefile now, but need to be added.  Stay tuned on that.

**Comment by connorshank** [comment]
10/23/2017  Update on Progress:
I have created the TNC_CA_PointsofDiversion shapefile and saved it to the following location:
N:\Projects\CA_FWA\projects\WaterRights\shapes\CA_TNC_PointsofDiversion.shp

The schema has been adapted as requested and all points from TNC Historic properties have been deleted.

An mxd for editing the points has also been created:
N:\Projects\CA_FWA\projects\WaterRights\mxds\TNC_CA_PointsofDiversion.mxd

**Comment by connorshank** [comment]
11/7 Update: 
Points of diversion have been edited to match the GPS coordinates taken in the field were possible.   Several inconsistencies are still present, either where more GPS locations exist than recorded points of diversion or vice versa.

**Comment by connorshank** [comment]
Create schema for point shapefile to be included in Atlas.

**Comment by connorshank** [comment]
N:\Projects\CA_FWA\projects\WaterRights\tables\POD_shapefile_schema_forAtlas.xlsx

**Comment by kklausmeyer** [comment]
Hi Connor-  I think this feature class needs some more clean up.  The field names should match the schema table exactly.  For example, I checked "N:\Projects\CA_FWA\projects\WaterRights\shapes\CA_TNC_PointsofDiversion_Atlas.shp" and there is a field name "Applicatio" with the same alias.  In the schema table the field name should be "app_num" and the alias should be "Application Number".  Please update the shapefile to create a 1-1 match with field names and the schema table.  I usually do this by adding new fields, calculating them to equal the old field, and then deleting the old field.

**Comment by connorshank** [comment]
I have updated both the schema and the shapefile so that the two now match up.   Some of the original field names were too long so I shortened these in order to keep them meaningful and legible, I also did my best to preserve field names taken from other TNC records (i.e. TRACTNAME).

**Comment by kklausmeyer** [comment]
Great!  Thanks Connor-  can you make sure to update the excel file with the schema documentation to match the final field names you used?  And finally, can you update the ArcGIS metadata to include the description of the fields.  And delete any old fields that are not needed in the schema!

Thanks!

**Comment by megrwebb** [comment]
Thanks Connor.  It will be important to have the schema and documentation as close to final as possible, but I'll have more flexibility when I import this shapefile into a gdb and eventually our enterprise gdb (e.g. lengthening field names so they match the names in our INTERESTS dataset).  IMO, it's just important that we have all the necessary fields and I know what they mean so I can make adjustments as needed.  As Kirk mentioned, we'll need to populate the general metadata (i.e. summary, description, credits, etc.) for this dataset.  This can include the field descriptions too.  Perhaps, work with Kirk to accurately fill this out?  You can refer to the metadata descriptions for TRACTS and INTERESTS (viewable via your caro-viewer database connection) to guide you since this will be the final resting place for this dataset.
