### ISSUE TITLE
Birdreturns Map -- all Oct A fields for infiltration rate contractor.

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#108]
This is a short notice request; Birdreturns asked for this when I was out on 10/6 and they need it asap, today if possible. The Oct A fields under contract are all participating in a pilot groundwater recharge program. Birdreturns is contracting with Woodard and Curran to do an infiltration rate survey in each of the Oct. fields. They need to provide location info. They'd like create a map showing just the October fields for enrollments 501-507 (use a definition query to filter for these fields). 

I will email Julia, and cc you for more details (the above is all I got), e.g. basemap (probably Streets rather than aerial), title, etc). THANKS.

**Comment by ka78** [comment]
@connorshank, thanks for doing this. can you add a pathname here and close this issue (I think you said it'd complete)? K

**Comment by connorshank** [comment]
JPEGs are located in the following folder: 
N:\WATER_Program\projects\birdreturns\2017_Fall\contractMaps
