### ISSUE TITLE
Mapping needs for TNF : Fire Modeling 

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#110]
Hi Connor -

There are some mapping needs for TNF Fire Modeling project. I am visiting SF today will give the data to you, so that we can address Ed's mapping needs. 

Thanks
Tanu

**Comment by ka78** [comment]
hey @TB2016 we can close this seeing as how Jennifer DeMartino is on point here?

**Comment by TB2016** [comment]
yes, TB
