### ISSUE TITLE
Dynamic Water Mgmt -- Map and data for Grant Application (11/6)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#111]
The Dynamic Water Mgmt team is applying for a grant to help fund groundwater recharge projects in severely disadvantages communities; they need a map and some geo-info to accompany the grant. All draft materials for the grant are due 11/6, lmk if this deadline for the draft will be an issue, if so I can jump in to help.

The details are still being worked out as they prepare the materials, but they'll need 1) a map showing the Severely Disadvantaged Communities SDAC of interest with some underlying data TBD, I think the map will need to be an 8.5x11jpg but we'll check with Julia, and 2) some geographic coordinates as per the Grant instructions.

I will email you details as I have them, but this will evolve.  There isn't a ton to do right now, but you could pull together the lat/longs now if you wanted to (I'll email what's needed).

You can make a copy of this mxd; it shows the SDAC of interest, and contains some potentially relevant data: N:\WATER_Program\projects\disadvCommunities_DAC\grant_proposal_oct2017\starterMap.mxd

**Comment by ka78** [comment]
@connorshank, for the geo-info table I did some digging:

Watersheds: the grant proposal packet points the user to [this online map](http://www.conservation.ca.gov/dlrp/wp/Documents/CALFED_Watershed_Map%5b1%5d.pdf). I saw that it say CalWater watersheds, so I looked in N:/Ca/data/hydro and found Calwater watersheds and compared them and they're the same, so pls use: N:\California\data\hydrography\calwater2.2.1\calwater2.2.1.gdb\calw221

Groundwater Basins: use N:\California\data\hydrography\groundwater.gdb\CA_GROUNDWATER_BASINS

**Comment by connorshank** [comment]
Katie,
     Looking over the grant application instructions and the geographic component, this all seems pretty straightforward.   However, I'm not sure on what project(s) this is for, I don't see any specific locations or project names mentioned in the email chain you forwarded me.   I was going to throw together a statewide map with the necessary layers now, but I was just wondering if you had any info on the projects in question, or is that the information that will be discussed on Tuesday?  Thanks!

**Comment by connorshank** [comment]
Edit, nvm, found the link to the N: drive, my mistake.

**Comment by connorshank** [comment]
Small problem: the starter_map.mxd in the folder has about half of the layer connections broken, and it appears the source of all said layers is in your documents folder.   Could you copy them into a folder within the grant_proposal_oct2017 folder?

**Comment by ka78** [comment]
Whoops, thought I did that but I guess not - I'll do this now.

**Comment by connorshank** [comment]
I have created an excel spreadsheet with the geographic information requested by the grant instructions and placed it here:
N:\WATER_Program\projects\disadvCommunities_DAC\grant_proposal_oct2017\grant_geographic_information
I have also added layers for watersheds, counties, hydroregions, and gw basins to the mxd starterMap2

**Comment by ka78** [comment]
Hi @connorshank - coming out of our meeting with Julia just now, I wanted to document the 3 outstanding projects:
1. map of the Disadvantaged Communities (symbolize SDAC vs DAC), as discussed, data here: N:\California\data\demographic\disadvantagedCommunities_DAC
2. map of **Economically Distressed** areas, as discussed (I've not downloaded data for this)
3. the analysis: sac/sj valley x sdacs and dacs x sagbi x crop types within sagbi - the deliverable here is a table that they can pivot. I have to go but I'll fill in more on this item tomorrow.

Online map links:
SDAC mapping tool: https://gis.water.ca.gov/app/dacs/
EDA mapping tool: https://gis.water.ca.gov/app/edas/
