### ISSUE TITLE
Groundwater Dependent Ecosystem Review Webmap (11/14)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#113]

**Comment by kklausmeyer** [comment]
Hi Connor-

I would like an .mxd converted to a simple webmap for a handful external partners to review.  It would be better if only people with the link can view it, but if it is easier to make it public, I think that is fine.  There isn't any super sensitive info in the webmap so public is ok.

Here is the 10.2 format mxd: "N:\Projects\Groundwater\mxds\USGS_GW_depth_review10_2.mxd"

I updated the colors and gave the layers intuitive names, so I hope that helps.

The main difficulty will be in getting the potential groundwater dependent ecosystem layer to draw.  I will send some code I used in the past to do it.

**Comment by kklausmeyer** [comment]
Here is a doc file I used for my notes on how to publish the data to stratus:
[Methods to Publish pGDE data on ArcGIS.docx](https://github.com/tnc-ca-geo/gd_intern/files/1459610/Methods.to.Publish.pGDE.data.on.ArcGIS.docx)

Here is a link to the current webmap that works really well with the earlier version of the data: http://arcg.is/2gffy0u

**Comment by kklausmeyer** [comment]
Thanks and let me know if you have any questions.  If you can get a draft to me by next Friday that would be great!

**Comment by ka78** [comment]
@connorshank - when you get to the point of adding this layer(s) to a web map, check with me.  I believe you'll want to use a different REST Url when you're consuming Stratus services... but I need to get my facts in order before I can give you those details.  - Katie

**Comment by connorshank** [comment]
Draft Webmap has been created and populated, link here:
http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=b10a18e7ed454552b1f92b6971709af3

The mxd with the three data layers have been published to stratus here:
http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/GDE/USGS_GW_depth_publish_10_2/MapServer

The data has been successfully added to the webmap, though there is a problem with displaying all features, especially at larger scales.   The GDE layer in particular does not get fully drawn when viewing the map at a state-wide level.

**Comment by ka78** [comment]
@connorshank you could try creating a tiled layer for GDEs along with feature access.  I did this a few years back with protected lands (for the Atlas) and it worked nicely.  So, the tiled layer allows for speedy rendering, and the feature access allows for inquiry via pop-ups.

**Comment by connorshank** [comment]
Update:  I have found a way around the above drawing issue.   Rather than add the layers as their individual urls, I have added them together using the mxd url from stratus.   Because I published the map as a tile cache this allows all features to be drawn at all multiple scales, the only downside is that the individual layers cannot be toggled on and off without turning off all layers.

**Comment by kklausmeyer** [comment]
This is looking great Connor.  I updated the input data for the wells and saved a new MXD.  Can you replace the old webmap with the data from this one?  

"N:\Projects\Groundwater\mxds\USGS_GW_depth_publish2_10_2.mxd".  Ideally before turkey day?

**Comment by connorshank** [comment]
I have switched the displayed data to the new mxd, from the following rest url:
http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/GDE/USGS_GW_depth_publish2_10_2/MapServer

Let me know if you'd like me to delete the old service.

**Comment by kklausmeyer** [comment]
Awesome Connor-  this worked out really well.  Please delete the old service.  

Here is the link to the final webmap with the formatted popups:  http://arcg.is/1jyyiz
