### ISSUE TITLE
Test Accessing data on Sac Server

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#115]
See attached Map for SacRiver Property, 
https://tnc.box.com/s/hj1v8hdwnqbq4qzadz0bmeuiebktkx94

Find the shapefile and upload it here 
https://tnc.box.com/s/326byvtstjwvst36hv4kycqd1oadpgdl

Let's see if this actually works. 
Thanks
Tanu

**Comment by TB2016** [comment]
Kirk and Katie -- just adding you guys to the thread to see if Connor can actually access data on Sac Server. 
Thanks
T

**Comment by connorshank** [comment]
I am able to open and view the mxd, it is a little slow, but it works.   I have also uploaded a copy of the associated shapefile to the linked box folder.

**Comment by ka78** [comment]
great @connorshank, glad to hear it!

**Comment by connorshank** [comment]
Great. Few following tasks:

1.	Create a kml of the entire mxd, name it Hartely Island location. 
2.	Create a KML folder in the box folder called “HarleyIsland” and upload it there
3.	Create a gdb from all the layers visible in the mxd, create a folder “gdb” within HartleyIsland on box and upload it there, if you want to split the .gdb into shapes and grids, that’s fine by me. 
4.	Create a mxd folder on BOX/HartleyIsland – upload it on box,
5.	Once you create the mxd, I should be able to map to all the layers in the mxd, using the gdb you just created above. 
6.	Lastly, just upload the polygon in a separate shapefile folder in box. 

Thanks
Tanu

**Comment by TB2016** [comment]
Connor -- can you please send me an email to my tnc address, when this is
done.
Thanks
Tanu

**Comment by TB2016** [comment]
Thanks again Connor,  closing this issue. Tanu
