### ISSUE TITLE
New layer / function for pGDE map

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#116]

**Comment by kklausmeyer** [comment]
Hi Conner-  as we discussed, I would like to add the function to select or highlight one vegetation vegetation type at a time in the pGDE database layer in the webmap you built.  Here is the link to the latest webmap:  http://arcg.is/1jyyiz.  

Here is the mxd with the pGDE data:  N:\Projects\Groundwater\mxds\USGS_GW_depth_publish2_10_2.mxd

Here is the feature class of the pGDE database:  N:\Projects\Groundwater\gdbs\CA_pGDE_v0_4_1_20170602.gdb\pGDE_v0_4_1_BasinsOnly

I would like to be able to select unique veg_Names.

If you are able to get that to work, I would like to be able to do the same for wet_Name field as well.  Note that veg_Name and wet_Name basically reflect a union of two datasets, so you can't select each one independently.

**Comment by connorshank** [comment]
Kirk, I've created a mxd containing the dissolved vegetation type layer, ready for publishing, let me know if this is what you had in mind.
N:\Projects\Groundwater\mxds\USGS_GW_vegName_publish_112817
The shapefile can be found here:
N:\Projects\Groundwater\shapes\pGDE_v04_4_1_vegName_diss.shp

**Comment by kklausmeyer** [comment]
This looks good-  I have thought of a way to simplify this task-  there are only a subset of veg types in question.  Use this table, "N:\Projects\Groundwater\tables\pGDE_veg_names_to_review.xlsx", join to the layer you created, make sure all of the names join correctly (there are 100 types), and use that to publish.

I also noticed something weird with Coast Live Oak and Willow-  they are not dissolved and have numbers in front of them?

**Comment by connorshank** [comment]
I noticed this as well, not sure what exactly happened but it must have occurred during the dissolve step.   I have resolved the issue by editing the names and re-dissolving the layer.   New layer can be found here:
N:\Projects\Groundwater\gdbs\CA_pGDE_v0_4_1_20170602.gdb\pGDE_v04_4_1_vegName_diss2

**Comment by kklausmeyer** [comment]
Thanks Connor-  let me know if you have any luck publishing the layer, adding it to a webmap, and then searching my vegetation type.  I would like to have it done by thursday this week if possible.  Thanks!

**Comment by connorshank** [comment]
I've published the mxd containing the vegName layer:
http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/GDE/USGS_GW_vegName_publish_112817/MapServer
It doesn't look like I can edit the current webmap, however the symbology is just the basic outlines of the polygons, like we discussed.   This version is not tiled, let me know if it has trouble loading all the features and I can re-publish a tiled version.

**Comment by connorshank** [comment]
Kirk, I've published the tiled version of the vegName mxd at the following url:
http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/GDE/USGS_GW_vegName_publish_112817_cache/MapServer

**Comment by kklausmeyer** [comment]
Nice!  That one works really well.  I will use it
