### ISSUE TITLE
Print old maps for Mike Sweeney

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#117]

**Comment by kklausmeyer** [comment]
Mike would like to frame some old maps.  He found some images online that are high enough resolution to work.  I printed a draft for him so I think he is ready for the final.  The first one is of California as an island-  You can print it at about 21x29 inches.  Use the "Best" setting for the quality, and the standard paper is fine.  Mike wants to get it framed with glass.  If you can get it to fit into a standard size mat and frame even better. You might get away with printing it a little larger (22x32) so it fits in a 30x40 frame.  Here are the standard frame sizes and mat openings:  https://www.usaoncanvas.com/include/guide_picture_framing_rules_standard_sizes.php.  The second picture (anacapa island) has lower resolution so we will probably need to print it out smaller.  Do a test at 8x10 and 11x14.  You can print on the standard printer to test the dimensions.

**Comment by kklausmeyer** [comment]
Please email Mike when you have the next version ready for him to review.  I don't think there is a timeline but sometime this week would be great.

**Comment by kklausmeyer** [comment]
Here are the files:  https://tnc.box.com/s/s5op34f573qdy6cnbojxqwv7qbevzc92

**Comment by ka78** [comment]
Hey @kklausmeyer -- if Mike wants to frame these we might consider having Kinkos print them on a higher quality printer/paper/ink than we have here; @megrwebb any thoughts?
We could certainly print them in house to see how they look but our plotter is not the highest quality - it's good, but not excellent.

**Comment by kklausmeyer** [comment]
I was thinking we could give Mike our best go at it, and if he wants higher quality, we can go to kinkos.  @megrwebb I would be interested in your thoughts.

**Comment by megrwebb** [comment]
@kklausmeyer, I would highly recommend taking these to Kinkos and not printing them on our HP plotter.  The plotter will work well for testing size and image quality, but the plotter ink is not of highest quality and will fade quickly over time. Since these will be framed, it sounds like Mike is hoping these will last a long time.  I’d go to Kinkos and explain your intention so they can recommend and use the best quality paper and ink for this and possibly add a protective coating.

**Comment by bcohen27** [comment]
I'll put in a plug for a more dedicated print shop like https://www.e-arc.com/location/san-francisco-jackson-street/#   I think you'll get better results than Kinko's. I have used them here in San Diego with good results.

**Comment by megrwebb** [comment]
I agree with Brian.  Or another idea - go to the David Rumsey Map Collection website and find these maps or something similar.  You can order prints - framed or not, matted or not and at different sizes.  Maybe easier and cheaper?  https://www.davidrumsey.com/
