### ISSUE TITLE
Create property maps for real estate deal routing and approval

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#118]
Hi Conner –

This is a sensitive project and highly confidential.  I’ll send you an email with more details, i.e. property name, etc.

Two maps needed – one regional context and one zoomed to the property boundary.

Use these mxds from a previous deal as your map template:
N:\South_Coast\Projects\Sam\Mxds\CA_SantaAnaMtns(Applegate)_map1of2_20171012 - Copy.mxd
N:\South_Coast\Projects\Sam\Mxds\CA_SantaAnaMtns(Applegate)_map2of2_20171012 - Copy.mxd

Here are a few details (but please let me know if you have questions or need clarification on anything):

1)	Rename files and place in project folder (I’ll provide more info in an email)
a.	Typically, we use the conservation area and property name for file name and map title (this info is in the Salesforce deal record or TNC Conservation Area and TRACT data in mxd).
2)	Do a definition query on the TRACT layer by property name and zoom to property area and adjust to an appropriate scale for the map type
3)	Update map legend, layer definition queries, and styles where needed (use style file from WO: N:\Projects\ProjectPackageMaps\New_Standards\style_files\ PPM_Style_File_20110802.style)
4)	Remove existing annotation layers and add new labeling for layers and convert to annotation “in the map for features in current extent” for better placement and flexibility
5)	Although these fonts are in the style file, we are no longer permitted to use Oakleaf and Imago.  Instead, use the current TNC fonts - Chronicle Office and Whitney Office.  You should have all other fonts installed on your computer.
a.	Chronicle (bold) – use for map title, ecoregion name (map inset), conservation area name, scale bar, scale text
b.	Whitney (bold) – use for protected/managed area names, tract name, TNC Interests (fee, easements, etc.)
6)	Export final maps as PDFs – RGB, 400 dpi, image quality between normal and best

It would be great to have these completed as soon as possible (maybe mid-week?), but let me know if you have trouble fitting this in.

Thanks,
Megan

**Comment by megrwebb** [comment]
Hi Conner,

Do you have time to meet sometime this afternoon to discuss some edits to these maps?  I think we only need ~15 minutes or so.  I'm available after 2:30.

**Comment by connorshank** [comment]
Megan,

               I’d be happy to meet around 2:30, do you want me to reserve a room?

Sincerely,
Connor Shank

**Comment by megrwebb** [comment]
Sure, that would be great.

**Comment by megrwebb** [comment]
Hi Connor -

I've looked over your most recent drafts and will be sending you additional edits via email.

Thanks,
Megan

**Comment by megrwebb** [comment]
Connor -
The project director would like the conservation easements labeled with the easement holder (e.g. CDFW, etc.).  Would you add these labels to both maps in the same style as the managed land labels? You can abbreviate the labels, but if you do please add the abbreviation and full name to the legend.   Thanks!

**Comment by connorshank** [comment]
pdfs located here:
N:\Central_Valley\Projects\Tlr\plots
corresponding mxds:
N:\Central_Valley\Projects\Tlr\mxds
