### ISSUE TITLE
data conversion/sharing w/birdreturns field techs (12/14, flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#120]
The field techs are currently working on a crane study.  They're using this AGO map in the Explorer for ArcGIS app.  They also use a handheld GPS unit.  They've requested that some data be downloaded from the web map, converted to a format they can upload to their handheld (.gpx) and emailed to them.  

I'll send you the email where they explain which records they need.

The "green dots" Ian describes should be [this feature layer](http://tnc.maps.arcgis.com/home/item.html?id=f942ce2fd586440f8d83744ddf5e9f3d).

You can view the data in [this web map.](http://tnc.maps.arcgis.com/home/item.html?id=50f4fe316ef94eb9beb3fedd6977b50d)

Please save any data you export or convert to this location:  N:\WATER_Program\projects\cranes

I invited you to the Cranes - TNC group so you hopefully have all the access you need.

Their work is underway and they'd love to have this data soon, but as our time allows.  They can function with what they have; this is more of a bonus.

**Comment by ka78** [comment]
@connorshank I emailed the .gpx file from Ian (bird field tech). Can you please store it here: N:\WATER_Program\projects\cranes, convert the .gpx to a shapefile and publish it to AGO, sharing it with the cranes - TNC group?  When that's done I'll add it to the web map since I'm the owner of the group and the owner of the web map. Thanks.

**Comment by ka78** [comment]
Hi @connorshank - Thanks for jumping on this. I added the Beck layers to the Butte Basin web map. Then tried to open the web map in Explorer and got an error "Unable to open web map. The shape must have a z-value".  I've run into this before; I'll share an email with you explaining the issue and the fix. Stay tuned.

**Comment by connorshank** [comment]
I have updated the layers to disable Z and M values, and re-uploaded the layers to AGO as a feature layer named Beck_Crane_map2.

**Comment by ka78** [comment]
@connorshank - over break Ian sent me the .gpx file for Shaw Pond which I put up on AGO in the crane folder (and here: N:\WATER_Program\projects\cranes). Thanks for your help on this; closing it for now.
