### ISSUE TITLE
Update Salesforce Water Rights Records (7/25 flex)

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#122]
Hi Kirk-  Thanks for your reply re. the status of your effort to compile information around TNC’s water assets.  Siobhan shared with me the attached spreadsheet which I believe she created from your initial water rights database.
As for the Water Trust work, I think it will be important to get this information in a format that could easily be mapped in the future.  This will likely be important as we enter our strategic planning stage of the water trust work this March-May.  
Here is a list of details we might want to know in the future with respect to our water assets.  The items below in blue are already populated in the attached spreadsheet.  The items in red are potential additions but I look to you and Cat to add other characteristics we’ll want to track.  

As for timeline, it would be nice to have most of this information collected by end of January.  I’m not sure how realistic that is but we may ramp up our efforts with AMP Insights on the Spatial Analysis work around this time and it would be nice to have this layer available for use.  I welcome any feedback you might have about how easy/hard the additional information might be to collect.
Amy

•	TNC property name
•	Property manager
•	eWRIMS water right number or ID
•	other water right identifier (for example in the Shasta we have diversion #’s)
•	“Record type” in this spreadsheet seems like it includes water right type (pre-1914, riparian etc.) but also includes groundwater (not sure if these are actual groundwater rights).  Might be good to create to columns which say whether the water is groundwater or surface water and then describe the specific water right type.
•	Adjudication (Y/N)
•	Face value (AF/yr) How are groundwater rights quantified?  Is it AF/year or do they use some other sort of unit?
•	Description
•	Purpose of Use
•	Description of technology (assuming this is whether or not there is a gage and what type)?  Unclear

Potential Additions:
•	Has the water right been actively put to beneficial use in the last 5 years?   
•	Is the water right located on the TNC owned property?
•	Location of the water right (coordinates)
•	River name
•	Watershed name
•	SB88 compliant (Y/N)
•	Located in a SGMA basin?
•	Crop type (pasture, row crops, vineyards, etc.)
•	Shared point of diversion with another landowner?
•	If Adjudicated, who is the responsible party to regulating the adjudication (DWR, Private entity, Special District)

Here is where I have been doing my water rights work:
"N:\Projects\CA_FWA\projects\WaterRights "

I don’t know if the attached file is on the N drive, but you can work from this one which has some similar information:
"N:\Projects\CA_FWA\projects\WaterRights\tables\TNC_WaterRight_Summary_20170504.xlsx"

**Comment by connorshank** [comment]
I have added the requested fields and filled them in where possible using some simple overlap analysis in ArcMap, referencing Salesforce when needed.   As I mentioned when we were chatting before, some of the requested fields are probably going to require input from site managers and leasees (sp?) for each of the properties, as the Salesforce water rights record are pretty spotty.   Updated table can be found here:
N:\Projects\CA_FWA\projects\WaterRights\tables\TNC Water Rights Portfolio March 2017

**Comment by kklausmeyer** [comment]
Hi Connor-  I'm updating this request to reflect the current state of the project.  Katharine Anderson and I have updated the Salesforce records type to include all of the water rights info we want to collect.  Now we need to make sure there is 1:1 parity between Salesforce and eWRIMS.  The biggest problem is Staten Island where we have about 50 water rights.  I would like you to update the salesforce records so there is one record for each water right.  I have done 3 so far, but the rest need to be done.  Here are the steps: 

1. Go to the water right record in salesforce- e.g., https://na60.salesforce.com/a2f0c000000EGs6
2. Press the "Clone" button at the top of the page to start a new record
3. Go to the "Detail" sheet in this excel file: "N:\Projects\CA_FWA\projects\WaterRights\tables\TNC_WaterRight_Summary_20170504.xlsx".  I have filtered the worksheet to only show the water rights for Staten Island (see column AJ).
4. Copy the Application number in column B and paste it in the "Statement ID" field in salesforce.  I have highlighted the ones I have already done in yellow.  
5. Open this file: "N:\Projects\CA_FWA\projects\WaterRights\tables\WaterDivData2018.xlsx" and look up the "Siphon_Number" based on the application number for the water right your are looking up and update the number in salesforce in the "Name of Right, pond, POD or well" field.  Eg. "SI 35" in the excel file is the name of the siphon associated with water right "S018525"- so update the name of the right as "Siphon 35".
6. Open the link in Column AG of the TNC_WaterRight_Summary_20170504.xlsx excel file titled "eWRIMS_URL" to open the record on eWRIMS.  
7. Click the "View Statement" link to open a PDF of the water right.  Check to make sure the "Source" field is correct as the entry on line "C" of the PDF.  Also check that the "Name of diversion works" is the same siphon number as you entered in step 5.
8. Back on the eWRIMS page for the water right, click "View Reports".  Check that the "Date Received" date for 2017 is the same as "Date Last Report Filed" field in salesforce.
9. Click "Save" in saleforce and move on to the next water right for staten.

**Comment by ka78** [comment]
hey @connorshank if you need Salesforce help, I'll volunteer @AndersonKatharineTNC to help address your questions.

**Comment by AndersonKatharineTNC** [comment]
Yep! Happy to help if you need.

**Comment by connorshank** [comment]
Salesforce records have been updated for all points of diversion listed in TNC_WaterRight_Summary_20170504,
S019181 and S019178 did not have statements available, so siphon numbers are not confirmed for those records.
