### ISSUE TITLE
Playa vegetation review (1/10)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#126]

**Comment by kklausmeyer** [comment]
Hi Connor-

I would like your help to review about 160 polygons that represent Playas in the Mojave Desert.  I set up a kmz for you to use to do the review.  It includes polygons for each playa in red, and two folders for you to add placemarks.  One folder is for placemarks that indicated you surveyed the entire playa and saw no obvious signs of vegetation.  The other folder is for placemarks that highlight the general location of vegetation within the playas that have it.  I have started filling out some placemarks in both folders so you can see what I would like.  In the end I will take the "No Obvious Vegetation" placemarks, convert to a shapefile, and remove those playa from our indicators of groundwater dependent ecosystems database. 

Note that some of the playas are broken into multipart polygons- please add a placemark in each part.   

Review kmz is here:  "N:\Projects\Groundwater\kmlz\Playa_Review.kmz"

**Comment by connorshank** [comment]
I have reviewed all of the playa polygons in the original kmz file and added either 'Vegetation' or 'No Obvious Vegetation.'   There are also several markers labeled 'Vegetation?' to indicate that it is hard to discern from google's aerial images whether or not the objects in question are rock formations, shrubs, or something else.   I have saved the updated kmz file as Playa_Review_CSedits.kmz in the same location as the original:
N:\Projects\Groundwater\kmlz

**Comment by kklausmeyer** [comment]
Thank you Connor!  I will review the kmz this week and let you know if there is any follow up

**Comment by kklausmeyer** [comment]
I reviewed the .kmz, checked some of the questionable areas, and made a few final edits.  This is very helpful!  I have sent it to the external team for their review.  Here is the most recent .kmz:
"N:\Projects\Groundwater\kmlz\Playa_Review_TNC_20180109.kmz"
