### ISSUE TITLE
Data Mgmt - CNDDB and Spotted Owl Observations January 2018 update

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#127]
I’ll send you the January email with link, username and password to download data.

1) Click link and go to the Monthly Data Updates tab>CNDDB and Spotted Owl GIS data updates>Data Portal

2) Import the updated data to corresponding geodatabases on CAROGIS: N:\California\data\bioscience (i.e. CA_NDDB.gdb and CA_Spotted_Owl_Observations.gdb)

3) Delete the old data and name the new data by the same name (i.e. CNDDB, CNDDBPNT, Spotted_Owl_Observations, Spotted_Owl_Spider_Diagram)

Note: Do not update layer or PDF files unless more current ones are available

4) Add "*This is the January 2018 monthly release/update*" to the metadata for each feature class under the Summary section.

Not urgent, but let me know when this is done and I'll send an email out to GeoDesign.  Thanks!

**Comment by connorshank** [comment]
The January updates have been successfully downloaded and added to the existing databases in the N:\California\data\bioscience folder.

**Comment by megrwebb** [comment]
Thanks Connor.  Would you please put "This is the January 2018 monthly release/update" at the beginning of the summary for each feature class and add an asterisk to either side of this statement?  I'd like to make sure this is obvious to users.

**Comment by connorshank** [comment]
No problem, the descriptions have been updated.

**Comment by megrwebb** [comment]
Great.  Thanks!
