### ISSUE TITLE
Mapping Support for TCSI - d/l from box -  Flex Feb16th 

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#128]
Hi Connor, 

I will send a map package your way for the TCSI  landscape embedded with Blueprint results and some additional dataset's.  Please download the package on N Drive, here N:\Sierra_Nevada\Projects\TCSI\Mappackage

Open the  map package and have it all ready for map edits. 

Go through the map package and subset all GRID layers (stored with Sierra_Grids) by TCSI boundary. Save them within the GRID. Maintain the original name in the raster.

D/L stuff from box folder here to respective folders on N drive above. 

Some mapping edits will be needed on the maps I produced. Will update you on that as I receive comments

Thanks 
Tanu

**Comment by TB2016** [comment]
Ok Connor updating the task 

1.  D/L these below here on N Drive **N:\Sierra_Nevada\Projects\BluePrint2017\BluePrint\Grids\BiodiversityGrids**

Shapefiles and Excel file : https://drive.google.com/drive/folders/1ZBA3HZ9Jgq-KQARmH-5r4-A_MHHhIF2_?usp=sharing

Grids: https://tnc.box.com/s/v9corlifn74q5wfho8glvxvvowc55sjj

2. D/L  from these datasets https://drive.google.com/drive/folders/1_CRFpvaZOkUeHVAOnPixMEgpe9yBSG8u?usp=sharing

to N drive below. Create a new directory within "Finalresults" FINAL DATA DELIVERABLES before the copying. 

N:\Sierra_Nevada\Projects\BluePrint2017\BluePrint\FinalResults

The GDRIVE contains: 
•	SN_PrioirtyAnalysis_FACTS_BurnSeverity_WUI_acres_Aug2017
•	SN_PrioirtyAnalysis_RegionalAnalysis_Final_Aug2017_PrioirityWS
•	Sierra_HUC8s
•	Frenchie_Boundary
•	NewStudyArea (From the French Meadows directory)

And the GRID files. 

3. D/L this mappackage as well to Blueprint2017/Make Directory"Mappackage"

4. From TCSI box folder /Arcmap/ ONLY D/L the TCSI_Jan17.mxd -- don't d/l the folder called "TCSI_Jan17"

5. Let's loop back once you d/l everything. I will try to re-create the mpk from home. 

Thanks
Tanu

**Comment by TB2016** [comment]
@connorshank , Connor, I have sent you the links to the datasets on Box. In addition
Can you see this webmap and figureout a way to d/l these layers 

http://snc.maps.arcgis.com/home/item.html?id=44d5fc1587a245898a8830612cb09481#overview

DOn't waste too much time on D/L or opening these layers on ARCGIS. Better would be if you can just create point files for these shapes. Exclude Biomass layer. Basically we need a shapefile of different projects within the TCSI landscape. 

Thanks much
Tanu

**Comment by TB2016** [comment]
@connorshank  Connor once you make the final maps, upload them here 
https://tnc.box.com/s/89fw3qx8gh3fgerjxcoemvx8v6hxlzwo

d/l the ppt at your end and upload the maps on these slides:
https://tnc.box.com/s/yfqyqqg0legfrb9hh9c7dxugc76xwp9q

>>slide 13 upload the PFRID map with location information
>> slide 14 upload new map
>> slide 15 make a new map with 10 classes, use a color ramp to show all 10 classes distinctly
>> slide 19 upload locations
>> slide 20 add the inoperable legend in the map, and make the map with 3 FRI classes 
>> Note there is map (last slide) he wants focused on Tahoe National Forest. 

Once you are done updating the maps in the ppt, send me a note and upload it back on box within the presentation folder.

**Comment by connorshank** [comment]
Tanu,
I have uploaded an updated version of the ppt based on the above edits.   It is in the same presentations folder, named:   Sierra-TCSI Watershed Priorities_Jan17_2018_Connor_edits

**Comment by TB2016** [comment]
@connorshank 

Thanks Connor. 
Can you update the maps on box as well here >> https://tnc.app.box.com/folder/45113670776

Where is the map zoomed in for Tahoe National Forest?
Three cheers for being the geospatial Ninja :) 

Tanu

**Comment by TB2016** [comment]
@connorshank 

Connor, last few tweaks then we are good to go. 

1. Found the Large Tree Patch dataset. It's located here https://tnc.app.box.com/folder/19439098324
D/L them and store them within Sierra/Data/LargeTree directory. Make a folder if it does not exist

2. Load both the TIFF's and create new map for slide 19, over lay the location information, Label them as shown on the slide  here https://tnc.box.com/s/jijgbsh6lh8ohaota5pckl9ms6f763b7 and load it here
https://tnc.app.box.com/folder/45306523091 (SEE the map names. replace the new maps you make keeping the names corresponding to the slides)


3. Few more comments on the slides. upload all the final maps [here](https://tnc.box.com/s/wv7tqwksyaiwxvawxn9qww7jv88w35uu)

Let me know once you are done. I will upload the slide. Thanks Tanu

**Comment by TB2016** [comment]
Upload the Location and Project file you created within the data folder in TCSI_cities and TCSI_projects

Thanks
Tanu

**Comment by connorshank** [comment]
Tanu,
I have uploaded the edited maps and data to the requested file locations on Box.   The cities layer is essentially just the CA_PPL statewide layer with a Definition Query narrowing it down to a few towns in the TCSI region.   I also updated the ppt and added it to the presentations Box folder.

**Comment by TB2016** [comment]
@connorshank 
Thanks Connor very much. Can you just clip the CA_PPL data layer by the TCSI or Sierra Regional Boundary and load it up on Box?

Thanks again
Tanu

**Comment by TB2016** [comment]
@connorshank 

re-opening this issue. 
Address Rodds comments on the ppt, here https://tnc.box.com/s/jijgbsh6lh8ohaota5pckl9ms6f763b7

Just to remind : 
(a) The BluePrint_(Report) Priority Watershed is the attribute : PriorityWS
(b) The normalized prioirityWS : Ovr_nIndex

Things to do:
1. Subset the current data by TCSI == 'Inside' >> address the map edits. Upload the data >>TCSI/DATA/NormalizedIndexed_BPResults
name the file leading by TCSI

If any new data is created  upload on box and let me know.
Thanks
Tanu
--

**Comment by TB2016** [comment]
@connorshank Rodd wants SPI parcel overlaid on one of the map below.. (Side 16) I am uploading the dataset. Also note the deadline is bumped to Feb 16th, thanks Tanu

![image](https://user-images.githubusercontent.com/17483557/36113855-16cd07d8-0fe3-11e8-8728-6612882b6420.png)

**Comment by TB2016** [comment]
@connorshank  we also got the data from SNC 
Here is the link on box https://tnc.box.com/s/zgj942pqni3o0taa4hv4fs17m2zl9jfs

Update the property map with these layers.
Thanks
T

**Comment by TB2016** [comment]
@connorshank  hi Connor, I just noticed that the WIP layer that we received from SNC does not have the HUC12 (green layers). Use the ID on the WIP site and select the HUC12 from the SN_regional_HUC12 ID..

SNC did not alter the HUC12 boundary so the boundary of those green polygons should match up with HUC12 boundary on our regional analysis. 

Here is the link to  SNC site https://snc.maps.arcgis.com/apps/MapTools/index.html?appid=b9326960940c45688b9547631b70e570

Thanks
Tanu

**Comment by connorshank** [comment]
I have uploaded the latest set of map images based on the comments in the powerpoint.   They are in the   TCSI>Maps >12Feb2018 folder on Box.

**Comment by TB2016** [comment]
@connorshank 

Slide 15 : change the text of location to match up to slide 14
Edits to map for slide 18

SLide16 : Its very confusing. Too many colors. SPI parcels and TNF looks same. Try to stay with dark blue color for PriorityWS

Make all property related boundary to a line so that the underlying WS priority is visisble
Find HUC12 boundaries for following HUC12 watersheds and add them as well. 

1. Deer Creek-North Yuba River
2. Bonta Creek-Cold Stream
3. Boca Reservoir-Little 
4. Big Valley Canyon-North Fork American River
5. Long Canyon
6. Squaw Creek-Truckee River

Can you convert the WS Priority Legend to a continuous graphic instead of thematic?


Thanks
T

**Comment by TB2016** [comment]
@connorshank 

SLIDE 20  I forgot to mention that show the polygon layer of connected forest patch not the grid layer called as large tree (>30dbh). 

Thanks
T

**Comment by connorshank** [comment]
I've uploaded most of the updated map images to Box (15Feb Updates folder), however I was not able to find a large tree polygon file, all the data seem to be rasters.   Tanu, could you point me in the direction of where this data might be, or send me the shapefile via Box?   Thanks!

**Comment by TB2016** [comment]
@connorshank  --u are right both are actually grids. Use the layer which is called as effective patch.tiff not just the large tree grid

I think you already have it. Incase not here it is 
https://tnc.box.com/s/aewceqq0v4902xrg91ih8e8rxesaopss

thanks
t

**Comment by TB2016** [comment]
@connorshank  --- -here are the final edits on the maps needed for tomorrow meeting. Ping me on skype to see the WS color ramp.. This edits are high priority. Hopefully we can deliver them to Rodd within next few hrs.  thanks T

https://tnc.box.com/s/vutoum4lbno87q95bg6trnup141wiybb
