### ISSUE TITLE
East Bay Sub-Regional Assessment Maps (2/15 Flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#130]
Hi Connor - 

We are finalizing the East Bay Sub- Regional Assessment.  

[Draft RAMP SRA_2017.11.27_clean.docx](https://github.com/tnc-ca-geo/gd_intern/files/1624300/Draft.RAMP.SRA_2017.11.27_clean.docx)

There are a couple of mapping and data needs in order to do so.

1. Update excel tables of transportation impacts assessments for Alameda and Contra Costa counties based on Table 6-1 in subregional assessment. Once this is done I will rerun my analysis in R and output a dbf table.
The excel tables are here: 
contra costa: N:/SF_Bay_Area/Projects/EB_SRA/cc_RAMP_BayArea_impacts_6March2017.csv", 
alameda: "N:/SF_Bay_Area/Projects/EB_SRA/al_RAMP_BayArea_impacts_6March2017.csv"
project grouping: "N:/SF_Bay_Area/Projects/EB_SRA/projectGrouping2.csv"

2. Create 3 report quality maps based on the join of the dbf table to the hexagons similar to update figures 6-4, 6-5, and 6-6. I will send you the dbf table after you update the csv files.

3. Create a report quality map for figure 6-1 for planned transportation projects.
-I'm waiting on the updated shapefile from AECOM.

4. I'd like to create a map that can show the MCA proposed site along with the transporation projects that it services.  Can you create this map for 1 of the 7 and if we can find something that  communicates the info clearly we can move forward with the rest.  This would be mapping table 6-3.  Potentially 1 map per row.

**Comment by connorshank** [comment]
Carrie,  I've updated the three tables listed above with a column indicating whether or not the project is included in Table 6-1 of the current report.   The new tables are in the same folder, they just have more recent dates in the file names.

**Comment by connorshank** [comment]
Closing for now, can re-open if/when we get feedback from outside partners.
