### ISSUE TITLE
Update Oil and Gas comment letter/map (1/24/19)

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#136]
Create map series for California section of TNC comment letter on offshore oil and gas leasing policy changes under Trump administration.   

We we're imaging 2 maps for each of the lease areas in Ca - one for current managed areas (marine and coastal terrestrial) and one for habits (aka things we care about).

Use the Esri basemap for bathymetry 

Work-space created in N: drive at the following location:
N:\California_Current\Projects\Oil & Gas

Box link:
https://tnc.app.box.com/folder/45774127508

**Comment by mmerrifield** [comment]
some specific notes about data / symbology / layers 

Marine Managed Areas Map
Add ASBS (Areas of Special Biological Concern) in distinct color and or hatching (SWRCB)
Add HAPC (Habitat Areas of Particular Concern) in distinct color and or hatching (NOAA)
Add Non-Trawl RCA (Rockfish Conservation Areas) n:/california_current/shapes
differentiate terrestrial protected areas by Federal / State / Private (e.g. TNC & other easements)
Add salmonid critical habitat designations

**Comment by mmerrifield** [comment]
some specific notes about data / symbology / layers

Biological Significance
generally - use single color for all layers stacked on top of each other but have gradient variation between offshore and nearshore layers - for example
bathy complexity
rocky reef
seamounts
canyons
deep sea corals

kelp
seabird colonies
pinniped haulouts
estuaries (either as point or polygon)
salmonid streams (USFWS)

and the legend or separate text box to list out all the features we've included in plain terms (basically the names I used above)

**Comment by connorshank** [comment]
Looking at Biodiversity maps first.
I would change title to include Figure 1 (gave those to you earlier) and to say “Some Known Features of Biodiversity Significance” [since these are not the only areas of biodiversity importance -just the ones we have data on these features].
 
It seems a bit “pink” – can we include a few different colors to represent a few different categories of features?
 
Should include the nearshore rocky/hard substrate from the fine scale state waters mapping?
 
What are the squares?
 
There should be hundreds of Deep sea coral points….that doesn’t seem reflected here?
 
Anything else we can add?

**Comment by kklausmeyer** [comment]
Hi Connor-  I got a request from Mary Gleason to update this map.  She will be out on vacation soon, so please contact 
Kate Kauer <kate.kauer@tnc.org> and Stephanie Dashiell / Erica Brand on all correspondence.  

Here is Mary's initial request to Matt.  I'll forward you the email so you get the attachments as well.

Hi Matt,
Connor made some statewide managed area maps for our comment letter on Oil & Gas development (attached for reference).
 
We are now needing to comment on BOEM Offshore Renewables “Call Areas” and want to include 2 regional maps that show these 3 potential lease areas (2 off Morro Bay and 1 off Humboldt) and the surrounding managed areas. 
 
Wondering if Connor or someone can do these for us?  We would need them in the next two weeks (by Jan 24)….sorry a bit last minute but we just decided to comment.
 
If so what we would need is:
1. Someone to download the shapefile for the 3 BOEM Offshore Wind leasing areas in California – Diablo Canyon, Morro Bay, Humboldt  (jpegs from BOEM attached for reference)
2. Adapt the statewide MMA maps into two regional maps (1a. Central CA and 1b. Humboldt) that show these wind lease call areas and surrounding MMAs.  We should include all the same MMAs from the map Connor made.  Just be sure to replace the BOEM “Oil and Gas Planning area boundary” with these new BOEM offshore wind call areas.
 
Doable??
Thanks!
mary

**Comment by connorshank** [comment]
Location of new mxds and images for offshore wind maps:
N:\California_Current\Projects\Offshore_wind
