### ISSUE TITLE
HSR impacts and live-demo with Sasha (2/12)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#140]
Hi Connor - Sasha needs to update a spreadsheet (in word doc below) that shows the impacts of current HSR alternatives from Morgan Hill to Pacheco Pass using new mitigation option data.

New data here:
N:\California\data\infrastructure\20180208_HSR_alternatives

Here are the older HSR alighments on N.
N:\California\data\infrastructure\20161207_Confidential_HSR_Alignment_SHP – about a year old.

I'm not sure exactly what you will be screening for impacts yet, but a good start would be getting the new and old alignments in a mxd for her to look at.  She would also like for you to help with live analysis in a meeting on Tuesday between 9-11.  Would you be available to help her with that?

**Comment by cschloss** [comment]
[StakeholderMatrix_RDPRevised_7Feb2017.docx](https://github.com/tnc-ca-geo/gd_intern/files/1708618/StakeholderMatrix_RDPRevised_7Feb2017.docx)

**Comment by connorshank** [comment]
I have created an initial mxd with both the 2016 alignment and the data from the 2018 folder (converted the kml file into shapefiles), located here:
N:\Projects\highspeedrail\HSR_impact_9Feb2018_map
