### ISSUE TITLE
New Analysis of Strategic Fallowing within California (San Joaquin Valley)  - March 23

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#144]
Hi Connor, 

We need re-analysis of the habitat suitability within entire SJ Valley instead of just the desert. 
I am assuming you went through the previous map packages and the final datasets that were uploaded in Nov 2017 to do the analysis within a larger study area. 

I will touch base with you on the steps.

Here is the old link on Github.
https://github.com/tnc-ca-geo/gd_intern/issues/82

Thanks
Tanu

**Comment by TB2016** [comment]
**Data sources to use**
Croplayer >> https://tnc.box.com/s/euoa0xkbqoofuxobeyu5oxebe8h02chr
Species layers >> https://tnc.box.com/s/p60roh85jeqonxcovlal6zenfghrnryk
CPAD and CCED  2018 or 2017 (latest available) 
Critical Habitat (latest available) https://tnc.box.com/s/js1ic19lpr9ohzhudt8qjfo2n5jo1lqr

STEPS
***ensure the rasters have same projection and resolution***
Create a overlap of all species habitat models
Classify the area into no of species in each pixel

Create overlap of CPAD, CCED, Critical Habitat 
Create 5 km buffer from the union
Convert the layer to grid same resolution as species overlap 

Convert crop layer to Irrigated Cropland raster (30m) by combining Annual and Perennial.

Once you have done all these we will move into the next step of the analysis
Thanks
Tanu

**Comment by TB2016** [comment]
@connorshank -- did you create a final map package for this project?
If yes, can you please update it to box here or email me the link 

I checked the mpk  you already uploaded  on box, it has all the analysis you did, as well. That is good for me. but to share with the team , I need a mpk with only data layers associated with the final maps. 

Can you  please send me a link when you have that ready?

thank you
tanu

**Comment by connorshank** [comment]
mxds:
N:\Projects\Agriculture\projects\Fallowing\Spring2018_Full_Analysis\mxds

pdfs:
N:\Projects\Agriculture\projects\Fallowing\Spring2018_Full_Analysis\plots\Final maps
