### ISSUE TITLE
Prep raster data (3/23)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#149]
Hi Connor - can you help me prep some data for an anaysis? 

I need rasters that are in the same projection and have the same extent and rows/columns
90m statewide (CA) rasters of:

- Counties
- Huc8 watersheds
- Ecoregions

Extent:
![image](https://user-images.githubusercontent.com/11560481/37608472-e1dd81c0-2b57-11e8-80bf-f2abc1378021.png)
Columns and Rows: 10272, 11918

You can use 
N:\Projects\Atlas\data\v2\tif90m\carb_abv_90m_ext.tif as a reference for projection/extent etc  and to snap to.

and 30m rasters of:

- Huc12 watersheds
- Counties

Extent: 
![image](https://user-images.githubusercontent.com/11560481/37608314-74258416-2b57-11e8-9cde-06c03f4aea06.png)
Columns and Rows: 39623, 38094

Projection:
![image](https://user-images.githubusercontent.com/11560481/37608543-14b5582a-2b58-11e8-8b55-f106838f92d6.png)
![image](https://user-images.githubusercontent.com/11560481/37608560-1f038996-2b58-11e8-9f29-df9ea0555a18.png)
You can use:
N:\Projects\Atlas\data\v2\preprocess\bird_rich2_ext.tif as a reference for projection/extent etc and to snap to.

**Comment by connorshank** [comment]
I have  converted the requested polygon shapefiles to raster .tif files according to the specified extent/projection settings.

They are named and stored as follows:
N:\Projects\Atlas\data\v2\tif90m\
ca_county_90m.tif
ca_huc8_90m.tif
ecoreg_90m.tif

N:\Projects\Atlas\data\v2\tif30m\
ca_county_30m.tif
ca_huc12_30m.tif
