### ISSUE TITLE
Digitize Legacy properties

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#15]
We have a spatial dataset that is an inventory of TNC land interests in California both past and present. This includes lands that TNC owns in fee, lands TNC holds a conservation easement, lands that TNC used to own and transferred, and lands TNC assisted other agencies to purchase.  Sometimes we are missing older transactions in this dataset, as is the case here.

When possible we use GIS parcel data to map property boundaries.  In other cases boundaries may be digitized from survey maps or other sources. Here you should be able to use current county parcel data.

Reference information:
Go to:  N:\TNC_GeoDesign\Core Data\Llano_Seco_Rancho
Here there are several files you can reference that document the transactional details.  These include an easement narrative, map, transaction table, etc.

Need:
Use current county parcel data and create a feature class of the conservation easement properties.
For each property/tract include, name (i.e. Parrott Ranch) and tract # (e.g. 65-C), date of purchase, date of transfer and to whom it was transferred.  Each property/tract (there are 6) should have a separate record.
1. Llano Seco Rancho (a.k.a. Parrott Ranch) CE Acquisition/Disposition (Megan Webb)
2. Desert Tortoise Preserve (Katie) -- below is a summation of what we discussed yesterday.  All documentation is in N:/TNC_GeoDesign/Core Data/desertTortoise_puzzle -- Tasks include:

a) please check the Levine Sierra Pacific deed and either map the property according to the township and range description, or if you find that the BLM acquisition data has it mapped then you can just borrow the shape (either way it's an easily digitized tract).

b) please do a brief review of the "27 deed-out" records in the Excel spreadsheet, and compare with the multi-part shape from the BLM data; no need to be overly precise.  We want to make sure we get this into our GIS records, but if it's not a perfect match it's okay, as long as it's a pretty good match.  Megan will indicate in the comments that the mapping may not be precise, depending on your findings.

3. Chuckwalla Bench - information provided by Brian Cohen

**Comment by ka78** [comment]
@cgrainger431, adding another:
5) Devil's Garden, as per our discussion last week.
