### ISSUE TITLE
Data Mgmt - CoreLogic ParcelPoint 1st quarter 2018 updates (4/6 flex)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#150]
Connor,

Please download the latest ParcelPoint 1st quarter 2018 updates for each CA county (the vintage could be 2017 or 2018).   I'll forward the email with details.

You'll need to add this the 4th quarter 2017 updates request I opened February 1.  No list was provided for this quarter, so you'll need to see what is available county by county and compare with our vintage and download if more recent.

Let me know if you have any questions.

Thanks,
Megan

**Comment by connorshank** [comment]
The following counties have been updated as of 3/23/2018:

Contra Costa
Colusa
Del Norte Humboldt
Los Angeles
Madera
Mariposa
Placer
San Francisco
San Joaquin
Santa Cruz
Shasta
Siskiyou
Solano
Tuolumne
Yuba
