### ISSUE TITLE
Ten Mile South Fork (Phase 1) Conservation Easement Maps (DRAFTS 3/30)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#151]
Hi Connor –
As we discussed last week, I could use your help to create these maps.  Unfortunately, it now sounds like I will not receive the final map details until the end of this week, but we can get started with what I expect will be needed and I can finish up the draft maps after 2/23 to meet the 3/30 deadline.

Currently, I believe 3 types of maps are needed:

Project Area
Infrastructure
Land Use

However, since the project area is so large (and due to the interest of funders), we’ve had to break up this area into 8 page-size maps for each map type (i.e. 3 x 8 = 24 maps) so that even the smallest features may be readable.  In addition, if we create these maps in color, they will need to be readable when printed in black and white (a legal reproduction requirement).

I’ve already set up a map layout and an index grid to use data driven pages, so this should be pretty straightforward.

Again, no pressure in finishing all of these, so let's just figure out what you have time for and plan on discussing some details either late Tuesday afternoon or Wednesday morning.

Thanks,
Megan

**Comment by megrwebb** [comment]
Map Template
N:\North_Coast\Projects\Ten_Mile\Mxds\tm_South_Fork_Phase_1_CE_Map_Layout.mxd

Includes map layout/extent, index layer, legend, title, map inset, etc. and initial styling/symbology for the ‘Infrastructure’ map.  Data driven pages are enabled.  Use this map template for all 3 map types.

Place new maps in same location.
For file name replace ‘May_Layout’ with ‘Project_Area’, ‘Infrastructure’ or ‘Land_Use’

Currently, there are 3 map types at 8 pages each. 

Project Area -show project area boundary, USGS topo
 
Infrastructure - like NCRM EDR "Manmade Features" map – show project area, stream classes, pond, roads, drafting sites, wells, rock sources, gates, buildings, expanded riparian buffer, PLSS first division lines

N:\North_Coast\Projects\Ten_Mile\Projects\HTC_Deal\tm_Final_Lyme_EDR_093017\ Appendix_F_manmade_map_08_14_17.pdf

Land Use - like NCRM EDR "Biological" map – show project area, stream classes, "Sensitive Forest Area" = old-growth islands = currently labeled Marbled Murrelet Habitat, NSO activity centers and core habitat, plant and animal occurrences (CNDDB and Lyme), expanded riparian buffers, PLSS first division lines, roads

N:\North_Coast\Projects\Ten_Mile\Projects\HTC_Deal\tm_Final_Lyme_EDR_093017\ Appendix_G_BIO_map_08_14_17.pdf

Annotation - Label and create annotation layers (within the maps) for streams and roads (if available)

Symbology – Use what I’ve already developed in the ‘Map_Layout’ mxd.  Let’s simplify symbology and categories for roads.  Maybe just ‘permanent’ and ‘other roads’.  We don’t want the roads layer to distract from other important features on the maps.

Data will primarily be in two places:

Ten Mile South Fork Phase 1 Conservation Easement N:\North_Coast\Projects\Ten_Mile\Projects\HTC_Deal\Ten_Mile_South_Fork_Phase_1_CE_FINAL.mdb

NCRM Easement Document Report
N:\North_Coast\Projects\Ten_Mile\Projects\HTC_Deal\tm_Final_Lyme_EDR_093017\TenMileEDR.gdb

Final Map Files:
Export as PDF and JPEG (grayscale) and 300dpi.  Let’s look at your image quality settings for each. Create subfolders by map type/name in plots folder

**Comment by connorshank** [comment]
I have copied the layout mxd to create three new map documents:
Land_Use
Infrastructure
Project Area

I think I have located and added all of the requested data, and modified the symbology and legend where necessary.   Unfortunately, I did not get a chance to create label annotations for the roads and streams.

**Comment by megrwebb** [comment]
Ok, thanks for you work on this.  When you get back from vacation, I'll let you know if there is more to do to finalize these maps.
