### ISSUE TITLE
Crescent Peak Wind Project (Nevada) map(s)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#152]
Our colleagues in NV need a map or maps of the Crescent Peak Wind Project. 

Here is a link to an article that has a map of the proposed project: https://www.reviewjournal.com/local/local-nevada/blm-to-review-massive-wind-farm-planned-near-searchlight/

The request from NV: "One thing that would be helpful: Could Brian or somebody from CA produce a high quality map of the project area that shows its location in relation to all the other protected areas?  We are short any GIS support right now."

I would start with a map that replicates the one from the article.

The NV point of contact is John Zablocki <jzablocki@TNC.ORG>

**Comment by connorshank** [comment]
N:\Nevada\Mxds\Crescent_Peak_WF
