### ISSUE TITLE
Map priority locations for new stream gages in California (4/5 tight)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#153]

**Comment by kklausmeyer** [comment]
Create an external facing 8.5 x 11 inch map of California that shows point locations for 8 priority groups for new locations of stream gages in California.  

Title: "Initial Priority Locations for New Stream Gages in California"
Legend (see if you can fit all of this in the legend-  it might be tough!):  
•	Priority 1: Inactive gages that are located in gage gap CVAs and are also either (a) downstream of an ungaged dam or (b) located on a reference stream. Total gages: 15 
•	Priority 2: Ungaged dams that are also located within a gage gap CVA. Total gages: 51
•	Priority 3: Inactive gages that are located downstream of an ungaged dam. Total gages: 11
•	Priority 4: All remaining ungaged dams. Total gages: 220
•	Priority 5: Inactive gages that are located in gage gap CVAs. Total gages: 99
•	Priority 6: Inactive gages that are located on reference streams. Total gages: 55
•	Priority 7: Reference streams that are located in gage gap CVAs. Total gages: 560
•	Priority 8: All remaining gage gap CVAs. Total gages: 333

Data:  Lists of the places are in tables in this folder, with a separate file for each priority list:  N:\Projects\GageGap\tables\Grantham_prioirities_20180330

The main work in making this map will be creating a new point feature class with an attribute that tracks the priority level (note that these could change over time).  Currently the data to generate the locations are in three places:

1. Inactive gages (for priorities 1, 3, 5 and 6):  N:\Projects\GageGap\gdbs\Gage_Priority.gdb\Gages join on field "STA"
2. Dams (for priorities 2 and 4): N:\Projects\GageGap\gdbs\Gage_Priority.gdb\Grantham_Dams_20180330 join on field "NID"
3. Streams (for priorities 7 and 8): N:\Projects\GageGap\gdbs\Gage_Priority.gdb\NHD5km_web join on field "COMID".

For the streams, I would join the tables for priorities 7 and 8 and then convert just those locations to points.  

The final point feature class should have the following fields:
"Priority_Group": with values 1-8 based on the list above.  Check the numbers to make sure we have all the points we need.
"Priority_Group2":  Cat would like to group priorities 1-6 into "Step 1" and 7 and 8 into "Step 2"
"STA"
"NID"
"COMID"
"Name"

Put the featureclass here:  N:\Projects\GageGap\gdbs\Gage_Priority.gdb

For the map, use a standard basemap.  I think we could add major rivers if you like, but not essential.  Make Priority 1 rivers the biggest most obvious points, down to small grey dots for Priority 8.  Group the priorities by Step 1 and Step 2 and have some common symbology between those two steps.  

Sorry for the tight timeline, but I'm hoping we can have a draft to review by Wednesday, April 4th.

**Comment by connorshank** [comment]
pdf maps:
N:\Projects\GageGap\plots

mxd:
N:\Projects\GageGap\mxds\Priority_New_Gage_Locations_2Mar2018v2
