### ISSUE TITLE
Data gathering for Path to 100 project (4/20)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#154]
Hi Connor

We've come to the point in the Path to 100 project where we need assistance in obtaining a large number of datasets. In the attached workbook there is a sheet named BC_list. This is the list of data that I need to obtain. The rows highlighted in light green are the rows for which I will get the data. The rest of the rows is where I could use your help. Column D provides the link to the data (or at least a starting point).

Once you download the data (or as you go along, whatever is easiest for you), please make a ArcMap .mxd that contains the data, organized into groups as specified in column E (1, 2, 3, or 4).

Our goal is to have these datasets downloaded and the .mxd created by April 20th.

[trackingSpreadsheet.xlsx](https://github.com/tnc-ca-geo/gd_intern/files/1873292/trackingSpreadsheet.xlsx)

**Comment by connorshank** [comment]
N:\Projects\Energy\Path_to100
