### ISSUE TITLE
compile birdreturns data for Upstream (4/11, flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#155]
@connorshank, as part of the Upstream project, we share with them our in situ compliance observations (called "site compliance visits" in Salesforce). Many of those observations have associated photos taken or map sketches made by the field techs.  These images live in Salesforce as part of the "site compliance visit" records, and the only way to harvest them is manually. I've provided Upstream with the spreadshet below listing all the "site compliance visits" for Spring 2018. I'd also like to give them the photos/maps associated with the observations. I'd like you to help me download all these images from Salesforce. For every record in the spreadsheet that refers to a Photo or Map in the Notes column, go to that site compliance visit (SCV) and download the image, name it with the SCVID, along with _Photo1 or _Map2, or however the field tech refers to the attachment in the notes.

Spreadsheet: N:\WATER_Program\projects\birdreturns\2018_Spring\compliance\site_compliance_visits\Spring2018_siteComplianceVisit_fieldTechSummaries.csv
You can save all images here: N:\WATER_Program\projects\birdreturns\2018_Spring\compliance\site_compliance_visits

Here is an example of how I named the images last year:
![image](https://user-images.githubusercontent.com/11932002/38394919-4952afb6-38e5-11e8-9bf6-89912421d0bf.png)

**Comment by connorshank** [comment]
Images (38 total) have been downloaded from Salesforce and placed in: 
N:\WATER_Program\projects\birdreturns\2018_Spring\compliance\site_compliance_visits

**Comment by ka78** [comment]
perfect, thanks @connorshank!
