### ISSUE TITLE
Data conversion and KML creation - Puma road kill data (yuck) (5/25)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#156]
Group the data by year and convert to KML

[1998toDec2017_Roadkill_032218.zip](https://github.com/tnc-ca-geo/gd_intern/files/1961424/1998toDec2017_Roadkill_032218.zip)

**Comment by connorshank** [comment]
Two kml files have been prepared, I reccomend using the 'clamped' version, as the points are visible at all scales and angles.

N:\Projects\Puma_RK\shapes
