### ISSUE TITLE
Monitoring our property from space (Remote Property Monitoring)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#16]
Hi Cori-

We are doing a pilot project to see if we can use aerial photography and satellite data to monitor TNC property.  In order to make this work well, we will need high resolution aerial imagery for all our properties for each year, and this could get expensive.  Luckily, Google Earth imagery is free and will fit the bill.  I would like your help to create an inventory of all of TNC Fee and Easement (don't worry about historic or assist or any other category) lands and determine what is the date of the most recent imagery in Google Earth.  Some properties will be covered by multiple images and so it may be 40% in 2016 and 60% in 2012.  In the end, I would like a table that has the property name, property ID, imagery date, and percent cover (you can do a visual estimate- it does not have to be exact).  I would also like a chart that shows the acres of our properties by imagery year.  And finally, I would like a simple map that shows the the properties as dots, colored by the image year (and for extra credit, the size of the dot can represent the area of the property!).  Please make the chart and map suitable for a powerpoint presentation.  

Thank you!

**Comment by kklausmeyer** [comment]
Great work on this task Cori-  I have attached the draft map and table you sent to me.  I have two questions for you:
1. What does the "percent cover" in the table reference?  
2. Can you redo the map with a color ramp for the dots?  I want to oldest to be the least saturated, and the 2016 to be the most saturated.  You could use a yellow to green or yellow to purple ramp to help differentiate the colors.
[Google_Earth_Imagery_Year.pdf](https://github.com/tnc-ca-geo/gd_intern/files/507226/Google_Earth_Imagery_Year.pdf)
[GoogleImageryInfo.xlsx](https://github.com/tnc-ca-geo/gd_intern/files/507225/GoogleImageryInfo.xlsx)

**Comment by cgrainger431** [comment]
Hi Kirk,

Is this more what you were thinking with the color ramp? 
[Google_Earth_Imagery_Year_update.pdf](https://github.com/tnc-ca-geo/gd_intern/files/509132/Google_Earth_Imagery_Year_update.pdf)

As for "percent cover," it is the tree cover.  But looking at this again, you probably meant percent cover of each imagery year... Only two properties had split imagery dates (same year, just different month) and they were split pretty much down the middle.

**Comment by kklausmeyer** [comment]
This is very close, but I want to 2016 dots to jump off the map and be the brightest.  In this version, the darkest green is very subdued and tends to get lost in the base map.  Perhaps a yellow to purple ramp would work well in this case.  Something to really make 2015 and 2016 stand out.

**Comment by cgrainger431** [comment]
Hi Kirk,

Here it is with a yellow to purple ramp, I hope it is popping out enough. There are so many 2015 and 2016 points that I was having a hard time stretching the color ramp enough that the color difference between 2015 and 2016 was distinct but still had them be the brightest.

Sorry there have been so many versions, hopefully this one works!

[Google_Earth_Imagery_Year_update1.pdf](https://github.com/tnc-ca-geo/gd_intern/files/514917/Google_Earth_Imagery_Year_update1.pdf)

**Comment by kklausmeyer** [comment]
Looks great!  Thanks for you help.  This one is done!
