### ISSUE TITLE
Dangermond Preserve Coastal/Marine Map (Draft 5/16, Final 5/18)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#160]
@connorshank  I wanted to get this in your queue sooner rather than later.

The Oceans team is having a retreat at the Dangermond Preserve May 21-23 and would like to get a couple of good field maps showing coastal/marine features and resources for the group to have on site.
This Wednesday, I’ll be reviewing this request with Matt and the sourcing of some datasets.  When I know more, I’ll update this request.

Thanks!
Megan

**Comment by bcohen27** [comment]
I have passed along the ESI data to Connor that Matt via Mary has requested for a map of shoreline types. They also want summary statistics of the shore line types (Landward, Shoreward 1 and Shoreward 2).

**Comment by megrwebb** [comment]
Thanks Brian.

Connor, let's make N:\OCEANS_Program the primary workspace for this request.

**Comment by megrwebb** [comment]
Hi Connor -

Please put the data you've received from Brian (ESI shoreline types, marine mammals, seabird colonies and coastal confluences) in the N:\OCEANS_Program folder and then add these to the map.

I've started an mxd (in the same location) with the map size, layout and scale I think will be appropriate.  I've also added some additional data that should be included on the map.  I've started symbolizing some of this, but it will need a lot of finessing if we are to show all of this data.   Note, some of the features will be a combination of several sources e.g. marine mammals from Brian and WRA, so you will need to use your best judgement on what to include or not.

We'll want to label all the features on the map in addition to Jalama Creek, Jalama Rd, Union Pacific Railroad.  I'd like to not have a legend if possible.

Let's discuss tomorrow if you have questions or need more clarification.  We should get a draft of this completed by next Wednesday in time for a review by the Oceans team and so can have a final ready by Friday.

Thanks Connor!

**Comment by megrwebb** [comment]
Hi Connor -

Please put the data you've received from Brian (ESI shoreline types, marine mammals, seabird colonies and coastal confluences) in the N:\OCEANS_Program folder and then add these to the map.

I've started an mxd (in the same location) with the map size, layout and scale I think will be appropriate.  I've also added some additional data that should be included on the map.  I've started symbolizing some of this, but the map will need a lot of finessing to show all of this data.   Note, some of the features will be a combination of several sources (e.g. marine mammals from Brian and WRA), so you'll need to decide how to best show these.

We'll want to label all the layer features on the map in addition to Jalama Creek, Jalama Rd, Union Pacific Railroad.  I'd like to not have a legend if possible.

Let's discuss tomorrow if you have questions or need more clarification.  We should get a draft of this completed by next Wednesday in time for Mary Gleason to review and so can have a final ready by Friday.

Thanks Connor!

**Comment by megrwebb** [comment]
Hi Connor -

Let's chat about this request when you have all the data in the mxd.  Thanks!

Megan

**Comment by megrwebb** [comment]
Connor -
Here is some additional data:
Streams (symbolize, no labels) - N:\Central_Coast\Projects\Sba\Sites\BRSB_Confidential\Gdbs\WRA_CJR_Viewer_20170918\CJR_Aquatic.gdb\CJR_Aquatic\AandM_Delineation_JDLine_20130219

Jalama Rd (label only) - N:\Central_Coast\Projects\Sba\Sites\BRSB_Confidential\Gdbs\WRA_CJR_Viewer_20170918\CJR_BaseData.gdb\CJR_BaseData\Base_Data_External_Roads

Union Pacific Railroad (label only) - N:\California\data\infrastructure\transportation.gdb\CA_RAILROADS_CALTRANS_Rail_13

And ask BC about the coastal confluence data.

Thanks!
Megan
