### ISSUE TITLE
Data Mgmt - help compiling and formatting bird survey data for research grant (5/15 flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#161]
We have a contract with Cornell to incorporate our bird survey data from 9 birdreturns seasons into their STEM Abundance modeling. We have provided them with the observation data, and now need to give them the spatial data to go along with the observations (so Cornell will know where each observation was taken).
I've wrapped up and shared the survey zones. And now I'd like your help organizing and formatting the survey points. This involves formatting the unique ID field, removing sensitive fields, ensuring data in correct projection, etc. 
I will send an email with the details.

Primary workspace is N:\WATER_Program\projects\birdreturns\bird_survey_data\FINAL_FORMATTED_DATA

**Comment by connorshank** [comment]
Ultimately, what I'd like is for you to mimic what I've done for the zone data, but with the point data. See this directory:  N:\WATER_Program\projects\birdreturns\bird_survey_data\FINAL_FORMATTED_DATA\br_final_zones_ALL
 
At the root, you'll find a copy of whatever the final raw, QC'd, projected, formatted with tdat and tdat_sid fields.
 
And in the "_short" folder is the same shapefile as above, but exported without any sensitive or meaningless/confusing attribute fields.
 
This mxd contains the final zone and point data for each birdreturns season (the zones are there for your reference, as well as the fields symbolized for that season): N:\WATER_Program\projects\birdreturns\bird_survey_data\FINAL_FORMATTED_DATA\ data4cornell.mxd
 
1.	look over the point data, do a general scan that there are treatment points on treatment zones and control points on control zones
2.	check for the existence of a "Survey_ID" field; if it's not named exactly this, please create one. values should be M001, M002 or C001, C002 numbering system for the survey points, both treatment and controls.
3.	add a field "tdat" (text, 5)
4.	calc tdat as "t1", "t2", "t3", etc… pls double check that this is correct, super important
5.	add field "tdat_sid" (text, 10)
6.	calc "tdat_sid" = [tdat]&"."&[Survey_ID]
7.	save the file to this location: N:\WATER_Program\projects\birdreturns\bird_survey_data\FINAL_FORMATTED_DATA\br_final_points_ALL, make sure as you save the data are reprojected as UTM NAD83 Zone10 and named using convention here (the data frame is the UTM projection so you can reproject as you export)
8.	then hide any fields with sensitive info, e.g. anything with an owner name, or really anything with extraneous info, check the zones_short shapefiles for examples
9.	save the shapefile into the "…._short" folder, follow the naming convention I used for the short zones
 
In the end, we want the raw data untouched and unmoved, we want a copy of the raw data with the Survey_ID, tdat, and tdat_sid fields protected to UTM and saved to FINAL_FORMATTED_DATA\br_final_points_ALL and we want a copy with minimal fields for sharing saved here: FINAL_FORMATTED_DATA\br_final_srvpoints_ALL\br_srvpoints_all_short

**Comment by ka78** [comment]
Thank you @connorshank, this was a HUGE help!
