### ISSUE TITLE
Write python script to download PRISM data and convert to ascii

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#162]

**Comment by kklausmeyer** [comment]
Hi Connor-  We are working with a team of data scientists at AT&T to update our unimpaired flows data every month.  One of the big components of this project is to download the latest monthly PRISM climate data as it becomes available, along with the previous 5 years of data.  PRISM allows bulk downloads of data if you take the .BIL format, but AT&T folks need it in ASCII format.  Unfortunately, they do not have arcGIS which is required to make this conversion.  That is where you come in!  

This file describes how to download the .BIL format data, one month at a time:  http://prism.oregonstate.edu/documents/PRISM_downloads_web_service.pdf.  I believe we want the "DATA WEB SERVICE USAGE
Daily, Monthly, Annual Data Request Syntax" section.  This is an option, but I think the FTP option is better- see below.

An alternative method that might actually be easier is to access the data from the FTP site.  We want ppt and tmean monthly data:

ftp://prism.nacse.org/monthly/tmean/
ftp://prism.nacse.org/monthly/ppt/

Here is a tutorial on how to use FTP data in python:  http://www.pythonforbeginners.com/code-snippets-source-code/how-to-use-ftp-in-python
Here is a description of the FTP PRISM climate data structure:  http://prism.oregonstate.edu/documents/PRISM_downloads_FTP.pdf

We will want the current month, as well as the 59 months proceeding the current month, for a total of 5 full years of data.

Once you download the data, you need to convert from .bil format to .asc format.  This tool should allow you to do that:
http://pro.arcgis.com/en/pro-app/tool-reference/data-management/copy-raster.htm

For an output, I would love to see a python script that automatically downloads the files and converts them to .asc format.

There isn't much time pressure on this one.  If you can get a draft to me in 1 month, that would be great.

Thanks!

Kirk

**Comment by TB2016** [comment]
Kirk -  is there any particular reason you want Connor  to create this
dataset from the FTP site..
this can be very easily done on GEE platform.

Here is a script for extracting PRISM data for entire California by months
since 1988
you need to just convert the date information to YY-MM-DD format..

https://code.earthengine.google.com/7736de758e01dd23e3119d8b46a520ff


Enjoy
T

**Comment by connorshank** [comment]
Final grids have been successfully downloaded and converted, the .asc grids can be found here:
N:\Projects\CA_FWA\projects\UnimparedFlows\grids\prism

original .bil grids are located here:
N:\Projects\CA_FWA\projects\UnimparedFlows\archive\prism

Scripts have been saved here (2 formats, one for years 1985-1980, and one for data format post-1981):
N:\Projects\CA_FWA\projects\UnimparedFlows\scripts

2017 data is not yet complete, but I can adjust the script to access those months that are.

**Comment by kklausmeyer** [comment]
Thank you Connor-  I will review shortly!

**Comment by kklausmeyer** [comment]
The script is working well and I send off the files to our partner for testing.

I would like to see the script updated to download any provisional data as well. 

The simple way to do this is to write a list of all the year and month combos that are provisional, and have the script check to see if the year and month combo is in that list, and then if so, change the "stable" to "provisional" in the file name.

The more complicated way is to get a list of all the file names in the directory and just download them all, regardless if they are provisional or stable.  Here is the example code:  https://stackoverflow.com/questions/111954/using-pythons-ftplib-to-get-a-directory-listing-portably

**Comment by connorshank** [comment]
Update as of 7/5/2018:

So I have solved the problem of finding whether a data file is proversional versus stable using a 'try except' statement and the urllib.urlretrieve functions.   Have a look at the code (prism_dwnld_script.py) in
N:\Projects\CA_FWA\projects\UnimparedFlows\scripts , it looks like a turducken of loops, but it does the job.    The only problem I can forsee in the future is if it encounters a provisional data set that has already been downloaded (i.e. if it is executed 5 months from now and June has not been updated to 'stable', but I think this can be overcome by having overwrite enabled.
