### ISSUE TITLE
SinghBidwell Data

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#163]
Connor --  I am looking for the dataset associated with this pdf. Can you see if its on SAC server?
THanks
Tanu

[SinghRestorationCommunities_edit_20170622.pdf](https://github.com/tnc-ca-geo/gd_intern/files/2018186/SinghRestorationCommunities_edit_20170622.pdf)

**Comment by connorshank** [comment]
Tanu, 
I have uploaded what appears to be the most similar (and recent) shapefile to Box.   Some of the zones look a little narrower than in the pdf you sent, but the location I found it at appears to be the only place with similar shapefiles.
N:\Sac_Server\Seths_drive\Geodatabases\Sacramento_River_Projects.gdb

**Comment by TB2016** [comment]
this is actually a old file.. Cori modified it.
Thanks for sending it though
Tanu
