### ISSUE TITLE
another SDAC map (5/29 flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#165]
Connor, the Colusa Groundwater Authority Board is encouraging us to work on the west side of the valley. We are constrained by our recent grant to work within the SDAC you've been mapping, but Julia would like to see a map of the 3 Sagbi good categories within the Colusa Groundwater Authority, to help with conversations about other/future recharge work. You can keep the simple (totally internal and low key), this is just a starting point so she can see **how much** Sagbi and **where** is present in the CGA.
We should have CGA data, but these links might help.
https://sgma.water.ca.gov/portal/gsa/all
https://gis.water.ca.gov/app/boundaries/
Julia can answer questions about CGA if needed.

Thanks!

**Comment by connorshank** [comment]
pdf location: 
N:\WATER_Program\projects\disadvCommunities_DAC\plots\Colusa_sagbi_map

mxd location:
N:\WATER_Program\projects\disadvCommunities_DAC\mxds\Colusa_sagbi_map
