### ISSUE TITLE
compile coastal/marine gdb for Dangermond Preserve

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#167]
hey @connorshank - the Dangermond Preserve core team has identified a data need, that to create a coastal and marine gdb for A) use in the Dangermond Preserve Management Plan and B) to publish to AGO so the layers can be added to the master web map for the Preserve. 

Here is a link to the master data inventory for the DP: https://tnc.box.com/s/wg9hdunthtf75o9zc06m47lkemu0etyy. Page 1 "datasets in hand" is where you want to go; see the "theme" column. "Coastal and Marine" is the focus of this gdb. I think we have all these data in-house but we need to find each feature class and load it into a single gdb.

Here is a blank gdb for this purpose: N:\Central_Coast\Projects\Sba\Sites\BRSB_Confidential\Gdbs\DP_coastal_and_marine.gdb

Let's talk on Tuesday when my voice is back! We'll cover things like:
1. what do to if data cover wide are, clip? to what extent
2. metadata
3. best sources if you don't know where the data are
4. some info you'll need to get from Brian

**Comment by mmerrifield** [comment]
hi @connorshank - thanks for the great progress on building out coastal and marine geodata. I've looked through it and have some very specific feedback below. Reach out if you have questions. In general all the data will need to be clipped, I've made notes on stuff that's duplicative or should be updated with newer stuff (with sources), and once everything is in place if you adhere to the nomenclature [found here ](https://tnc.box.com/s/ba1mtvklwbr4wzpwqhbngeobuo8tllg1) that would be much appreciated!

BIO_CA_Mammal_Pinneped_Haulouts_MLPAcompilation - please check if this was Brian's source or if he had more than this
BIO_CA_Seabird_colonies - same as pinnipeds
Built_environment - not neccessary but doesn't hurt - go ahead and clip and make sure to document source in metadata
CA_COAST_VULNERABILITY - good as is
ccm_bathy_10m_to_600m - good, keep this one and clip
ccm_bathy_50fa - you can delete this
ccm_bathy200m - you can delete this, we don't need a raster, the Esri basemap is sufficient to view this
ccm_canyonheads, ccm_canyons - these are at a scale that isn't very useful to DP go ahead and delete
ccm_canyons_channels - this looks like the best representation, keep this and clip
ccm_estuaries - this is dated, more complete up-to-date source is at california_current\gdbs\PMEP_West_Coast...gdb
ccm_pfmc_efh_notrawl - you can delete, these are in the marine_managed_areas feature class
ccm_pinniped_PU - looks like Wildlife_Marine_Mammals is a better layer, go ahead and delete this one
ccm_rocks - good, just clip
ccm_sponges_nmfs - delete, the deep_sea_corals_NOAA_121717 has these embedded, see notes on that layer
ccm_statewaters_noaa - good just clip
Coastal_CNDDB_sept2016 - good, but please look at latest CNDDB (Megan has details on where this lives) to ensure no changes to now
dp_coastal_marine_clip_bnd - clip boundary to limit geometery for all these data
Dangermond_ESI_s - good
deep_sea_corals_NOAA_121717 - good, just rename to include sponges in name - e.g. deep_sea_corals_sponges
HAB_SCSR_PredictedSubstrateWDepth - good, for simplicity please dissolve on 'substrate' attribute, also please add ~/shapes/Habitat_Offshore_PointConception to gdb
marine_managed_areas - I pulled this from Protected Seas and its comprehensive and clipped - all good
MPA_CA_Existing - delete, sufficiently covered in marine_managed_areas
National_HAPC - good, just clip
ncc_emu200m, scc_emu200m - ok there's a few different sources for this, these are ones we made and Esri has made some as well but those are at a global scale and unclear how useful that will be. For now please use the polygon versions of these in california_current/gdbs/ncc_ERA_v2.gdb/to_benthic_habitat_tnc04 and california_current/gdbs/scc_ERA_v2.gdb/tgt_benthic_habitat you'll need to merge these two datasets then clip them. The TYPE attribute is mostly the same but unfortunately scc is UCASE, don't worry about that for now
seamounts_banks - all good, just clip
TargetLandcover - all good, just clip
WestCoastCanopyFormingKelp - all good just clip
Wildlife_Marine_Mammals - good just clip and add any source metadata (assuming this is from Brian? or maybe WRA?)
Wildlife_Tidewater_Goby - good, assuming this is from WRA?

**Comment by ka78** [comment]
- everything has metadata
- worked with MM and Brian on data and extents
- data is clipped
