### ISSUE TITLE
Clean river flow data (6/20/18 flex)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#168]

**Comment by kklausmeyer** [comment]
Hi Connor-

We recently got access to a cool dataset that has some promise, but it needs some cleaning.  You can visualize the data here:  https://disappearingwest.org/rivers/map/index.html.  Select the "Flow Restriction" data in the legend too see what we are interested.  These data show places where flow is altered by dams, but many of the smaller stream segments are getting an "altered" score even though there is no dam upstream.  I think this is because they used a raster to do their flow accumulation, and the raster data did not align well with the smaller stream segments.  The task is to clean up the data so it is more accurate.  I will show you how to do the cleaning in our meeting.  The .mxd is here "N:\Projects\CA_FWA\mxds\DisappearingRiversCleaning_Connor.mxd"

**Comment by kklausmeyer** [comment]
Hi Connor--  you can charge the time to P100712

**Comment by connorshank** [comment]
All data has been successfully checked and cleaned.   I have erred on the side of caution with many of the San Juaquin Valley and Delta area rivers, due to the heavily modified nature of those channels and tributaries, I am quite confident that the data for the rest of the state is now accurate.

**Comment by kklausmeyer** [comment]
Looks great Connor!  I will do the overlay with the blueprint data and let you know if there are any major issues.
