### ISSUE TITLE
Summarize parcel level data with GSA for Tule and Kern Subbasin

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#169]
Hi Connor, 

Here is the task for summarizing GSA for parcels within Tule and Kern Sub. 

Abby wants to identify how many parcels there are of less than 500, between 500-1000, and over 1000 acres within Tule and Kern sub basin. She want's each parcel to be classified by GSA, sub-basin, and county, then summarize the numbers at those levels as an excel sheet or map. Excel sheet might be better since a map will be very busy! 

I was able to grab the parcels for Kern sub-basin, and summarize the parcels by area into following classes after dissolving the parcels by owners. Can you do the same for Tulare sub basin. I have uploaded the sub-basin and an mpk on box

![image](https://user-images.githubusercontent.com/17483557/41175389-c49b3554-6b11-11e8-8640-068665c49533.png)

Box link to dataset https://tnc.box.com/s/epfwtgtt7l85xso6mlce12p6758wz8vc

Kern sub basin has about 159541 parcel records. Tule sub-basin might have 200,000 more. I did not do a spatial join between GSA to the parcel data. I am not sure if she wants all the parcels or only the parcels above certain size thresholds.  Find that from her once you have summarized the Tule sub-basin parcels then join GSA to both kern and tule sub-basin and send her a shapefile and excel file. 

If she has area threshold for parcel it will help to speed up the process. Check with her on that. 
Thanks much for you help on this

Tanu

**Comment by connorshank** [comment]
N:\Projects\Agriculture\projects\GSA_Tule_Kern

**Comment by TB2016** [comment]
@connorshank -- connor - will you please update the data on box?
Thanks
tanu

**Comment by connorshank** [comment]
Tanu,
               I just uploaded the map package to Box in the following folder:
All Files->Agriculture->GSA and Parcels Pilot study
https://tnc.app.box.com/folder/50140659744

Sincerely,
Connor Shank
