### ISSUE TITLE
Interactive GSA GDE webmap (6/15)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#170]

**Comment by kklausmeyer** [comment]
Hi Connor-  

The groundwater team would like an interactive map that shows GSA boundaries, Groundwater Basin boundaries, and the iGDE data.  I think an ArcGIS online webmap would be appropriate for this task.  

I have already started a version of the map for internal needs, but I would like an external facing version.  Here is a draft you can start from:  http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=32d40fc3b9ea498fbad785df239e3adc

You can keep the "Indicators of Groundwater Dependent Ecosystem" layers-  I have a scale dependency set up so you get a tiled version while zoomed out, and a vector version when zoomed in.

You can also keep the Groundwater Basins 2016 layer in the map

**Comment by kklausmeyer** [comment]
Actually, I think I was able to do it all the map content myself.  Could you just work on finding a nice app that allows the user to search the data, but it looks clean?

**Comment by kklausmeyer** [comment]
Here is the URL for the webmap:  http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=074b0e3828af4c6cba4747dcb7f274ce

**Comment by ka78** [comment]
hey @connorshank you can use the Web App Builder in AGO to wrap up @kklausmeyer 's web map inside an application. Search functionality happens by adding the Search widget to the application, then you configure which layers and attributes you want to search on. For look and feel, there are a few layouts to choose from and you can brand with color, logo and links out, etc... lmk if you have questions.

**Comment by connorshank** [comment]
Kirk, here's a rough draft web app, let me know how the formatting looks, if there are other widgets that should be added.   
http://tnc.maps.arcgis.com/home/item.html?id=8ff28ef1fa6842b3a31e344e7fb9aa6c

**Comment by ka78** [comment]
good start @connorshank - imo, a few things could be improved here:
1. brand it, banner color and tnc logo if @kklausmeyer says a logo is important but that default logo needs to go
2. the functionality is all spread out in 3 corners, can you bundle it up a little bit? you can see how I did it in the birdreturns app (it's just one idea, and an illustration of what I mean)
3. do you really want to keep the Esri World Geocoder in your Search widget? Maybe you do, but the default "Find address or place" doesn't help the user understand what they might be able to search for... this might be purposeful, maybe you want them searching for their city... but I see they can search of many things you could add the hint "Search GSA, basins or place", or something like that
3. I'd make default extent one click out, to capture more  (almost all) of CA
4. check that the pop-up titles and content show what you want them to show
5. redundant to have a search icon when you have a search box
6. could use info button to give user some guidance on what they can do in this app if that's something @kklausmeyer would like
7. is there a website or page link you can add? notice in the birdreturns app we link to birdreturns.org in upper right corner.

www.tinyurl.com/birdreturns

In general, when making an app, imagine yourself as the end user and see if every aspect of the app makes sense from their point of view.

**Comment by connorshank** [comment]
Made some adjustments, numbers 4, 5, 7, and 8 are outside my control though (Kirk, I don't think I have editing access to the webmap) .   The info tab could definitely use some fleshing out, but I imagine that's better left to the Grounwater team, I don't want to make any assumptions as to how this information should be framed.

**Comment by kklausmeyer** [comment]
This is all great feedback- thank you Katie!  I agree with all those points. The end user will mostly be other non-profits, consultants, and potentially local governments. I agree that an info window is very important. Let's start with this text:

"This interactive web map shows the amount and location of vegetation and wetland indicators of groundwater dependent ecosystems (iGDE) within each Groundwater Sustainability Agency (GSA) area. To learn more about iGDEs click here: https://groundwaterresourcehub.org/gde-tools/mapping-indicators-of-gdes/.  To learn more about the Sustainable Groundwater Management Act (SGMA) and GSAs click here: https://www.water.ca.gov/Programs/Groundwater-Management/SGMA-Groundwater-Management. "

On Jun 21, 2018, at 10:00 AM, ka78 <notifications@github.com<mailto:notifications@github.com>> wrote:


good start @connorshank<https://github.com/connorshank> - imo, a few things could be improved here:

  1.  brand it, banner color and tnc logo if @kklausmeyer<https://github.com/kklausmeyer> says a logo is important but that default logo needs to go
  2.  the functionality is all spread out in 3 corners, can you bundle it up a little bit? you can see how I did it in the birdreturns app (it's just one idea, and an illustration of what I mean)
  3.  do you really want to keep the Esri World Geocoder in your Search widget? Maybe you do, but the default "Find address or place" doesn't help the user understand what they might be able to search for... this might be purposeful, maybe you want them searching for their city... but I see they can search of many things you could add the hint "Search GSA, basins or place", or something like that
  4.  I'd make default extent one click out, to capture more (almost all) of CA
  5.  check that the pop-up titles and content show what you want them to show
  6.  redundant to have a search icon when you have a search box
  7.  could use info button to give user some guidance on what they can do in this app if that's something @kklausmeyer<https://github.com/kklausmeyer> would like
  8.  is there a website or page link you can add? notice in the birdreturns app we link to birdreturns.org<http://birdreturns.org> in upper right corner.

www.tinyurl.com/birdreturns<http://www.tinyurl.com/birdreturns>

In general, when making an app, imagine yourself as the end user and see if every aspect of the app makes sense from their point of view.

-

**Comment by kklausmeyer** [comment]
For items to modify the web map, I can make those changes. I’m not totally sure what the best workflow is here. It would be great if we can both make edits to the same web map. @ka78, do you know if I can grant editing access of a web map to Connor?

**Comment by kklausmeyer** [comment]
BTW, thanks for the quick turn around on this!  Awesome to have your help!!

**Comment by ka78** [comment]
looking better @connorshank! I think the Search can still use more help. @kklausmeyer do you want users searching on the World GeoCoder, or only on your operational layers? @connorshank once you hear back from @kklausmeyer you can adjust the layers (or not) but I'd DEF edit the default Search Box text that currently says "Find address or Place", the user is going to think they can search only on address or place... but if we want to encourage them to search on GSA or whatever we have to prompt them by changing that default prompt.

**Comment by ka78** [comment]
@kklausmeyer I believe you have to change owner to do this. There is another way but WO says there are negative ramifications so I just steer away from it. I don't have the power to make Connor the owner of the map, but you could write a request to sditeam@tnc.org... they are short-staffed so might take a day or two to grant your request.

OR, Connor could just Save As and own a new version of the web map, and then edit the App to use his version of the map rather than yours ...

**Comment by kklausmeyer** [comment]
Hi All-

Connor and I decided that we would pass ownership of the webmap back and forth as we do the edits.  I took care of editing the popup boxes the way I want them.  I added a version number to the webmap name so we can keep track.  Right now this is version 1.0.  Connor, please save it as version 1.1.  I will not make any more edits until you let me know you are done editing it.  here is the URL:  http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=074b0e3828af4c6cba4747dcb7f274ce.

I made Katie's suggested edits.  

I would like the following edits made to the web app:

1. For the search, I only want users to be able to search the Groundwater Sustainability Agency layer and the Groundwater Basin layer.  You can remove the rest of the search options.  I agree that it would be good to change the default search text.  Can you do that at the web app level?
2. Can you make the legend visible by default?
3. Can you change the title to "Groundwater Dependent Ecosystems (GDEs) and Groundwater Sustainability Agencies (GSAs)"

**Comment by ka78** [comment]
Glad you found a way to make it work!
1. Yes, in the Search Widget you can specify what you want the hint to be... I'd have to open it to figure out how, but it's there within the Widget settings.
2. Legend, hmm I can't remember. I can look later. There are many types of layouts to choose from, I'd bet that if you can't set the Legend to be open, that one of the themes shows the legend by default... you'll have to play around with it.
3. Have you thought about giving it a name that describes what kind of resource it is? Something like:
- Groundwater Dependent Ecosystem (GDE) Viewer
- Groundwater Dependent Ecosystem (GDE) Explorer
- Groundwater Conservation Viewer
- Groundwater Sustainability Viewer (or Explorer)
- Etc...

**Comment by kklausmeyer** [comment]
I like this title better-  thanks @ka78 
"Groundwater Dependent Ecosystem (GDE) Explorer"

**Comment by connorshank** [comment]
Here is the latest version of the webapp.   I'm not especially happy with the color scheme, but the dashboard theme, which has the best options for displaying the legend upon opening, has limited available color schemes.    

http://tnc.maps.arcgis.com/apps/webappviewer/index.html?id=8ff28ef1fa6842b3a31e344e7fb9aa6c

**Comment by kklausmeyer** [comment]
hi Connor-  Can you make the web application public?  When I test with an incognito window it asks me to sign in.  Thanks!

**Comment by connorshank** [comment]
Yes, it is now shared with public and TNC

**Comment by kklausmeyer** [comment]
This is great Connor!  Thank you!  I think we can roll with this.  I may have some follow up questions but I think we can close this issue for now.
