### ISSUE TITLE
Sac Valley Water Trust Report Map (Draft on Friday 6/29)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#171]

**Comment by kklausmeyer** [comment]
Hi Connor-

I would like your help to make a map for a report for Jeanne Brantigan.  Here is the email chain with the request:

Thanks Kirk! Here are some answers to your questions:
-	Printed map (ideally to be inserted in Word as a jpg) on 8.5x11. For most flexibility, we’d like no title on the map; we would need space for a figure title/short caption when inserted on an 8.5x11– probably allow 2 lines. Eventually we’d want to put it in a powerpoint, but maybe that would be formatted differently…my priority now is for this report.
-	Extent – probably statewide because we need to extend south to San Diego, but it doesn’t have to extend north of Redding.
-	Main point of map: Ideally we want people to get a sense of where the water sources are we may acquire, where the water buyers are, where the ecological needs are. Secondarily, we’d like to communicate how the water would flow from the sources to the buyers and ecological needs (showing location of Delta pumping facilities and major conveyances).

Content:
-	Basic landmarks: Redding, Sacramento, San Francisco, Fresno, Bakersfield, Los Angeles, San Diego
-	Basic hydrographic (major rivers and tributaries, no need to label except for Sacramento R, Feather R, American R, Mokelumne R, and San Joaquin R)
-	Harvey O. Banks and C.W. “Bill” Jones pumping plants (CVP and SWP water pumps in the Delta)
-	California Aqueduct
-	Focal ecological water targets
o	CVPIA refuges (no need to label each, just show as distinct color), only show those south of the Bay-Delta
o	Potential agricultural shorebird habitat (or show current extent of rice, corn, other suitable crops in the Sacramento Valley only) – if you don’t know of another map that has already been created to show this (probably for Mark Reynolds or Greg Golet ?), I will look for one…
-	Potential water buyers (doesn’t have to be perfect at all, just general outline is ok – these are large areas and we’re just interested in showing the vicinity, although want to identify them separately on the map), I don’t have shapefiles…
o	San Luis and Delta Mendota Water Authority (http://www.sldmwa.org/OHTDocs/Maps/SLDMWA%20Member%20Agencies%20Map2.jpg) 
o	Kern County Water Agency (http://www.wakc.com/wp-content/uploads/2016/01/SWP-Water-Districts-in-Kern-County.pdf) 
o	Metropolitan Water District (http://www.mwdh2o.com/Who%20We%20Are%20%20Fact%20Sheets/Member%20Agency%20Map.pdf or shown in yellow for regional perspective http://www.mwdh2o.com/Who%20We%20Are%20%20Fact%20Sheets/6.4.2_Maps_Major_Water_Conveyance.pdf )
-	Potential water sources – Not sure exactly how to do this, but want to shade the Sacramento, Feather, and American River basins. We don’t know specifics here yet, but the sources would come from water rights holders in these areas. 

Let me know if you have other questions, thank you again!

From: Kirk R. Klausmeyer 
Sent: Monday, June 25, 2018 1:22 PM
To: Jeanne Brantigan <jbrantigan@TNC.ORG>
Subject: RE: map for Sac Valley Water Trust report

Hi Jeanne-  yes I am the correct person to work with on this request.  I will likely delegate some of the tasks to Connor, our GeoDesign associate, but I’ll still be the main point of contact.  

Here are some of the questions I have for you about this map, filled out with some guesses based on your email

Print or Powerpoint?  IT sounds like you would like a printed map on a 8.5 x 11 page.  Do you need room for a figure legend or title outside of the map?  That is important so we can size it correctly.
Extent?  It sounds like you want it statewide
Main point of the map?  What do you want people to understand when they first look at the map?  What are the key features to show to demonstrate this?  Is it just a locator map or do you want people to be able to understand more about how the Sac Valley Water Trust will work?  
Title of the map?  Do you want the title on the map or will be in the text above or below the map on the printed page?
Content?  What layers do you want the map to display?  Do we have them mapped already or we do need to generate them?

Thanks!

Kirk

From: Jeanne Brantigan 
Sent: Monday, June 25, 2018 1:00 PM
To: Kirk R. Klausmeyer <kklausmeyer@TNC.ORG>
Subject: map for Sac Valley Water Trust report

Hey Kirk, I’m in a bit of a crunch but hoping I can work with your team to create a base map for the Sac Valley Water Trust (formerly WSIP) feasibility report that I’m finishing up with Cat this week and next. (Not sure who is on point for Water Trust spatial work at this point, so I’m starting with you!) 

Essentially we’d like to show potential areas where we’d source water, as well as potential buyer water districts and ecological targets (shorebirds and refuges), and major conveyance routes. It may be somewhat similar to what someone on your team did in powerpoint for Cat about a year ago, attached, except the buyers and sellers have changed and we’re expanding this to the full Central Valley and southern CA. (And we only need one map for a report, not built in series like this.)

Let me know if you want to chat or who I should work with. Thanks in advance!

Jeannie

JEANNIE BRANTIGAN, P.E. | Environmental Flows Project Director |  The Nature Conservancy
Jbrantigan@tnc.org | (916) 642-8054 (voice) | (916) 743-0764 (text)

**Comment by kklausmeyer** [comment]
I have included Tanu on this request because I think she was involved in the first set of maps, attached here.
[WSIP_maps.pptx](https://github.com/tnc-ca-geo/gd_intern/files/2138936/WSIP_maps.pptx)

**Comment by kklausmeyer** [comment]
For content, Here is a page that lists the CVPIA refuges:  https://www.wildlife.ca.gov/Conservation/Watersheds/Refuge-Water
For Aqueducts, check this feature class:  N:\Projects\CA_FWA\projects\DrinkingWater\gdbs\CA_Drinking_Water.mdb\line_aqueduct

**Comment by kklausmeyer** [comment]
Store the files in this folder:  N:\Projects\CA_FWA\projects\SacValleyWaterTrust
You can charge your time to: P100712

**Comment by connorshank** [comment]
mxd:
N:\Projects\CA_FWA\projects\SacValleyWaterTrust\mxds\SacValley_WaterTrust_Report.mxd

images:
N:\Projects\CA_FWA\projects\SacValleyWaterTrust\plots

**Comment by connorshank** [comment]
Could you please create a series of maps to build this map?

Map 1: show Rivers, CA Aqueduct, and “Potential Water Sources”, and all city and valley and delta labels, and Banks & Jones pumps
Map 2: add “Potential Agricultural Shorebird Habitat”
Map 3: add “CVPIA Refuges”
Map 4: add “Potential Water Buyers” with labels

Same size and jpg format as you did previously is fine, and would be most versatile for our use at the moment.

**Comment by connorshank** [comment]
We are having a call with the Wildlife Conservation Board on some potential funding opportunities for this project, and I need some quick additions to this map (and quick turn-around - by COB tomorrow if possible). At minimum I just need to add/label Mill Creek and Butte Creek which are tributaries to the Sacramento River because we’ve expanded the objectives of this project to benefit instream flows on these creeks.

**Comment by connorshank** [comment]
Same mxd location as before; new jpeg:
N:\Projects\CA_FWA\projects\SacValleyWaterTrust\plots\SacValley_WaterTrust_Report_July19.jpg
