### ISSUE TITLE
Location maps for TNC Groundwater website (7/6 flex)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#173]

**Comment by kklausmeyer** [comment]
Hi Connor-

Ryan would like to have a set of six small location maps for some case studies that will be posted on our groundwater website.  The maps are very small - ~1.4 x 1.6 inches - and just show one county highlighted in red.  Attached is an example:
[GWR Hub_Colusa County case study.docx](https://github.com/tnc-ca-geo/gd_intern/files/2151175/GWR.Hub_Colusa.County.case.study.docx)

Here is the email chain for context:

From: Ryan Luster 
Sent: Wednesday, June 27, 2018 11:11 AM
To: Kirk R. Klausmeyer <kklausmeyer@TNC.ORG>
Subject: RE: case study maps

Hi Kirk,

Thanks for the reply.  There’s not a rush on these but I’d like to have the maps by July 6.  Let me know if that works for you.

They can be very simple, just like the one I pasted in below which essentially makes the county where the project is located red.  

We would need a separate map for Sacramento County and a map for Glenn County.  

We are also doing a case study for the San Pedro River in Arizona located in Cochise County.

I have maps for the other 3 counties were highlighting.  

Thanks,
Ryan

From: Kirk R. Klausmeyer 
Sent: Tuesday, June 26, 2018 6:06 PM
To: Ryan Luster <rluster@TNC.ORG>
Subject: RE: case study maps

Hi Ryan-  I can help you with those maps.  

What is your timeline?

Do you need an area outlined for each, or would a big dot do the trick?  The big dot is easier.

If you can send me the locations drawn on a map, I can work on getting the 6 maps to you.  

Also, let me know if you need any labels on the map, and the size in inches for each of the maps.

Thanks!

Kirk

From: Ryan Luster 
Sent: Friday, June 22, 2018 1:23 PM
To: Kirk R. Klausmeyer <kklausmeyer@TNC.ORG>
Subject: case study maps

Hi Kirk,

We’re creating 6 more case studies for the Hub, each will have an inset map like below depicting the county in which the project is located.  

 

Who can I work with to get maps made like the above for each of the case studies?

Thanks,
Ryan

**Comment by kklausmeyer** [comment]
I re-read the email and it sounds like Ryan already has maps for the other three, so the total maps for you to do is 3.

**Comment by connorshank** [comment]
mxd location:
N:\Projects\Groundwater\mxds\GW_Case_Study_Iocation_maps.mxd

jpegs:
N:\Projects\Groundwater\plots\CaseStudy_locmaps
