### ISSUE TITLE
New GSA webmap for Tulare Basin (7/25 flex)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#174]

**Comment by kklausmeyer** [comment]
Hi Connor-

I would like you to make a version of the GSA webmap for just a selection of GSAs in Tulare Basin.  Basically, you can start with the GSA map you made for me, and then filter the GSA layer to only show a subset of the basins-  see the screen shot below for the details on the filter.  I did this filter on and earlier version of the webmap here: https://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=7ccc0882a5f44c50a8aa054bf40a4117

![image](https://user-images.githubusercontent.com/11560493/42404110-34bceb04-813b-11e8-86e3-7e1c41fb0cef.png)

**Comment by kklausmeyer** [comment]
The other change is to give each GSA a different color so you can tell them apart better.  Sandi gave this suggestion-  I suggest using pastel colors to keep the focus on the groundwater dependent ecosystem information.   I will forward you the email chain from Sandi and I so you can see the context.

**Comment by connorshank** [comment]
Kirk,
I have copied the Tulare map you linked and made the appropriate changes to symbology and such:
https://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=1a3b01054fe64a4aba57c0365b1a4a67

Just to clarify though, did you want a new version of the webapp (using this Tulare webmap) as well?

**Comment by connorshank** [comment]
I had some extra time, so I put together a web app viewer for the Tulare basins.   It's essentially a clone of the statewide version.   
http://tnc.maps.arcgis.com/apps/webappviewer/index.html?id=43f23bc0d4594c2aa7659103acb85144

**Comment by kklausmeyer** [comment]
Hi Connor-  a few edits on this webmap-  
1. Sharing- can you make sure it is public?  It asks me to log-in when I try to access it
2. Can you do the colors based on GSA_Name field rather than the basin number?  

Thanks!

**Comment by connorshank** [comment]
Updated and made public

**Comment by kklausmeyer** [comment]
Thanks Connor-  I noticed a few places where adjacent GSA have the same color.  For example Central Kings and South Kings are both yellow, and buena vista and semitropic are both purple (see screenshot below).  Can you look for other examples and change the colors individually to minimize this issue?  
![image](https://user-images.githubusercontent.com/11560493/43869247-6ee92482-9b26-11e8-80b6-3afadc9ccccc.png)
![image](https://user-images.githubusercontent.com/11560493/43869285-946f60f4-9b26-11e8-8709-3e5e523bf9f4.png)

**Comment by connorshank** [comment]
Kirk, I edited the GWA colors, I think I caught most of the adjacent color problems, but if you want to give it a quick look over I think it should be good to go.

**Comment by kklausmeyer** [comment]
Almost done!  Colors look good but it asked me to sign in when I hit the link.  Can you double check that it is public?  When it is done, please email a link to Sandi Matsumoto and myself.  Thank you!
