### ISSUE TITLE
Tehachapi Connectivity Maps

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#175]
Hi Connor - 

I started a map for Cara of Tehachapi Priority Parcels and Omniscape output (both present-day and future - separate maps). They also want to add road kill data and I pulled that data into the MXD.  I was hoping to get your help on finalizing some cartography to make sure the information is conveyed clearly. I will forward you Cara's original email with the goal for the maps.

The MXD is here N:/projects/connectivity/mxds/tehachapi_parcels

Thanks,
Carrie

**Comment by cschloss** [comment]
Hi Connor - 

Can you switch the Protected Areas from cross hatch to a transparent grey?
Can you also add the bridge that Cara referenced in her email? 

Thanks,
Carrie

**Comment by connorshank** [comment]
Carrie,

Do you have the map Cara mentioned, or a location for the crossing?

Sincerely,
Connor Shank

**Comment by cschloss** [comment]
Hi Connor - 

We don't have a GIS location for the crossing, but the map with the crossing is in the attachment to the email I forwarded you from Cara that also had the prioritized parcels

**Comment by connorshank** [comment]
N:/projects/connectivity/mxds/tehachapi_parcels

images:
N:\Projects\Connectivity\plots\TehachapiParcels
