### ISSUE TITLE
Data Mgmt - Download CoreLogic ParcelPoint 2018 (2nd qtr) updates (7/16 flex)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#177]
Hi Connor -

The second quarter parcel updates are now available.  I'll forward the email with details about which CA counties to update.

Thanks,
Megan

**Comment by connorshank** [comment]
Parcel data has been downloaded and updated for the listed counties.
N:\California\data\ownership\Parcels
