### ISSUE TITLE
Data prep for Fall 18 Birdreturns program (ongoing until 8/31)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#180]
hey @connorshank, bidding just opened for the Fall 18 BR program, bidding will be open until July 31st. Can you please monitor and map incoming bids? Thanks. Let's review how to process/map incoming bids tmo. Thanks.

**Comment by ka78** [comment]
Thanks for getting all the bids mapped! Next, as discussed:
1. pls do visual check that no fields are within airport buffer... 
2. complete the prg_match column in the "cleaned" Excel spreadsheet here: N:\WATER_Program\projects\birdreturns\2018_Fall\AuctionFall2018\AuctionMetrics
3. create pivot table to show avg indices for all fields within each bid, play with version that shows all fields along with bid average, see example .xls in the same folder as above

**Comment by connorshank** [comment]
Two pivot tables added to  MergeALL_Prog_Metrics_SAGBI_Cleaned.xls

Location of mxd with joined table and fields layer:
N:\WATER_Program\projects\birdreturns\2018_Fall\mxds\Fall2018_metrics.mxd
