### ISSUE TITLE
Data preparation for the Atlas launch (8/1)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#181]
hey @connorshank -- the details are still being worked out but I wanted to get this on your radar (we Skyped about this earlier today).

In order for users to link to the Atlas and zoom to the correct property at the correct map scale, we need to prepare some information to upload to Salesforce. The information you prepare will be used to craft a custom URL that will zoom users to correct property at the correct scale.

I'll populate this issue with the details once they're finalized, and we can meet to go over things in person. Thanks.

**Comment by ka78** [comment]
link to app: http://s3-us-west-1.amazonaws.com/conservationatlas/dist/index.html

**Comment by connorshank** [comment]
Both spreadsheets have been updated with zoom extent numbers, save for properties without extent information.
