### ISSUE TITLE
Data Mgmt – Delineate property for potential acquisition (7/20, flex)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#182]
Hi Connor -

This request shouldn't take much time, but if it isn't doable in the next day or so just let me know.

M. Sweeney is interested in a property and asked M. Conner to investigate.  It is a large property (~27,000 acres) with over 75 parcels in at least two counties.  I’ll forward the list of APNs.  If possible, it will be easier to select parcels by owner name, but you should still check that the parcel APNs match the APNs in the list.  Consider the details of this request as confidential.

This is what’s needed:
Use current CoreLogic county parcel data to create two shapefiles 1) Of all the parcels 2) Of just the property boundary.

Once complete, I will add this property to our TNC CA Tracts dataset so Mike can investigate the location of the property using the Conservation Atlas.

Thanks,
Megan

**Comment by connorshank** [comment]
Two files have been created in N:\North_Coast\Shapes
nc_CabRanch_Boundary_20180720.shp
nc_CabRanch_CoreLogic_20180720.shp
The un-merged CoreLogic parcels for the property are:
nc_CabRanch_CoreLogic_TRINITY.shp
nc_CabRanch_CoreLogic_MENDOCINO.shp
