### ISSUE TITLE
3D Web Scene of Existing and Proposed Wind Turbines (9/15/2018)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#184]
Overall goal is to create a web scene depicting Existing and Proposed Wind Turbines in Wyoming.

Existing Wind turbine feature service is located at: 
http://tnc.maps.arcgis.com/home/item.html?id=221fb64729414003aea6a8ee14f6ffab

Example of web scene: 
https://www.arcgis.com/home/webscene/viewer.html?webscene=3d70a3f4268c49239c051b3cf3d030a3&viewpoint=cam:-116.67789346,33.9415129,1410.889;81.098,64.123

Wind map package and turbine style to be emailed.

Once web scene is developed we will reconvene and delve into more details.

**Comment by connorshank** [comment]
Workspace:
N:\Projects\Wind
