### ISSUE TITLE
create map for Colusa Groundwater Authority (9/10 ideally)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#186]
hey @connorshank, 
Julia received permission from DWR (who awarded us the grant) to work outside of the SDAC we identified in our original grant proposal. Julia's next step is to appeal to the Colusa Groundwater Authority to get their permission.  She needs a map to help make her case.
This product can be 1 or 2 pages, or however many are needed to make the case. Here's what we need to show:
- we're interested in working just south of Arbuckle, where there is significant gw depletion
- show the georeffed image from the Davids Engineer study
- show sagbi 
- show crops
- show the DAC and the DCPlace (https://gis.water.ca.gov/app/dacs/) that coincides with Arbuckle
- we want to be zoomed into the Arbuckle and gw depletion area
- we'll need to be creative with how to show all this and not have an overly busy map, we can have 2 pages, maybe 1 page is full size map, and other page is 2 side-by-side half-page maps, not sure, need to play around with it

Julia and Greg will be commenting on this deliverable, she's preparing a document to accompany these visuals I believe. She should tell us how she wants to tile the map(s).

She'd love this by mid-next week, but I told her you have a lot on your plate, so the due date is flexible. 

Let's talk before you start working on this, I just wanted to get something down on 'paper' with this Github Issue.

**Comment by ka78** [comment]
hey @connorshank so, the sagbi/crop jpeg is unreadable imo…

I suggest you break this up into 2 pages with 4 small maps:
Page 1:
1.	left half of page: zoom in a bit on the arbuckle map, show only DC and DBG, don’t worry about SDAC, add very simple locator map with only Colusa outline and Arbuckle point, both neatly labeled
2.	right half of page: same as above, but add in the overlay from the Davids Engineering report
Page 2
1.	left half: same extent with arbuckle dot and label, show crops
2.	right half: same extent with arbuckle dot and label, show sagbi

I'm trying to get the original Davids Engineering graphic for you, but here you can see how I did a quick and dirty overlay by lining up couty line and Arbuckle: https://tnc.box.com/s/grn4f711q25vev0ncwv1d5bnli4664u5

Let's talk live about this today...

**Comment by connorshank** [comment]
mxd location:
N:\WATER_Program\projects\gw_recharge\grant2018\mxds\Colusa_Arbuckle_map.mxd

image location:
N:\WATER_Program\projects\gw_recharge\grant2018\plots

**Comment by ka78** [comment]
hey @connorshank, I'm re-opening this issue and adding in a map expansion/revision:

The Colusa Groundwater Auth would like us to look at another area of depletion as shown in the Davids Engineering study. Please:
1. georeference the image from the Davids Engineering study... probably just use the clipped jpg version I made here: N:\WATER_Program\projects\gw_recharge\grant2018
2. review the map(s) you made for Julia to include this new area; it's just north of Arbuckle so I think if you just zoom out a little you can capture the new area

Lmk if you have questions, thanks

**Comment by ka78** [comment]
@connorshank can u please populate this issue with final pathnames? then it can be closed. THANKS.

**Comment by connorshank** [comment]
mxds:
N:\WATER_Program\projects\gw_recharge\grant2018\mxds

pdf and jpeg maps:
N:\WATER_Program\projects\gw_recharge\grant2018\plots

there are also powerpoints in the grant2018 folder.
