### ISSUE TITLE
Add Omniscape Connectivity layer to DP Web App (by 9/5)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#191]
Please add the layer from http://tnc.maps.arcgis.com/apps/webappviewer/index.html?id=3cbb9454372e43ffac44b9dda07b5551 into the Jack and Laura Dangermond Preserve web map. Please name it LANDSCAPE -Connectivity (TNC)

**Comment by connorshank** [comment]
The layer has been added to the webmap, near the bottom of the list, just above imagery.   I used the classified version with the blue-green-red color scheme, let me know how it looks.

**Comment by bcohen27** [comment]
Looks great, thanks!
