### ISSUE TITLE
create repar-like map for Oasis Ranch property (9/4)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#192]
hi @connorshank, as discussed and described in the email from Jake Jacobson, please create a simple 8.5x11 real estate map showing the Oasis Deal, with some of our surround fee properties, and the battle creek river.

you can pass a draft by Jake and me; I believe his email indicates he needs this by 9/4.

I fwd'd you Jake's email, and I've finished editing the data. thanks!

**Comment by connorshank** [comment]
mxd location:
N:\Central_Valley\Projects\LassenFoothillsGIS\Mxds\BattleCreek\CA_BattleCreek(OasisSprings)_20180830

pdf location:
N:\Central_Valley\Projects\LassenFoothillsGIS\Plots\BattleCreek
