### ISSUE TITLE
Present day connectivity service for atlas (10/20 - Flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#196]
Hi Connor - The present-day connectivity is needed for the Atlas - I am going to reclassify the layer to simplify the legend and then we have the following requirements for publishing to use in the Atlas: 

1. The service needs a description; this can be added to the metadata of the raster layer before publishing (the app just pulls from the “Description” section of the published service. Descriptions: “This analysis represents a wall-to-wall picture of regional habitat connectivity for plant and animal species whose movement is inhibited by developed or agricultural land uses. The approach treats landscapes as resistive surfaces, where high-quality movement habitat has low resistance and barriers have high resistance. The algorithm incorporates all possible pathways between movement sources and destinations and identifies areas of high flow via low-resistance routes, i.e., routes presenting relatively low movement difficulty because of lower human modification, and thus mortality risk.”
2.	Service needs to be tiled - as you did for the climate connectivity layer - and published on its own (not packaged with punch through etc)  

I will add a pathway to the reclassified data with the new legend shortly.

Would publishing by 10/10 be possible if I get you the new layer today?

Thanks,
Carrie

**Comment by cschloss** [comment]
Hi Connor - the reclassified, symbolized layer file and associated raster is at
N:\Projects\Connectivity\grids\Inputs201701\norms90\sqRbS90__raw_i7_d13_c17_splitHM_2_condenseClass.tif

Thanks!

**Comment by connorshank** [comment]
The condensed omniscape layer has been published as a tiled service and can be found here:
http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/Conn/Connectivity_for_Atlas/MapServer/0

**Comment by ka78** [comment]
@nathanielrindlaub, do you mind checking to see if this REST URL will work to replace the Omniscape layer currently in the Atlas? If it works then I'll fill out the Layers doc with the details, thanks!

**Comment by nathanielrindlaub** [comment]
Yes! It worked and it's live: https://atlas.codefornature.org/#/topo-vector/6/10111415161719202122232430313435399904030807/null/null/-120.99999999999794/36.999999999999375

**Comment by ka78** [comment]
Good news! Thanks Connor for publishing these data!

**Comment by ka78** [comment]
Oops. Hmm. The name of the layer in the Atlas Legend is whackadoodle:

![image](https://user-images.githubusercontent.com/11932002/46836029-b7ddf300-cd64-11e8-8bc7-799443e190ec.png)

@connorshank I this is set in the MXD? Can we change this to Present Day Connectivity? 

@nathanielrindlaub I'm assuming you cannot change this in the Atlas right? But even if you can I feel like the endpoint should have the correct name.

@connorshank we can work with this layer as is, until you republish - there is no urgency, so I'm going to reset the due date for next Friday, but you can push back if you're really busy.

**Comment by ka78** [comment]
@connorshank, reopening this issue. Can you provide a pathname to the mxd so I can take a look?

**Comment by ka78** [comment]
Perfect, thanks @connorshank:

![image](https://user-images.githubusercontent.com/11932002/47466363-c46f3c00-d7a5-11e8-99d2-80a302cbd497.png)
