### ISSUE TITLE
2 property maps for Mike Connor (10/12 flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#198]
Mike Connor has requested 2 property maps. 

Nearly all of the details are covered in the email thread you were on, but connectivity will be more nuanced; you'll need to browse the connectivity data we have (in CA/data)  and see if there is anything relevant for the areas of interest and decide what to show - we can look at this together. Also, there is Carrie/Dick's Present Day connectivity... if we show that then I think we will need 2 maps for each property because the raster under all the other data Mike needs will be unreadable... let's talk when you have browsed the connectivity data and make a decision. 

Mike asked what timeframe is reasonable for these maps. Can you reply all to his email and suggest a delivery date that is reasonable for you? and that allows time for the review of 1 draft? Thanks!

**Comment by connorshank** [comment]
Thanks, Mike we have a few connectivity datasets, the newest of which you can view in the Beta Atlas, it’s at the bottom called Omniscape (we’re cleaning this up but you can get the idea). Do you want traditional connectivity (linkage lines etc) or this new wall-to-wall connectivity, or we can do both.. please advise.

Okay Connor, so the official and nearly complete requests are (I created a Github ticket for this):

Map 1:
	8.5x11 map PDF map for printing  yes
	create a property boundary using APNs listed below yes
	what is the name of this property? Schneider Properties, Cosumnes
	title the map with the property’s name Name as  stated ^
	add any/all connectivity we have for the area yes connor let’s look at the various connectivity layers and choose what to show
	add protected lands + easements yes
	what kind of ‘groundwater layer’ do you have in mind? we have something called soil agriculture groundwater banking index (SAGBI – good for assessing gw recharge potential), would that be helpful? PERFECT PLS INCLUDE  if not pls describe what groundwater attributes you want to illustrate and we’ll see if we have data to match your needs.
	map extent? zoomed out enough to portray the connectivity importance of the property? yes
 
Map 2:
	8.5x11 map PDF map for printing yes 
	show the Rancho Latigo property (from the Tracts GIS layer) yes 
	title map “Rancho Latigo property” yes
	add protected + easements (label large protected) yes
	add connectivity layers yes connor let’s look at the various connectivity layers and choose what to show
	map extent? similar to what you show in your Atlas map, showing Dangermond Preserve (maybe tighten up the zoom level a little bit)? yes

**Comment by ka78** [comment]
@connorshank are you still waiting for feedback?

**Comment by connorshank** [comment]
mxd location:
N:\LAND_Program\mxds

jpeg location:
N:\LAND_Program\plots
