### ISSUE TITLE
Rangeland Parcel Analysis

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#2]
Background: TNC is developing strategies for successful conservation of rangelands.  This fall the working lands team will begin to pilot the strategy, but first they need to know where the best places in the state are to pilot the strategy.  Many factors including land owner willingness will determine pilot location, but a statewide spatial analysis will be the start to identify which landowners to begin talking to.  The strategy is to develop rangeland neighbor cooperatives where neighboring rangelands can have better access to forage through a property with shared forage.  Therefore, we need to identify aggregates of rangeland properties that are adjacent, have high biodiversity value and are permeable to wildlife, and are at risk of conversion. The limiting factor in this analysis is parcel data.

Analysis Need: 1) Develop a statewide parcel database with ownership information (either from Core Logic or the Counties themselves) dissolved on ownership and screened for rangeland extent
2) Spatial analysis to identify pilot potential from the rangeland properties above

**Comment by cschloss** [comment]
Hi Cori

N:\California\grids\UCD_climateExposure\VegExposure\VegExposure\cnrm_cm5_rcp85\
N:\California\grids\UCD_climateExposure\VegExposure\VegExposure\miroc_esm_rcp85\

Here are the exposure analysis to pull in.  The 50 year horizon is 4069, the end of century is 7099.  We can wait for Rodd's response on the planning horizon.  Please take a look at the readme file in the veg exposure data to get a better idea of what the data means.

Before you summarize by property, we'll need to create a modified version of this data.  The no analog is currently coded as a 1.  Let's code this as a 2.  Then lets run the property average in the R code on the modified dataset.

**Comment by cschloss** [comment]
Awesome work on finishing the pilot prioritization tiers and map!

Next steps from our meeting with Rodd:

1. Chart of # of ranches that meet biodiversity criteria (threshold >=3.5) histogram (4/4, 3/4, 2/4/ 1/4, 0)
2. Anchor ranches - how much protected (Fee only)  rangeland is within 20km (maybe still a question of dist?)
3. Partner ranches - how much protected land (fee and easement) is within Xkm (dist?) of partner ranches
4. Map of protected land (fee) colored by total acreage of rangeland within the boundaries

**Comment by cgrainger431** [comment]
The new prioritization is done and the web application has been updated; the web app will be transferred to you on AGO.  

All of the data lives here: N:\Projects\Rangelands\Projects\Prioritization\data
Web Map
-	All data is published to WASPATIAL in the CARO folder
-	MXDs and Data on WASPATIAL server: D:\GIS_data\CARO\Rangelands
-	Web map data on N: N:\Projects\Rangelands\Projects\Prioritization\data\Data_for_waspatial
Data Structure on N
-	Data layers the spatial statistics were run on the attribute data to Rangeland Parcel Master: N:\Projects\Rangelands\Projects\Prioritization\data\attributeLayers
-	Intermediate data layers created when making the Rangelands Parcel Master: N:\Projects\Rangelands\Projects\Prioritization\data\RangelandParcelsIntermediates
-	Rangeland Parcel Master Datasets: N:\Projects\Rangelands\Projects\Prioritization\data\Range_Parcel_Master.gdb
(Rangeland_Parcel_Master_2016_10_5 is the dataset we used for the old prioritization and Rangeland_Parcel_Master_20170516 is the updated master dataset for the new prioritization)
-	Properties pulled out in the “Properties of Interest layer: N:\Projects\Rangelands\Projects\Prioritization\data\TNC_Rng_interests.shp
-	Rangeland attributes of “Properties of Interest”: N:\Projects\Rangelands\Projects\Prioritization\data\TNC_Rng_prcls_interests_update_clip1.shp

I uploaded the new query spreadsheet to Box, which is embedded in the Web Map. 

I was not able to update the methods or the attribute descriptions for the new layers (connectivity, rangeland climate stress, etc).

Some key documents:
[RangelandTiers_Queries_20170627.xlsx](https://github.com/tnc-ca-geo/gd_intern/files/1132423/RangelandTiers_Queries_20170627.xlsx)
[RangelandTiers_update_20170508.docx](https://github.com/tnc-ca-geo/gd_intern/files/1132424/RangelandTiers_update_20170508.docx)
[RangelandMethods_update.docx](https://github.com/tnc-ca-geo/gd_intern/files/1132426/RangelandMethods_update.docx)
[DataList.docx](https://github.com/tnc-ca-geo/gd_intern/files/1132430/DataList.docx)
