### ISSUE TITLE
Property Routing REPAR Map, Anderson -- (10/16)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#200]
@connorshank this is a request for a REPAR map set, similar to what @megrwebb describes in this issue:
https://github.com/tnc-ca-geo/gd_intern/issues/71. From that issue, we'll need only the "1 of 2" and "2 of 2" maps, not the extra APN map that is described.

This is for Chris Basilevac; he's working on the **Anderson (Sierra Valley)** Deal: https://na60.salesforce.com/0060c00001SjVmj

Can you please send him a draft for comment? He may request some specific things labeled, to match his deal narrative.

And, in addition to the maps, can you please create a shapefile of this property, strip out all of the fields other than TRACTNAME, and send it to Chris? He needs to share it with a contractor. Thank you.

Lmk if you have any questions.

**Comment by ka78** [comment]
ps: this is a deadline with a little wiggle room if you get in a bind. Chris would like to route the deal soon so I chose 10/16 based on our Skype chat about this.

**Comment by connorshank** [comment]
Mxd locations:
N:\South_Coast\Mxds\CA_Anderson(Riverside)_map1of2_20181012
N:\South_Coast\Mxds\CA_Anderson(Riverside)_map2of2_20181012

Plots:
N:\South_Coast\Plots\CA_Anderson(Riverside)_map1of2_20181012
N:\South_Coast\Plots\CA_Anderson(Riverside)_map2of2_20181012
