### ISSUE TITLE
TNC Protection Numbers for USFWS CV Joint Venture (Nov 7)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#201]
Hi @connorshank, Paul Spraycar from the Dynamic Water Team has asked us to pull together some numbers to report to the USFWS Migratory Bird Program, Central Valley Joint Venture. Specifically, how many acres has TNC protected in the Central Valley since 2006? Can you help me with this? Here are some details:

1. properties TNC protected: TNC Interests
2. central valley: the CVJV is talking about the valley floor, which they say LT 300'. you can either select (using the lasso) using the map on [page 6 of this report](http://centralvalleyjointventure.org/assets/pdf/CVJV_fnl.pdf) if it's straightforward enough, or you use a DEM on ca/data and select from that
3. you can use the PROTDATE in the Interests data to select out only properties protected in and after 2006, and INTEREST_TYPE to select for Fee, Easement and Historic.
4. please send the total acres for TNC Fee, TNC Easement and TNC Historic to Paul and cc me pls.

This isn't urgent so I put a due date of 2 weeks from today.
Thank you!

**Comment by ka78** [comment]
Thanks Connor! Would you please add an mxd path and then you can close this issue.

**Comment by connorshank** [comment]
table location:
N:\Central_Valley\Tables\CV_TNC_Interests_2006.xls
