### ISSUE TITLE
Additions to Jack and Laura Dangermond Coastal Map (When possible by 11/30)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#203]
We have a request to add more layers to the JLDP coastal map: 
●	Coastal Zone boundary; 
●	Property boundary- of the  Jalama parcel to be transferred, using a dashed line;
●	Tar seeps  (not tarballs or oil samples,  just points identified as natural seeps; from USGS); 
●	all 24 small coastal streams (from WRA); 
●	Species Occurrence and critical habitat data for this coastal area – by spp (as in WRA figs 17 & 20) 
●	Offshore rocks in BLM’s CA Coastal NM (https://navigator.blm.gov/api/share/6d3d54f897ef3ce1)
●	Surfgrass, seabird colonies, intertidal monitoring points (from Marinemap website)
●	Upwelling (see Matt’s composite layer)
●	Dune sands (from paper Dibblee geology map that MR has. We may have to digitize or other wise evaluate if this is possible) 

Confer with Brian on any datasets for which you have questions.

**Comment by bcohen27** [comment]
Thanks Megan. It turns out that this is a request to update the coastal map, not the web map/app.

**Comment by megrwebb** [comment]
Note, I've made a few aesthetic changes to this map. The current mxd is here: N:\Central_Coast\Projects\Sba\Sites\BRSB_Confidential\Mxds\sba_DangermondPreserve_Coastal_Resources_20181107

**Comment by bcohen27** [comment]
● Coastal Zone boundary;  - all land shown in the map extent are within the CZ boundary, so this probably isn’t necessary (doesn’t even appear in frame)
● Property boundary- of the Jalama parcel to be transferred, using a dashed line; - I’m assuming this is one (or more) of the parcels within DP?  Do you have an id for which ones to include?
● Tar seeps (not tarballs or oil samples, just points identified as natural seeps; from USGS); - same source as webmap
● all 24 small coastal streams (from WRA); - same source as webmap (I think)
● Species Occurrence and critical habitat data for this coastal area – by spp (as in WRA figs 17 & 20) – could you point me to the WRA source?
● Offshore rocks in BLM’s CA Coastal NM (https://navigator.blm.gov/api/share/6d3d54f897ef3ce1) – same source as webmap
● Surfgrass, seabird colonies, intertidal monitoring points (from Marinemap website) – working on downloading from UCSB website
● Upwelling (see Matt’s composite layer) – I think this is the one included in the webmap, if not it is probably in California Current folder
● Dune sands (from paper Dibblee geology map that MR has. We may have to digitize or other wise evaluate if this is possible) – can you point me to a source on this?

**Comment by bcohen27** [comment]
**Coastal Zone:** use new inset map (but make it look better and place where it does not obscure other necessary data
**Property Boundary:** layer Jalama_Transfer added to map, need to put into legend
**Species Occurr..:** WRA maps start at page 136 in https://tnc.app.box.com/file/286260603625 for reference, seems like some of the data are already displayed in map, others should be in the Wildlife group that is in the map or in other .gdbs in N:\Central_Coast\Projects\Sba\Sites\Dangermond_Preserve\Gdbs\WRA_CJR_Viewer_20170918\
**Dune Sands:** not feasible at this point, we can hold off on this one.

**Comment by connorshank** [comment]
Brian, that Box link doesn't work for me, I might need to be invited into the group.
