### ISSUE TITLE
Analysis of property owners in Colusa DAC (Nov 7, flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#204]
@connorshank, back in May you did an analysis for Julia of landowners in the SDAC in Colusa Co. where she received a grant for dynamic recharge work. Now there is another project area, a DAC near Arbuckle. Julia would like a spreadsheet of landowners who have 1) selected crops and 2) desirable recharge potential.  Before I write out the steps for this analysis, I'd like to hop on the phone with you to discuss options. I'll find you on Skype, and then I fill in the rest of this request.

**Comment by ka78** [comment]
As per our phone chat, here is the mxd >> N:\WATER_Program\projects\gw_recharge\mxds\arbuckle_owner_analysis.mxd, thanks!

**Comment by connorshank** [comment]
Table location:
N:\WATER_Program\projects\gw_recharge\tables\colusa_crop_sagbi.xls

mxd:
N:\WATER_Program\projects\gw_recharge\mxds\arbuckle_owner_analysis.mxd
