### ISSUE TITLE
Download Unimpaired Flows Data (flex 12/15)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#205]

**Comment by kklausmeyer** [comment]
Falk gave me the harddrive for you to download to.  Can you check to see if you have a USB 3 port: https://support.magicard.com/solution/how-do-i-know-if-my-computer-has-usb-3-0-ports/

**Comment by postfalk** [comment]
Thx

**Comment by postfalk** [comment]
Thanks again, for doing that. Is there a reason why there is no 10.2.3 folder between 10.2.2 and 10.2.4.
Adding @kklausmeyer.

**Comment by connorshank** [comment]
@postfalk that particular region was not available for download for some reason, I think it might be the Everglades ecoregion, for some reason I recall that being omitted and finding it odd at the time.

**Comment by postfalk** [comment]
Thx
