### ISSUE TITLE
SWIF data collection in AGO (12/10)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#206]

**Comment by kklausmeyer** [comment]
Hi Connor-  

I checked out the mxd and it is looking good.  I confirmed with Tanu we are using the correct strategic fallowing layer.  Lets use the "1 or more species" layer and remove the other one.  

I would like to remove the freshwater blueprint from this group and publish it to AGO separately.  I will do that step.

In its place, please add in this layer:

N:\Projects\CA_FWA\gdbs\water_trust_1June2018.gdb\CA_water_trust_catchments

Please create a new feature class and remove any polygons with the Sept_1995-2015 value less than 0.01.  Then  symbolize the new Sept_1995-2015 layer based on these breaks, and label each value with the units "CFS":

1.	.01 to 10
2.	10-50
3.	50-100
4.	100-200
5.	200-300
6.	300+

Call the layer "September Unimpaired Stream Flow"

After that we should be ready to publish!

**Comment by kklausmeyer** [comment]
Hi Connor-  Can you add the latest CNDDB data to the SWIF feature service so I can view on AGO?  I would prefer a feature service instead of a map service, but either one will work fine.  Thanks!

**Comment by kklausmeyer** [comment]
Hi Connor - can you add the URL for the map service to this issue so we can find it later?  Thanks!

**Comment by connorshank** [comment]
Service (Stratus):
https://www.tnccmaps.org/arcgis/rest/services/Lands/cnddb_service/MapServer

mxd:
N:\LAND_Program\mxds\cnddb_service.mxd
