### ISSUE TITLE
Data Mgmt - CoreLogic ParcelPoint Update, Fourth Quarter 2018 (12/21 flex) 

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#208]
Hi Connor,

The fourth quarter, 2018 ParcelPoint updates from CoreLogic are now available. I'll forward you the email with details.  Please download the CA county updates to N:\California\data\ownership\Parcels and use our most recent naming convention.

Thanks,
Megan

**Comment by connorshank** [comment]
All new counties parcel data has been downloaded, renamed, and placed in the appropriate folder in:
N:\California\data\ownership\Parcels
