### ISSUE TITLE
Project Pitch Forms- Pajaro

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#21]
Hi Cori

Please use the wording and questions of this word doc to set up a Project Pitch Survey.  I run a script on the output data from this survey and the output of our network survey, so it is important that the data are collected in the same way where they match.  

When you set up the new project pitch survey - can you take a look at the network survey that already exists and use the same type of question (i.e. checkbox, multiple choice etc.) and use the same answer choice options?  

Here is the template for the survey - see the drop down menus embedded within the word doc.
[02. RCDSCC Agriculture Working Group - June 2016 Compass Intake.docx](https://github.com/ka78/gd_intern/files/448093/02.RCDSCC.Agriculture.Working.Group.-.June.2016.Compass.Intake.docx)

Here is the network survey that exists that we will try to be consistant to in terms of question type and wording.
https://docs.google.com/forms/d/1QTQU50s-6QEvH_KqKvLg_O0G4lHJ290TTwa9JOnyOs8/edit

**Comment by cgrainger431** [comment]
Hi Carrie,

I made the changes to the project intake form.  The old strategies are still in there and I left the theme as carbon stock/ climate change for now.  I also transferred ownership of the survey to you.
