### ISSUE TITLE
Data Mgmt - Download remaining FMMP GIS Data from 2016 (flex)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#210]
Connor,

We have _some_ of the FMMP GIS data from 2016 here:  N:\California\data\agriculture\FMMP_2016

Recently, I downloaded Tulare County and the statewide dataset for a map and noticed there are more counties we don't have on CAROSPATIAL.  Would you check to see what counties are missing and download these shapefiles to our FMMP_2016 folder?

Here is the link about this program: https://www.conservation.ca.gov/dlrp/fmmp
and this is the FTP site: ftp://ftp.consrv.ca.gov/pub/dlrp/FMMP/2016/ to download the data.

Thanks,
Megan

**Comment by cschloss** [comment]
Hi Connor and Megan - 

I wrote a script that will figure out what is missing and automatically download it.  It lives here:
N:\California\data\agriculture\FMMP_Updater_Script_R.R

I can run it now to grab the rest of 2016.  Feel free to use in the future anytime you want to pull the updated FMMP's. 

Carrie

**Comment by megrwebb** [comment]
Ahh, I have some vague recollection of this!  Thanks Carrie!
