### ISSUE TITLE
Forest Climate TCSI Analysis (draft 2/8, final ~2/15)

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#215]
a.	What percent of TCSI landscape falls within high exposure category and what is the current forest 
        structure in those area?
	- Forest Structure component to focus on Size class, Dominant Age class, and Vegetation type
	- How much of that is operable 
	- How much of that is potential owl habitat (for this we will currently use owl observation or large 
           tree size class as an index) but we plan to find 
	         - If there is already a potential owl habitat data layer available for TCSI 
	         - If not we will model it ourselves using above forest structure component,  RS variables and Owl observation
b.	I will send you the LEMMA grids I already created
c.	You will send me climate exposure data clipped to TCSI

**Comment by TB2016** [comment]
Connor – Download the GNN grids from CLIP folder here. Don’t d/l entire GNN grid folder. It has all GNN attributes. For demonstration purpose we don’t need that. 
https://drive.google.com/open?id=1jwhLayiCnwQRPEzpqEi8T8a4cT71KAgc

Here is link to ClimateExposure
https://drive.google.com/open?id=14KbZOVX8ZkHVmb-kmfEyYwcRZw2EPNFA

Here is the ppt I am working on 
https://drive.google.com/open?id=1rdA6RxrINJ-PtU20fJhFPHxhMUr-h2XhkoOIwjIZGMs

**Comment by connorshank** [comment]
Can you do the same calculations for total acres under each exposure class by operable (slide3) and non-operable (slide 2 - 2nd graphic).

Operable Acre exposure 3 and 4 (slide 4) 

Fire Risk (Class 4, 5. 6)

Total Volume > reclass it by quantile (then summarize acres for class 4 and 5)  in exposure class 3 and 4
Similarly do the same for Size Class (CWHR data). You should have CWHR size class data. Its on TCSI web
Also upload the climate exposure classified data (1-5) on TCSI webmap and the one with only class 3 and 4

**Comment by TB2016** [comment]
@connorshank - here is the link to fastEmap data with Total Volume and Trees Per Acre

https://drive.google.com/drive/folders/1gdWou5lusUuQxYOjKK9ktnESt4EKEMJ6?usp=sharing

**Comment by connorshank** [comment]
Workspace:

N:\Sierra_Nevada\Projects\TCSI_climate
