### ISSUE TITLE
Agriculture Team Support (Interim)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#22]
Hi Cori-

I am hoping you will be able to help out the Agriculture team (Abby and Jen, CC’d here) as they start putting together some data to help them scope different strategies for the Land Team.  This work will transition to the new Sacramento Spatial Data Scientist when that person starts, but I’m not sure when that will be, so I am hoping you can fill in as interim support.  Abby and Jen will follow up with a meeting time and place.  This will be a good opportunity for you to see how strategy development takes shape, and how science and data can help inform that process.  Carrie has already done some good scoping analysis for this team (see attached and the description below of the data locations), so she will be a good resource moving forward.  I’ll post this in GitHub so you can keep track of it.

Thanks!

Kirk

An mxd with the following layers is in: N:/projects/agriculture/mxds/ag_prelim_spatial
1.       Ag lands (FMMP)
2.       Water Quality Index (California Healthy Watershed Assessment)
3.       HUC8 with 303d listed water bodies (screened for Nutrient pollutants from Ag)
4.       Connectivity  - California Essential Habitat Connectivity 
5.       Groundwater Recharge (BCM – historic)
6.       Groundwater Recharge Potential – SAGBI
7.      Fresh Water Assessment Aquatic Species Richness
8.       Aboveground Carbon Stock (Gonzalez) – not useful for Agriculture Analysis because crops not accounted for – but requested by group

**Comment by cgrainger431** [comment]
Hi Kirk- Is this still something I should have as an assignment? Or would any future support be project specific?

Thanks!
-Cori

**Comment by kklausmeyer** [comment]
You can close this one!  I think Tanu is handling the incoming requests from this team.

On Apr 26, 2017, at 1:30 PM, cgrainger431 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kirk- Is this still something I should have as an assignment? Or would any future support be project specific?

Thanks!
-Cori

-
