### ISSUE TITLE
Implement additional properties - rdm

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#221]
Placeholder card:

https://github.com/tnc-ca-geo/rdm/issues/220

**Comment by postfalk** [comment]
Please clarify what actions to take if any.

**Comment by ka78** [comment]
Hey Connor, following up from convo with @einlander1  and me today, here are the data on Carospatial --> N:/Land_Program/projects/Stewardship/rdmapper

**Comment by ka78** [comment]
thank you @connorshank. the only outstanding item is what we discussed this morning: please add your spreadsheet data as a new tab to the original data. pls name the original data tab "source" and your data something like "formatted" -- this is so we have only one spreadsheet per property. thanks a lot, I'll go ahead and close this.

**Comment by ka78** [comment]
@connorshank, we'd like to add Dangermond RDMapper data prep to your queue. @einlander1 will get you the Dangermond data. Can you please format that data the same way you did the previous and let us know when this is complete? @einlander1 will have something for you in the next couple of days.

**Comment by connorshank** [comment]
The management_units shapefile has been updated to include the JLDP pastures, located here:

N:\LAND_Program\projects\Stewardship\rdmapper\templates\management_units.shp
