### ISSUE TITLE
Share GIS data on properties with OSA

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#222]
Hi Connor - 

Abby and Sasha have a GIS request I am hoping you can help out with - should be quick.

Can you pull the following properties from the tracts layer and export as a shapefile:

-	El Toro
-	Paxton/Soap Lake Ranch (now has partial easement)
-	Rancho San Benito/Floriani
-	Bourdet
-	Red Fern
-	Willow Creek/Zgragen (now has CRT easement)
-	Oak Pine

They should all be within Santa Clara county or norther San Benito.

Thanks,
Carrie

**Comment by ka78** [comment]
hey @cschloss this is for sharing outside TNC I presume? If so, @connorshank you should probably strip out all fields other than tractname and gis acres...

**Comment by connorshank** [comment]
Exported, with sensitive information removed:
N:\Central_Coast\Shapes\tracts_for_OSA.shp

Couldn't find a tract with the name Pine Oak, are there any other names it might be listed under?

**Comment by megrwebb** [comment]
The tract is called Oak Pine Ranch

**Comment by connorshank** [comment]
Thanks Megan, found it!  Exported a new shapefile with all properties, same name as above.

**Comment by cschloss** [comment]
Thanks Connor!
