### ISSUE TITLE
Santa Cruz Island MPA map (Due 4/5)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#223]
From Caitlin:

We’re in the process of creating a tidebook for our Santa Cruz Island landing permit holders to reference while they are out at SCI and we’d like to include a map of the Island that shows the marine protected areas. I’m thinking this can be a basic greyscale map of the Island (that is, not with all the detail of the landing permit map) with the MPA’s shaded. Would this be something you might be able to help make for us (or that you might already have)?

The tidebook is only 3.5 x 5.5 inches, but if the map is larger than that it would be good for us to have on hand for other purposes. Hopefully this is enough information to go off of, but if not, just let me know!

Thanks so much,
Caitlin

**Comment by connorshank** [comment]
mxd:
N:\South_Coast\Projects\SCI\mxds\SCI_tidebook_MPAs.mxd

images:
N:\South_Coast\Projects\SCI\plots (same names as mxd)
