### ISSUE TITLE
Organize and map priority real-estate properties (5/3)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#227]
Hi Connor - 

I will get in touch about deadline, but if possible, we are hoping for a quick turn-around.

This is to compile multiple excel sheets (4-5) into a single google sheets doc (some have extra fields, please retain the extra fields and just leave those fields blank if they are absent in one of the sheets).

The  next step is to create a single shapefile of these priority properties. Most of the priority properties will be in the TRACTS layer, but some may only be referenced by APNs and county and then we will need to grab it from the county parcel data and dissolve.

Last, if time allows, join the compiled data in the spreadsheet to the shapefile to retain the info directly in the shapefile.

I will forward you the info you need shortly.

**Comment by cschloss** [comment]
Also, please add a column for the source - i.e. who submitted the priority property based on which spreadsheet it came from so we can reach back out to them if we need to to get more info.

**Comment by megrwebb** [comment]
Hey @cschloss, I’m not up to speed on this project, but if there are any priority real estate properties not in TRACTS we should get them in there.  As Connor works on this request, let’s coordinate so I can make sure these are accurately captured in TRACTS as properties of conservation interest.

**Comment by cschloss** [comment]
Hi @megrwebb - adding some context about this project:  as a part of the Protect Lands and Waters work we are doing an Asset and Action map to identify potential land protection priorities statewide, but are also engaging in a 'bottoms-up' approach to make sure we are capturing what the investments team already knows are priorities.  This will have 2 functions: 1) these properties won't slip through the cracks 2) if we missed them, we can dive into 'why' and potentially improve the analysis so we don't miss other properties that are like them elsewhere.

@connorshank will you create a column in the master spreadsheet to flag the ones that are not in TRACTS so we can coordinate w Megan down the road?

**Comment by megrwebb** [comment]
Thanks for the context info @cschloss.

@connorshank, would you also make sure to note the geometry source like we do in TRACTS e.g. "CoreLogic Parcels - Mendocino 2018"?

**Comment by connorshank** [comment]
Workspace and location of shapefiles and tables:
N:\Projects\Atlas\PLW\Priority_properties
