### ISSUE TITLE
Pajaro -- Maps for Floodprevention Authority Meeting

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#23]
Cartography for Floodprevention Authority Meeting

For our meeting today!

Map of influences (planned transportation, HSR, urban expansion, williamson act non-renewals) over floodplain
Same as above, but with primary focus integrated assesment dropped in, and flood plain area is just highlighted.
Map of biodiversity with floodplain highlighted
Map of agriculture with floodplain highlighted

**Comment by cschloss** [comment]
Next Map Set for Abby's presentation to the SCVHA (date TBD - waiting for Abby's response)

Mapset similar to maps created for the flood prevention authority highlight compass values within the floodplain, but instead of within the floodplain, the highlited area should be the Habitat Plan Permit Area (not all overlaps with Paj watershed - so data will only show up within the paj watershed, but you can show the whole permit area

-	Whole watershed view 
-	Zoom in to show area of watershed that overlaps with Habitat Plan area (basically, Santa Clara County) and show the overlap of the Plan area on the watershed.
-	Then within that area, show the overlap of the plan area with, specifically: 
o	Floodplains
o	Agriculture 
o	Biodiversity
o	Water resources
o	Primary focus
o	Influences (start with same influences used for Flood Prevention Authority)

**Comment by cschloss** [comment]
Closing for now as the first set has been useful for other outreach meetings as well.  Can reopen if specific requests come in.

**Comment by cschloss** [comment]
From Abby - Map Request

Hello all – I just got off the phone with the Pajaro flood prevention authority, and they're hoping that we can produce a map that they can use at their upcoming board meeting this Friday. Ideally, it would show that Pajaro 100 year floodplain, the two high-speed rail alignments, and the conservation properties.

**Comment by cschloss** [comment]
Awesome Job Cori.  Thanks for the super quick turnaround and creating a really solid map.

**Comment by cschloss** [comment]
Hi Cori - from our meeting with Abby/Sasha today: 

Update floodplain web map with:

Leung  easement
Zoomed in so Morgan Hill (Coyote Valley) is at the northern extent
Legend symbology changed so not just squares
Label Coyote Valley and Soap Lake Floodplain
Add creeks/streams so they pop a little more

**Comment by cschloss** [comment]
Hi Cori

Thanks for making the time to make a map of HSR per Abby's request.  Here is here request:

"We need to show where HSRA alignments might overlap TNC fee or easement properties. Romero and Pajaro Ranch in north; I have no idea in south."

I have an email out to her checking in on some of the details, but I think this is for the full alignment and the extent may depend on how far south there are impacts to easements. Once you have an mxd prepared - we can take a look at easement overlap and see what extent makes the most sense.

Please feel free to follow up directly with Abby on size, audience, etc.  She needs them for July 10.

**Comment by cgrainger431** [comment]
I sent Abby drafts of these maps but have not heard back about edits.

The mxd is here: N:\Central_Coast\Projects\Paj\Mxds\HSR_TNCprop_overlap.mxd

**Comment by cgrainger431** [comment]
The MXD for the Upper Floodplain Map is here: -	N:\Central_Coast\Projects\Paj\Mxds\paj_UpperFloodplain_20170601.mxd
