### ISSUE TITLE
Property deal maps for brochures and WCB meeting (drafts 4/19 or 4/22)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#231]
Connor,

I just received a quick turn-around request to create REPAR (Real Estate Project Approval Routing) style maps (a.k.a deal maps) for an upcoming senior management meeting with WCB (Mike S, Jay Z, and Sharon W will be in attendance).  There are five properties, but one i.e. Chicago Valley that we've already created the deal maps.  So with four properties left, **eight maps** (one regional, one close-up aerial for each property) will be needed.  I know this is a tall order, but I would like to see what we can get done.  Are you able to help? Maybe we can split this i.e. you do the first two properties and I do the next two?

Here is part of the email from Sharon:

Hi Megan, TNC’s real estate business is heating up!!!

I’m preparing for our quarterly meeting with WCB’s senior management with Mike S, Jay and me on April 24.  Jason and I have been preparing  property brochures to present to them ahead of the meeting and we think its best to have the  REPAR type maps for these brochures

The properties are:
Pettyjohn
Mill Creek Ranch (Pfendler)
Bear Mountain
Las Piletas
Chicago Valley

**Comment by megrwebb** [comment]
If you have time to work on all of them, that would be great... but I realize a BIG ask so just let me know.

**Comment by connorshank** [comment]
Make copies of the final Sorrells (a.k.a. Chicago Valley) deal maps in N:\Mojave_Desert\Projects\Amr\Mxds to create these property maps.

CA_AmargosaRiver(Sorrells)_map1of2_20190408
CA_AmargosaRiver(Sorrells)_map2of2_20190408

For Pettyjohn Ranch place the mxds/plots here: N:\Sac_Server\Seths_drive\Maps\Yolla Bolly For Mill Creek Ranch (Pfendler), place the mxds/plots here:  N:\Central_Valley\Projects\Lsf For Bear Mountain – Tehachapi, place the mxds/plots here:  N:\South_Coast\Projects\Thp For Las Piletas Ranch, place the mxds/plots here:  N:\Central_Coast\Projects\Czo

For the regional maps, I’ve already made a copy of CA_AmargosaRiver(Sorrells)_map1of2_20190408.mxd and bookmarked some scales and extents I think will work for each property.
For the close-up aerial maps, zoom in fairly close to the property boundary.

Don’t forget to turn on/off layers to see if there is any data to show and revise some of the layer definition queries.  For hydrology, there are several options, so pick what looks best for the scale of each map.  Unfortunately, The style file for the deal maps is dated and we no longer have access to some of the fonts.  Instead, use the same fonts and styling in the Sorrells maps for these maps.  Also, you can omit the conservation areas if there are too many and they end up cluttering the maps.
