### ISSUE TITLE
Landinfo data gathering

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#232]
@connorshank, Jeanette and Dick are signing a contract with a vendor for an analyses and reporting out of conservation values found at our properties. Part of our deliverable to the contractor is to compile all the data on Box. I am away until next week so at this point, I'll just add a link the contract so you can familiarize yourself with it: https://tnc-ca.my.salesforce.com/8000c000001Qy5l

And, with a spreadsheet indicating the data that'll need to be gathered up and stored on Box. I don't (yet) have the details on format, naming conventions or anything else that's required on our side for this project. I can look into it a bit when I'm back (will send via email).

After you review the contract and spreadsheet can you provide a rough estimate of when you could work this into your schedule? Thanks Connor, Katie

**Comment by ka78** [comment]
@connorshank - echoing the email I just sent: 
Please upload the data to Box in whatever format we have it (shp, gdb, tif, grid, etc). 
Jeanette will send Box folder link. 
I uploaded the spreadsheet to the contract (link above), feel free to d/l and make notes; we can upload your version when you're done.
Thanks!

**Comment by connorshank** [comment]
Staging location:
N:\Projects\Landinfo
