### ISSUE TITLE
Property mapping/delineation for evaluation (6/28)

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#239]
Hi Conner,

I’ve received a request to map a new property and add it to TRACTs and the Atlas for evaluation.  I need help with the first part – mapping/delineating the property area (it looks like it’s a big one covering several counties) and then I’ll add it to our TRACTs dataset.
The property is N3 Cattle Ranch and it’s approx. 50,500 acres.  I’ll forward you the emails with the exhibit maps and details.
Please use current CoreLogic parcel data to select and export all parcels as one shapefile (or you might be able to use the dissolved ownership layer from the Protect Lands and Waters analysis).  Save all working and exported layers in a mxd to an appropriate folder on the N Drive based on the property location.  Send me the mxd location.  No need to dissolve the parcels into a single property boundary/area; I’ll do this as I add the property and attribute information to TRACTS.

Let me know if you have any questions.

Thanks!
Megan

**Comment by cschloss** [comment]
Connor - if you do use the PLW property shapefile - can you send me a list of the PLW IDs for the property (it will likely be several)?  I will need to go grab those after you guys map it so it would be super helpful if you pulled them while you were in there - thanks!

**Comment by connorshank** [comment]
Merged (undissolved) parcel shapefile is located here:
N:\Central_Coast\Shapes\N3_Cattle_parcels_0619.shp

The PLW ids are listed below:
SCL COID: 4126, 4127, 4128, 4129, 4130, 4134, 4135, 4136
	stateID: 533197, 533198, 533199, 533200, 533201, 533205, 533206, 533207
ALA COID: 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013
	stateID: 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014
SJ COID: 7262
	stateID: 495478
STA COID: 6468
	stateID: 587720
