### ISSUE TITLE
Update American River Headwaters map

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#25]
Hi Cori-

We have a request to update an existing map.  This map is located on the Sacramento NAS drive at this location:  "S:\TNC_SacGIS\NorthernSierra\Projects\ARH\mxds\ARH_Map5_Merchantable_Forest_NDVIgtr03_with_fires.mxd"

I have asked Jason Ando (the TIS support person in the Sac office) to set you up to access the drive.  I have to use VPN to connect to the drive, even in the SF office, but you may have better luck.  

This project was managed by Chris McColl who left 6 months ago.  He did a nice job writing up details about his projects.  I have attached his transition document that gives path locations to the data, models, etc.
[American River Headwaters-GIS data.docx](https://github.com/ka78/gd_intern/files/470610/American.River.Headwaters-GIS.data.docx)

NOTE:  It may be impossibly slow to work on the Sac NAS over VPN.  If so, lets see if we can make the edits to the map in Adobe Acrobat.  That might be a good stop gap until the new person starts in Sacramento.

Due early next week.

From: Ed Smith 
Sent: Tuesday, September 13, 2016 8:40 AM
To: Kirk R. Klausmeyer <kklausmeyer@TNC.ORG>
Cc: David Edelson <dedelson@TNC.ORG>
Subject: requested map changes for David's trip to DC next week

Hi Kirk,
David has a trip next week to advocate for our project at American River Headwaters and French Meadows. Chris produced the attached map, and we would like to make some changes to it, if you are able and willing.

1.  In the title, change the term "merchantable" to “Mature”; change in legend as well
2.  Add to the title "and fire history” and "French Meadows Project” so the title should now read, "Mature Forest and Fire History of the American River Headwaters and French Meadows Project Area”
3.  Add a light-colored vegetation layer under the displayed layers to extend into the rest of the area, but low-key visually (Sierra Nevada Mixed Conifer forest and other veg types if it’s not too busy
4. Add Frenchie or French Meadows project boundary to map and legend
5. Add locator of CA so the reader knows where it is
6. Maybe add a production date or version

I will be in the SF office for a Land Science meeting until 3 pm if you want to discuss.

How is the hiring going for Chris’ replacement?

Thanks,
Ed

Edward Smith
Forest Ecologist | 555 Capitol Mall, Suite 1290 | Sacramento, CA 95814 | (o) 916-449-2854, (c) 928-864-7113

**Comment by cgrainger431** [comment]
Hi Kirk,

I have been able to make all of the changes I think, but my connection to the Sac NAS slowed down dramatically and I have not been able to get the map to load completely.  I eventually tried to just export the map, but that ran for over an hour before shutting down Arc.  I finally got the mxd open again, but I am a little worried about being able to export the map in time.  Do you have any suggestions for getting it to export efficiently?

Thanks!
-Cori

**Comment by ka78** [comment]
Yikes.  Well, you could try the ol' shut down everything, restart, make sure you're hardwired to network (not w/Pulse).

**Comment by ka78** [comment]
I'm also trying to think if there is anyone in Sac office with ArcMap on their machine, who are also wired to the NAS, who could open the mxd and Export ... @cgrainger431 is the map totally ready to go, just needs to be exported?

**Comment by cgrainger431** [comment]
I think it is.  I haven't been able to get it to load completely since I made the last few changes, so I am not completely sure...  But they were the last changes I was going to make as long as they looked okay, so it should be pretty much set

**Comment by kklausmeyer** [comment]
Thank you guys for working on this!  This is the first time we have tried to export a big map from the SAC NAS so I was expecting some difficulties.  We should ask Jason if he can set up a machine we can remote into that is connected directly to the NAS.  I'll send him an email now to see if that is possible.

**Comment by cgrainger431** [comment]
The export finished this time, but it didn't grab all of the data.  Kirk, we can look at it in morning and hopefully the connection will be better!

**Comment by kklausmeyer** [comment]
Oh man!  So close!  I think the underlying dataset may be too large to export.  We could copy the mxd and all the data and rebuild it on the N.  That might be the most efficient/simple.  Or we could ask Jason to set up a machine for us to remote into (a better long term fix).  Or we could just edit the PDF.  I'll meet with you first thing in the morning to figure it out!

Thanks again for all your help!

**Comment by kklausmeyer** [comment]
Great work Cori!  thanks for your persistence on this one!
