### ISSUE TITLE
Development / infrastructure layer for California Coastal Area

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#27]
Create a polygon layer of development within the study area of the California Coastal Assessment (attached). Layer to be categorized by type of development or infrastructure.

[studyarea.zip](https://github.com/tnc-ca-geo/gd_intern/files/509093/studyarea.zip)

**Comment by ka78** [comment]
Hi @bcohen27 - can you please provide some context for this project for Cori?  Also, is there a particular development layer you had in mind? Or would you like her to provide you a couple of options? Also, I see this issue is labeled time sensitive, can you provide an ideal due date? Thanks, Katie

**Comment by bcohen27** [comment]
Details:

The purpose of this layer is to help us identify the type and amount of infrastructure that is or will potentially inhibit the expansion of coastal wetlands in the face of sea level rise. This data layer will be used in a variety of analytical processes and cartographic outputs.

The product that we need is a polygon layer that, for each polygon, has the attribute of what type of development or infrastructure is present. For urban areas, we would like to use the NLCD data/classification. Roads will use the esri streetmap roads. Railroads will require some data research. I will help you track down these layers, though you are welcome to do some initial research yourself to get familiar with the resources available online.

Here is the basic categorization:

1. Urban: High Intensity, Medium Intensity or Low Intensity, & Developed Open Space.
2. Roads: Buffer roads 4, 8, 10, or 12m by RoadClass (will need to evaluate this, so we can start with a pilot area)
3. Rail: Buffer Rail lines by 6m (will need to evaluate this, so we can start with a pilot area)

To this layer we want to add more detailed information about facilities along the coast, such as power plants, water treatment plants, etc. There are some layers available that will help us identify the what/where.

The desired due date for this layer is by the end of October. I will be working closely with you on this.

**Comment by kklausmeyer** [comment]
Hi all- just doing a little eves dropping here.  Cori- be sure to check with Carrie on this task. It sounds very similar to the infrastructure layer she and Eliza developed for the statewide connectivity assessment.  That would be a good place to start.

**Comment by bcohen27** [comment]
[Levees.zip](https://github.com/tnc-ca-geo/gd_intern/files/511726/Levees.zip)

Cori, here is a levee data that we will try to incorporate. Similar to roads, we should look at the imagery to get an idea of how wide these are on the ground, and then buffer the lines accordingly.

**Comment by bcohen27** [comment]
Thanks Kirk. Cori, look for CA_Resistance_Native.gdb in N:\Projects\CA_resilience\gdbs\ResistanceInputs. That seems to have a lot of good input layers (putting this in Git for consistency)

**Comment by cgrainger431** [comment]
Hi Brian,

I created a roads buffer data set, but it is too big for GitHub so I uploaded it to Box and invited you to the folder.

Here is a key of the RoadClass Attribute:
1: Primary road with limited access or interstate highway. Buffer = 12 m
2: Primary road without limited access, U.S. and state highway. Buffer = 8 m
3: Secondary and connecting road, state and county highways. Buffer = 6 m
4: Local, neighborhood, and rural road, city street OR Vehicular trail, road passable only by 4WD vehicle. Buffer = 4 m
5: Cul-de-sac OR Service drive, road that provides access to businesses, facilities, and rest areas along limited-access highway. Buffer = 4 m
6: Special road feature OR Access ramp. Buffer = 6 m
7: Traffic circle. Buffer = 4 m
Road classes 7 and 8 were ferry routes. 

I did look at the local TIGER roads shapefile in the Resistance Inputs folder on N and it had a few more streets mapped than the ESRI streetmap roads, but it didn't have any road size classifications so the more specific buffers would be difficult. I decided the more accurate buffers were worth using the ESRI streetmap roads, but I can buffer the streets from the TIGER data set that are missing in the ESRI data set and add them in.  What do you think?

I will look at the rest of the layers in the Resistance Inputs folder as well!

Best,
Cori

**Comment by cgrainger431** [comment]
Hi Brian,

Do you want me to send along layers as I make them or should I just start incorporating them into one data set?

Also for the aggregate layer of all development, would it be helpful to have a reference number to the original feature in the data set so all of the more specific information is accessible if need be?  Or is a class for development type and intensity sufficient? The NLCD and roads layers are really the only two so far that have a breakdown in intensity, but intensity is defined pretty differently for those two.  Do you have any suggestions on how to handle that, or the attributes in general?

Thanks,
Cori

PS. I got your box folder invite and will put everything in there from now on.

**Comment by bcohen27** [comment]
Hi Cori

Great questions, thanks for thinking about this. Let’s hold off on integrating the layers for right now and keep each layer separate. We (I?) still need to do a little thinking of how best to integrate the attributes and so no need to do a lot of processing that may need to be redone.

It will be good to retain source info for each layer once we integrate them, but probably not necessary to keep individual polygon ids. And since polygons will overlap, we will need to have individual fields for each source (i.e. a field named NLCD, a field named Roads, etc.), and the value of the field will be the attribute from the source (i.e. High Intensity in NLCD and 2 in Road).

Brian

**Comment by cgrainger431** [comment]
Hi Brian,

Sounds good.  I added the levee and railroads info to the box folder. Levees were buffered at 10 m and railroads were buffered at 6 m.  The railroads data set I used was from Caltrans.

**Comment by bcohen27** [comment]
Hi Cori

I am attaching a point layer for electrical generation sites. I'd like to use this layer to verify that we have the footprints for these sites in existing development data (NLCD, etc.), and if we do not, create a separate layer and add the footprint as necessary. For both existing and newly added footprints, please add an attribute that identifies the polygon(s) as "Power Plant".

There are many points in this layer that are not actually power plants, but just solar panels on roofs. If you sort the data by the attribute OP_CAP_MW you will see which ones are the large producers, and those are more likely to be power plants.

**Comment by bcohen27** [comment]
[egen.zip](https://github.com/tnc-ca-geo/gd_intern/files/516733/egen.zip)

**Comment by cgrainger431** [comment]
Okay great! I don't know if you already have a water treatment plant layer but I found this one as I was searching around.  Let me know if you think it would work.

[WaterTreatment.zip](https://github.com/tnc-ca-geo/gd_intern/files/517082/WaterTreatment.zip)

**Comment by bcohen27** [comment]
ESI data: http://response.restoration.noaa.gov/maps-and-spatial-data/download-esi-maps-and-gis-data.html#California

**Comment by cgrainger431** [comment]
Hi Brian,

Are you going to need more help with this project or should I close this issue?

**Comment by bcohen27** [comment]
Please keep it open, we will be doing QA/QC on it shortly and will need your help.

**Comment by bcohen27** [comment]
Closing this issue. May reopen a different version for QAQC part III, but this data development task is done.
