### ISSUE TITLE
Evapotranspiration Data and Visualization for Santa Clara River

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#28]
Building on the data in Google Earth Engine, a new tool is avialable to estimate the evapotranspiration of crops and native vegetation in the US.  We need this information to see if 1) invasive plants use more water than native and 2) how much water do native plants need to survive.  Both of these questions will be useful as we inform groundwater management plans statewide.  

Here is the task:  Please download 1 year (10/1/2015 to 9/30/2016) of Actual Evapotranspiration (ETA) data from the EEFlux webtool.  http://eeflux-level1.appspot.com/.  Some imagery will have clouds for our study area, so only download the non-cloudy ones.  Here is the extent I am interested, but don't worry about clouds over the ocean or over LA:  N:\Projects\Groundwater\sites\VenturaCounty\shapes\EEFlux_extent.shp

Please put the unziped grids here:  N:\Projects\Evapotranspiration\grids.  I have started with a few grids, but we may need a better naming system to include the path and row data for the landsat scene.

Only download the landsat 8 data (landsat 7 data is striped and terrible).  The grid ID starts with LC8.  Check each grid before downloading for clouds.  I have enclosed an screenshot with a lot of clouds to show what I don't want.
![cloudy](https://cloud.githubusercontent.com/assets/11560493/19172293/f97f1eec-8bd5-11e6-8cf7-5f496e373f83.JPG)

Feel free to check in with me if you have any questions!

**Comment by kklausmeyer** [comment]
I am most interested in the Agricultural zones in the lower santa clara river and the oxnard plain, so please download the landsat scene even if it cuts off other areas.  The area outlined in blue is my area of interest
![aoi](https://cloud.githubusercontent.com/assets/11560493/19172426/a6cf4478-8bd6-11e6-8966-e2e8303e3f14.JPG)

**Comment by kklausmeyer** [comment]
One more thing-  the EEFlux tool is buggy, so sometimes you just have to keep clicking on the buttons to get it to work, or leave it alone for an hour and try again.  The download is particularily buggy, so always check to see if you can unzip the downloaded file.  If not, try again!  It usually works the second time. :)

**Comment by cgrainger431** [comment]
Hey Kirk,

Looks good, I will let you know if I have any questions as I start getting into it.  When would you like this done by?

**Comment by kklausmeyer** [comment]
IT is not super urgent, but I would like to make some progress on it.  How about by 10/21?

**Comment by cgrainger431** [comment]
Hi Kirk,

Did you have more success with a particular browser when you were downloading files?  I have only gotten one file to successfully download and unzip over the last couple of days...

**Comment by kklausmeyer** [comment]
I have been using chrome and getting a better success rate. But it really varies by the day.

On Oct 11, 2016, at 10:30 AM, cgrainger431 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kirk,

Did you have more success with a particular browser when you were downloading files? I have only gotten one file to successfully download and unzip over the last couple of days...

-

**Comment by postfalk** [comment]
You might consider a download manager (which you can have as a plugin to most browsers). It would allow for continuing interrupted downloads.


Falk


______________________________________________________________________

Falk Schuetzenmeister | The Nature Conservancy | m: 1-510-604-8010 | skype: falk.schuetzenmeister
________________________________

**Comment by kklausmeyer** [comment]
Hi Cori-  now that you have downloaded most of the grids, its time to to summarize the data by the vegetation polygons.  Here is the feature class you can use:  N:\Projects\Evapotranspiration\gdbs\GDEs.gdb\pGDE_v0_3_ventura.  I think the "ID" field is a unique ID, but check for duplicates just to be sure.  Please use a python script to automate the zonal statistics command, looping through each of the grids.  You can save the scripts here:  N:\Projects\Evapotranspiration\scripts

Try organizing the output data in a "long" format. This would be a big table with the following fields:
Polygon ID, Date, Variable, Value.  For this analysis variables will be Evapotranspiration Mean, Max, Min, STD, etc.  I think that will help to summarized and visualize the data.  Let me know if you need any help with the scripting!  No major timeline, but it would be great to see some initial results in a month or so.

**Comment by cgrainger431** [comment]
Hi Kirk, 

I finally got the whole script running! The table is here: N:\Projects\Evapotranspiration\tables\compiledTables\compiledLong2_edit.csv

It's giant.... and the Unique_ID is a new field I had to create because the ID field wasn't unique to each polygon. This shapefile is the one that has the Unique_ID's to match:
N:\Projects\Evapotranspiration\gdbs\GDEs.gdb\pGDE_v0_3_ventura_copy

The script I used is called ZonalStats in the folder you mentioned above.  I could not get pandas working in IDLE for the life of me, so I ran the last conversion of the table from wide to long format in a Jupyter notebook and can give you that code too.

Let me know if you have any questions about anything or want any help with summarizing the data!

Best,
Cori

**Comment by kklausmeyer** [comment]
Great work Cori!

Can you do a few spot checks to make sure the zonal stats and the data pivot worked correctly?  I have had some trouble in the past with these steps.  I looked at some of the data and I was expecting smoother curves but there is some noise.

If the data looks accurate to you, lets move on to the visualization step.  As we discussed, here are the elements:

1. Make a table of the geography- include the xy coordiates of the centroid of the polygon and export to CSV.
2. Download Tableau Public and do a tutorial
3. Import both tables into tableau and link via the Unique ID
4. Note if the table is too large, you can drop min, max, and range variables and just focus on mean.
5. Make a map in tableau of the points that I can click on, and then it will show a chart of mean ET changes over time
6. Make a chart that shows the average ET values for all polygons by vegetation type overtime.

Thanks!

**Comment by kklausmeyer** [comment]
Thanks Cori-  the Tableau viz was really helpful to explore these data!  We sent it along to the contractor so I think we are all set for now.  I'll re-open if anything comes up.
