### ISSUE TITLE
Pajaro Web Map

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#30]
Hi Cori - 

Can you help with 2 pajaro web map items
1. Change the max scale zoom level of rangelands to match the other layers (i think 5000 instead of 500000) - you may be able to do this on AGO or this may require republishing on stratus
2. Delete the floating extra influences layer group (this might require a call to tech support)  

I can log you into my AGO account if that helps accomplish either of these items.  

I'd like to have these fixes in place by 10/26 for the Network Meeting if possible.

Thanks!

**Comment by ka78** [comment]
@cschloss @cgrainger431 you can do this in AGO; it's super quick as I remember.  
I can xfer ownership of the maps to @cgrainger431 if that makes things easier, just lmk.   
Also, @cgrainger431 we start up a tech support call together about that mystery layer; I can't recall what we found when we looked at that (think it's hosted on AGO but cannot find it?).

**Comment by cschloss** [comment]
Thanks @ka78 

Is it easy to transfer ownership (and be able to transfer it back?) That'd be great.

**Comment by ka78** [comment]
@cschloss yes easy to xfer, and xfer back.  @cgrainger431 just let me know the list of what you need xferred.

**Comment by cgrainger431** [comment]
Hi @ka78, I need access to the PajStratustestWebAppBuilder, but I can't see which web maps are linked to the app.  I think we found the supporting map when we looked at this before, but I do not remember what it is called.

**Comment by cschloss** [comment]
The supporting webmap is PajStratustest2.  Thanks all!  @ka78 @cgrainger431

**Comment by cgrainger431** [comment]
-	All data is published to Stratus from CAROGIS by theme
-	MXDs: N:\Central_Coast\Projects\Paj\Mxds\paj_greenprint_webmap\Features
-	Stratus services: GIS Servers\Stratus corinne grainger Publisher\Paj
-	Carrie owns web app: PajStratustestWebAppBuilder
-	To publish the data:
o	Add all the data you want to publish in one MXD
	Data has to be projected in WGS Web Mercator (Auxiliary Sphere)
o	When you publish a lot of data in one service, it limits the amount of changes you can make once the data is in the web map.  To avoid having to republish, make sure the following things are already set for how you want them to look in the web map:
	Symbology
	Layer names
	Layer order
