### ISSUE TITLE
Recreate cost analysis spreadsheet

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#31]
[SB88_Cost_to_government.pdf](https://github.com/tnc-ca-geo/gd_intern/files/551197/SB88_Cost_to_government.pdf)
Hi Cori-

I need to do a market analysis for the potential costs to comply with a new law that requires water diverters to measure the water they are diverting.  The state did an analysis for state and local agencies, so I want to use their method to include private diverters as well.  I would like you to re-create Table 3 in the enclosed PDF document in Excell with working formulas, so that when I change the numbers in one part, the total cost calculations are updated.  Let me know if you come up with any questions.

**Comment by cgrainger431** [comment]
Hi Kirk,

Here is the spreadsheet, let me know if you want me to change anything!

[CostAnalysis.xlsx](https://github.com/tnc-ca-geo/gd_intern/files/551716/CostAnalysis.xlsx)

**Comment by kklausmeyer** [comment]
Looks great-  just what I was hoping for!  Thanks for the quick turn around on this one!
