### ISSUE TITLE
create map to accompany birdreturns' journal article

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#34]
@cgrainger431 - this is a mapping request; here are the details:

The is for Greg Golet (birdreturns scientist).  He's submitting a manuscript for publication to ESA's Ecological Applications.  I'm sending an email with all the details...

**Comment by megrwebb** [comment]
Here are some links for format, resolution, appearance and size requirements.

General figure guidelines for initial submission: http://esajournals.onlinelibrary.wiley.com/hub/journal/10.1002/(ISSN)1939-5582/resources/author-guidelines-eap.html#Manuscript_Format

Figure requirements for accepted manuscripts: http://esajournals.onlinelibrary.wiley.com/hub/journal/10.1002/(ISSN)1939-5582/resources/author-guidelines-eap.html#Accepted_Manuscripts

**Comment by ka78** [comment]
thanks @cgrainger431
