### ISSUE TITLE
map request: distribution of UCNRS sites that TNC helped protect

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#36]
@cgrainger431 - this request comes from Lynn Lozier.  It's for her and Scott Morrison.  Due date is December 26th, but if it's done before that Lynn would love to have a look.  I'll fwd an email from Lynn outlining all the details.

**Comment by cgrainger431** [comment]
Checked in with Lynn and this is done for now, so I am going to close this issue.
