### ISSUE TITLE
Property maps for real estate deal approval/routing

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#37]
@cgrainger431, thanks for your help on this.

We’ll need two maps for the AC Growers, Inc. property: regional and aerial (zoomed to the property area).  Examples of the White/Mason regional and aerial maps are here: N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\plots

You can start with copies of the White/Mason maps:
N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\mxds\
CA_LAVentura_SantaClaraRiver(ACGrowers)_map1of2_20161130.mxd
CA_LAVentura_SantaClaraRiver(ACGrowers)_map2of2_20161130.mxd

You’ll need to:

- Update the data source for most of the layers (most should be in N:\California\data)
- Do a definition query on the TRACT layer for AC Growers, Inc.
- Pan/zoom from White/Mason to AC Growers, Inc. (it's in the same project area)
- Update where necessary (you’ll see some notes around the perimeter of the map)
- Remove or turn off old labels (some will be annotation).  Note, you may want to use some of the existing labels.
- Add new labeling (the labeling option/properties are preset, but you may want to convert to annotation within the map document for more flexibility).
- Export to PDF, 300 to 400 dpi and image quality between normal and best and save to N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\plots\

Let me know if you have any questions or trouble fitting this in.  This is a quick turnaround (the maps are needed by Friday morning), but I can help with finishing touches.

Thanks again!

**Comment by cgrainger431** [comment]
Hi Megan,

I think I have all of the changes done for the maps - they are in the plots folder.  Let me know if there is anything else you want me to change on them!

Best,
Cori

**Comment by megrwebb** [comment]
Thanks Cori.  These look great.  A couple of changes…
In general:

- You can add your name to “created by”
- Add Project Package Maps style file (link below) to confirm that the text matches the Project Package Map standards (e.g. it looks like many of the fonts switched to Arial).  This is important because it turns out these maps will be submitted for President (PRC) review which has strict standards.  I can help adding the style file, but it’s possible, you won’t have the necessary fonts.  If that is the case, I can make these changes.  Style file is here: N:\Projects\ProjectPackageMaps\New_Standards\style_files\PPM_Style_File_20110802.style
- Update source year for CPAD

For the regional, please

- Shift the “Area Enlarged” text so it doesn’t cover the extent
- Add Fillmore (town)
- Add Los Padres National Forest text and to legend
- Label other BLM shape
- To make the conservation area boundaries more apparent, create a MR buffer of the three areas shown on the map.  Save to N:\Projects\ProjectPackageMaps\New_Standards\shapes\.  I placed a buffer in your mxd that you can reference for buffer distance and use for symbology.

For the aerial, please

- Re-center the inset map to match the regional inset map and shift the “Area Enlarged” text so it doesn’t cover the extent.

Anything you can't get to today, I can complete tomorrow.  Thanks!

**Comment by cgrainger431** [comment]
Hi Megan, 

I was able to make all of the changes except the MR Buffer and adding Los Padres National Forest to the legend.

It looks like I have the project package already, but it says that the font is supposed to be Arial when I select the symbology assigned to a certain feature.  I must not have the necessary fonts...

I will be working around 8 tomorrow morning so I can finish making some of these changes then if you want!

Best,
Cori

**Comment by megrwebb** [comment]
I can make the last few changes before I send this off tomorrow.  Thanks again for getting to this so quickly, addressing the many requirements, and for doing an excellent job!
