### ISSUE TITLE
Smith Creek Ranch property maps for real estate deal routing and approval

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#40]
Hi Cori,

We need two maps for the "Smith Creek Ranch Company LTD" property: one regional and one aerial (zoomed to the property area). This property is in Nevada and you'll have to track down some data layers since we typically do little mapping outside of CA.  I'll email you with some suggestions.

These maps should be similar to the mxds you recently created for the AC Growers property on the Santa Clara River:
N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\mxds
CA_LAVentura_SantaClaraRiver(ACGrowers)_map1of2_20161130.mxd
CA_LAVentura_SantaClaraRiver(ACGrowers)_map2of2_20161130.mxd

I'd start with these, make copies, and save the new mxds in N:\Nevada\Mxds.
You will have to replace most if not all of the data, but you can use the existing layers for style reference and importing symbology.
I've added the property to our TRACTS dataset, so just do a definition query on name (i.e. Smith Creek Ranch).
The map label should be: Desatoya Range (Smith Creek Ranch Company LTD) .  I'll try to get you a copy of the deal abstract, so you know what features are important to include on the map. 

The maps are needed for routing on Friday, Jan. 6, but we should have solid drafts of these earlier in the week so there is time to make any necessary changes.  Let me know if you're unable to make this deadline. 

I'll be on vacation until Jan. 4 with limited access to email, so please make whatever progress is possible.

Thanks in advance for your help!

Megan

**Comment by cgrainger431** [comment]
Hi Megan, 

I hope you are having a great vacation.  I have put the drafts of the maps here: 
N:\Nevada\Plots\NV_DesatoyaRange(SmithCreekRanchCompany)_map1of2_20161227
N:\Nevada\Plots\NV_DesatoyaRange(SmithCreekRanchCompany)_map2of2_20161227

Let me know if there are any changes you want me to make!

Best,
Cori

**Comment by megrwebb** [comment]
Glad to hear you had a great vacation too.  I sent you an email with some changes.  Thanks again, Megan

**Comment by cgrainger431** [comment]
Hi Megan,

I replaced the old maps with the new ones in the plots folder!

Best,
Cori

**Comment by megrwebb** [comment]
Great, thanks for your work on this Cori.  As I mentioned, we often receive additional feedback during routing and review, so I'll keep this open.
