### ISSUE TITLE
Greenprint Info Hub

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#45]
Hi Cori,

Christa is creating a greenprint information hub with information on all greenprints that have been developed.  We have a webmap that will live on the hub that shows the location of each greenprint effort.  Can you be on point for completing the webmap of greenprints in U.S. for the greenprint resource hub? Work includes updating map with final greenprint list and linking points to individual greenprint pages in the resource hub. Here is the current map http://tnc.maps.arcgis.com/apps/webappviewer/index.html?id=10bc958f8b8d41bab2030137c1829c38

**Comment by cgrainger431** [comment]
Hi Carrie,

Is there anything you need me to do for this issue currently or will it be an upcoming project as more information is gathered?

**Comment by cschloss** [comment]
Yes - please reach out to Christa for the new/additional projects that need to be added to the webmap.  I think she is ready to go with the info for you.

**Comment by cgrainger431** [comment]
Okay I will send her an email.  What does the timeline on this look like?  The board meeting maps are taking up most of my time at the moment and I might not be able to get to this until next week. 

Also, should I ask Katie to transfer ownership of the app to me?

**Comment by cschloss** [comment]
Board maps are definitely the priority – I think this is near term but not with a strict deadline, prob as you have time over the next couple of weeks.  Check  with Christa on timeline though.

Yes, we’ll need to transfer ownership to you, I’ll figure out which app it is and get in touch with Katie.

**Comment by cgrainger431** [comment]
Data here: N:\USA\Projects\GreenprintInfoHub

**Comment by cgrainger431** [comment]
The ArcGIS Online web map and data should be transferred to you soon! Feature layer is called "greenprint_update," the web app is called "Greenprint Hub Map Application," and "Greenprint Hub Map."
