### ISSUE TITLE
Greenprint Data Prep

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#46]
Hi Cori - 

We have been finalizing the data layers for the Greenprint tool - some require some spatial analysis before we hand them over to Green Info Network for tool development.  I'll put a time on your calendar early next week to meet about project specifics.

**Comment by cschloss** [comment]
Hi Cori -

Next phase in this project (as you heard in the meeting today) is nailing down some of the climate layers.

For the following layers can you download from the climate commons (historic (1981-2010) both average and standard deviation, and future average (2040-2069) for these three climate models MIROC 8.5, CNRM 8.5, and CCSM4 8.5.  
1.  CWD
2.  Recharge
3.  Runoff

Could you extract by mask all 15 layers to the fishnet (make sure the fishnet is reprojected to the same projection as the climate rasters)?

**Comment by cgrainger431** [comment]
Hi Carrie,

All of the data is downloaded and clipped.  It is all in this gdb:
N:\SF_Bay_Area\Projects\BA_greenprint\BA\gdbs\GPTool\Data\BAGP_ClimateData.gdb

**Comment by cschloss** [comment]
Thanks!
