### ISSUE TITLE
RAMP (RCA) Report Figure Maps (1/17 flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#50]
Hi Cori

Bay Area RAMP is producing a report with a contractor and we are on for generating figures for the report.  This is the list of figures below.  Can you help to produce maps for this work?   This will involve producing just 1 early in the next week or so and working with the contractor on style/size etc for the document and then producing the rest by the week of March 20th.

GitHub doesn't like the table of figures/maps and data for each  that I'm trying to upload so I will send via email.  Let me know if this is a project you can take on!

Thanks,
Carrie

**Comment by cgrainger431** [comment]
Two rounds of draft maps have been submitted. Still waiting for the data to make maps 2-8 through 2-15.  

Carrie, do you know when the next round of maps are due?

**Comment by cschloss** [comment]
We are still waiting on data from GIN.  

However, I just did a first round of text/revisions on the  BACA/RCA and there will likely be a few map updates that will probably come from Jodi early next week.

**Comment by cschloss** [comment]
Hi Cori - Jodi asked me to work with you directly on some of the map comments I put in the RCA doc.  I will copy them here and feel free to follow up with me on whatever is not clear:

One overall question is - what is the size of the map layout you are using?  

Vegetation types:
Its super hard to show all the veg types with unique colors, I’m wondering though if a few tweaks could really help with communication here – for example hardwood forest is in reds whereas conifer forest is in greens, maybe all forests need to be in more similar colors – and vineyards and rice which are somewhat in the green spectrum can be more disparate.

Mitigation Supply:
Pending response from Patrick, may need to change legend to Hectares.

Prior plans:
 the break %'s aren't intuitive can you use manual/even breaks so they are at rounded numbers (maybe every 20% or every 15%) 

Connectivity:
I'm curious about why we are using essential connectivity areas instead of just BACL - is this based off of Jodi's rec?  If so I'll follow up with her, if not, can we remove it?

Watersheds and Hydrology:
-In the legend the outline of the HUC10 and the streams are very close in color – might be good to change the color for the border  of the HUC10s, also the stream lines are hard to see – could be good to darken or thicken.
-Also – roads are good for context, but because this is map of hydrologic features, those should be the features that pop the most with the highways falling back, hard to see water bodies too – maybe need to make this feature pop out more against the HUC10
-And the order of the legend should reflect the main features in the map on top – streams and water bodies on top, then watersheds, then context layers

**Comment by cgrainger431** [comment]
Hi Carrie -

The map layout is 8.5 by 11.  Is that what you want it as or should I change it?

The updated maps are here: N:\SF_Bay_Area\Projects\RAMP\RAMP_Report\plots\Updates_20170405

They are: 2_3_update (watersheds), 2_6_update (veg types), 2_8_update (connectivity), 2_18_update (prior plans). Let me know if you have any additional changes for these maps.

Also, let me know if I should change the mitigation supply legend units.

**Comment by cgrainger431** [comment]
Final maps are here: N:\SF_Bay_Area\Projects\RAMP\RAMP_Report\plots\Finals

MXDs are here: N:\SF_Bay_Area\Projects\RAMP\RAMP_Report\mxds

**Comment by connorshank** [comment]
Jpeg has been created for the requested data, named RAMP_2_19.   The mxd and jpeg are located in the locations listed above.

**Comment by cschloss** [comment]
Looks great! Thanks Connor
