### ISSUE TITLE
Cosumnes watershed maps for tour/flyover

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#54]
Cori,

A group of folks are flying over the Cosumnes watershed this Thursday and there is a request for several maps to help inform what is being viewed. They will be using the Avenza Map app to track their location on PDF maps.  In addition, there is a need for hard copies.  Details are being finalized, but it looks like three poster-size maps will be needed showing the entire Cosumnes watershed, lower Cosumnes and middle Cosumnes.  Each will have highlighted places/properties over aerial imagery.  Drafts will be due EOD Tuesday or early Wednesday and finals by EOD Wednesday.  It’s a quick turnaround, but these can be simple.  Do you have time to work on this?  Let me know and if so I’ll send you the details.

Thanks,
Megan

**Comment by cgrainger431** [comment]
Hi Megan,

I am so sorry but I don't think I have time to fit this in this week.

**Comment by megrwebb** [comment]
Ok, thanks for letting me know.
