### ISSUE TITLE
Land Swap Map for San Diego Project

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#57]
Here is the email from Cara.  Deadline Friday.  Brian to help with data layer locations if needed

"Hi Kirk and Cori,

Thank  you again very much for taking this on.

Attached you will find two maps that outline the parcels owned by GDCI.  The third map is discussed in bullet 3.  

The first map is the clearest.  The areas that are not hatched within the boxes are the developable areas and the areas within the hatched areas are not developable or are part of the PAMA – Pre Approvevd Mitigation Areas under the South SD County MSCP.

Could you please create the following information

1)	Define the entire number of acres owned by GDCI in GIS – gross and developable – so not hatched within the yellow outline and hatched (preserved) within the yellow outline.

2)	Label each yellow box area with gross acreage and developable acreage so we know the amount of each within each parcel
a.	So in each Parcel, can you please calculate the amount of acreage that is developable – so net and the gross acreage of each yellow parcel?
b.	In some cases there is no developable acreage within the yellow box, but could you please label the acres in that area anyway?  
3)	We will then take this map and determine if/where there are other areas that make more sense for development – we have a rough estimate that is the 3rd map for a potential swap.  If possible, could you take the areas we think could be swapped and calculate those acreages as well?  These are outlined in orange.

Thank you so much!  Deadline is Friday Morning.  If any of this is at all confusing feel free to call me.

Cara"

**Comment by cgrainger431** [comment]
The initial maps were completed and a second set of maps were sent to Cara on Monday.  She did not mention needing any additional help at this time; should I close this issue for now?

**Comment by bcohen27** [comment]
Yes, go ahead and close. Thanks for doing the great work.
