### ISSUE TITLE
Las Possas Surface Water and Ground Water Monthly Summary

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#58]
Hi Cori, 

I need some help with d/l and organizing surface water data for Las Possas study area. I already have the ground water data but need help with surface water. I have created a workflow document with link to the dataset and main tasks. Here is the link to google drive with the dataset. 

https://drive.google.com/open?id=0B_okb3ppkxGcYkhrZnpfTHZXSHM

TASK --- 

1.	From  above links (see this document)  download Average Daily Flow and create monthly summary for June, July, Aug and Sept using the template in the folder

2.    From the ground water wells file identify the well that correspond to the above surface water wells. 

3.    From the corresponding ground water wells go to each well (each sheet) and create summary of monthly averages for above months against each corresponding well in the above template

Not sure what your work load is Cori. But if I can get task 1 completed and the ground water wells identified by end of this week that will be great. If all task is completed in 2 weeks that would be terrific. 

Let me know if you have questions. 

Thanks
Tanu

**Comment by kklausmeyer** [comment]
Hi Cori and Tanu-

I added a map that Jordan Kear produced to Tanu's google drive folder.  It shows the location of all the GW wells.  Note that Jordan uses an abbreviation method when referring to the wells that I don't care for because it is not consistent.  For example:  "02N19W05K001S" becomes "5K1" and "02N20W12MMW2" becomes "MW2".  You will see this in the map and in the excel file.  I think we should use the full ID.  Cori, let me know if you want Jordan's well shapefiles and I will have Sally request them.

Kirk

**Comment by cgrainger431** [comment]
Hi Kirk and Tanu,

I finished the monthly summaries (June, July, Aug, Sept) for the stream gages.  Should I send you the spreadsheet, put it in the google drive folder, or put it on N?

Do we have shapefiles of the stream gages? Also, is the well data in the map from Jordan new data or is it data I passed along to him?  It could be helpful to have the GDE reference points he used though, so we use the same ones if they work with the stream gages. 

Thanks!
-Cori

**Comment by TB2016** [comment]
Hi Cori, this is great. Upload the file on Google Drive. There is only ONE well data that corresponds to this surface flow data gages. But it will be good to extract the GDE for this area. Lets quickly connect on skype. Thanks Tanu

**Comment by kklausmeyer** [comment]
Thanks Cori!  I just asked Jordan for the shapefile of the well locations and GDE reference points.  I think the Google Drive folder is the best place for the data.  But can you also put a copy here:  N:\Projects\Groundwater\sites\VenturaCounty\tables

Thanks!

Kirk

**Comment by TB2016** [comment]
Kirk, I am thinking we should pull out the temporal trend in NDVI and NDMI from these GDEs (that I have already summarized for the ventura study area) and see how they compare to each other. This will be polygon level summary of NDVI and NDMI. We  might eventually need to get to just pixel level summary within each GDE but for now even looking at GDE polygons will be great. I will send the file over to Cori.. after quick chat with her on skype. Tanu

**Comment by cgrainger431** [comment]
Okay it is in the google drive!

**Comment by kklausmeyer** [comment]
Cori, I don't think there is a shapefile for the stream gages.  Could you make one based on the lat long data provided on the stream gage website?

**Comment by TB2016** [comment]
Cori -- I am adding you the ventura Google drive as well, where you can find the GDE shape file with NDVI and NDMI information. Here is the link to task we need to do once you have identified the well and stream gage locations.  https://docs.google.com/document/d/1bwKqX4Hb9q4IXCJAm9OUUEmUBtsSOA9QpX8kaKSszbY/edit?usp=sharing

**Comment by TB2016** [comment]
Thank you Cori, for creating the annual summaries from well and gages. I am closing this task for now.
