### ISSUE TITLE
Create Carpenter Valley property maps for CA BoT board book

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#60]
Cori -
This is similar to the El Toro Ranch property maps request with one difference being that we want current parcels shown with APNs on the aerial map.  The aerial map should be created first, then the regional one if time permits.  The regional map would need to show other properties in the vicinity that TNC has helped to conserve, including Independence Lake, Webber Lake/Lacey Meadows, Royal Gorge, the Ranz easement, and the American River Headwaters.  It will probably be best to only show the TNC conservation area(s) that intersect this property due to the map extent.

With minimal changes, you should be able to repurpose the maps created for an adjoining property.
N:\Sierra_Nevada\Projects\NSP_CC\MXDs\
CA_NorthernSierra_Sagehen_CarpenterValley(McClatchyandWillis)_map1of2_20160512
CA_NorthernSierra_Sagehen_CarpenterValley(McClatchyandWillis)_map2of2_20160512

Let me know if you are able to help with this request too.  If not, I'll find time to take this one on.

Thanks,
Megan

**Comment by cgrainger431** [comment]
Hi Megan,

I can probably make time to create the El Toro maps, but I am not sure about these two.  Will most of the pieces be the same (labeling etc) as the McClatchy & Willis maps, and it is just changing/labeling the parcels and making sure the correct surrounding properties are shown?

**Comment by megrwebb** [comment]
Ok, that would be great if you could do the El Toro Ranch maps.  El Toro is near Mt. Hamilton and not Santa Clara River, so you will need to create new labels, but you will be starting from two current mxds without any broken data links.  For text placement and flexibility, please convert and store the annotation within the current extent of the map.   Let me know if you need any help with working with annotation layers.

The Carpenter Valley regional map will need a new map extent and scale to include the properties mentioned above and will require creating new labels and adjusting the scale of the current annotation layers.  The aerial map will need to be re-centered and include parcel boundaries and APN labels. Both are old mxds so I expect there will be some broken data links.   If you think you'll be pressed for time, I'll do Carpenter Valley.

**Comment by cgrainger431** [comment]
Hi Megan,

I don't think I will have time to do the Carpenter Valley map but I will do the El Toro maps.

Best,
Cori

**Comment by megrwebb** [comment]
Great!  Thanks.
