### ISSUE TITLE
Create a new map of the Singh Bidwell Restoration Community, Sacramento River for Ryan Luster

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#61]
Cori, 

Ryan Luster at Chico wants to revise a map that was created many years back by TNC Geodesign. I could not locate any data associated with the old map. So I think we will have to create a new map. 

DATA 

1. We have a KMZ on google earth to start with, which is located here (https://drive.google.com/open?id=0B_okb3ppkxGcZFR2Ym5Qa2JIYjQ)

2. Old map is located here [https://drive.google.com/open?id=0B_okb3ppkxGcSzIxM2pHR1dIMmc]

TASK -- 
1. Convert KMZ to shapefile in Arcmap 
2. Load high resolution NAIP data for California. See if you can find 2007 NAIP, I believe thats the NAIP underneath the old version of the map
3. Create a new map from scratch with 6 polygons (including the outside boundary) as shown in the OLD map above
4. Increase the width of the Grassland polygon such that width is 200  ft
5. Increase the area of the Flow polygon to 4 acres expanding on east - west. 
6. Create 2 line features as shown in the OLD map
7. Create a KMZ of the final map
8. Create a final map to send to Ryan Luster

COMPLETION TIME -- next week (April 28th or 1st week of May latest).

**Comment by megrwebb** [comment]
Sorry for butting in here, but for the property boundary I would use TNC Interests (this is a TNC historic property) or county parcels, rather than this KMZ shape.  Typically, county parcels, PLSS lines, survey maps and/or legal descriptions are our primary sources for property boundaries.

**Comment by TB2016** [comment]
Thanks for suggesting Megan. Cori, did you see this ?
