### ISSUE TITLE
Otay to Santa Ana Connected Lands Plan Maps

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#64]
Cara and team have a list of maps that are needed to populate a powerpoint and Word doc for the Otay to Santa Ana Connected Lands Plan (OSAN). Many of the maps are built on the same basemap with additional layers added and others turned off.

Brian will work with Cori to supply or point to relevant data sources. Attached here is a blank .mxd that has a bookmark for the mapping extent.

The Excel file is also posted on Box for interactive team use: https://tnc.box.com/shared/static/wdeqfe01mrbqmz93by28idx7c7rj4ru5.xlsx

[Exhibits for Otay to Santa Ana.xlsx](https://github.com/tnc-ca-geo/gd_intern/files/959457/Exhibits.for.Otay.to.Santa.Ana.xlsx)

[OSAN_extent.zip](https://github.com/tnc-ca-geo/gd_intern/files/959459/OSAN_extent.zip)

**Comment by cgrainger431** [comment]
Hi Brian,

Can we set up a call about this when you are ready to go over some background and talk about which maps you would like me complete?

Thanks!
-Cori

**Comment by bcohen27** [comment]
Certainly. I have also updated the spreadsheet to indicate which maps to work on (has Cori /). We’ll focus on the ones with the due date of May 5th.

**Comment by cgrainger431** [comment]
Map package and documentation sent to Brian.

Data is on N here: N:\South_Coast\Projects\Sdo\Projects\OSAN

Plots, Data and Map information on Box here: https://tnc.box.com/s/twng430xmz91dn1dykrvsc7oy5u2cdbn
