### ISSUE TITLE
Download and assemble 2016 Tiger/Line road data for California

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#65]
Hi Cori,
We’ve been needing an updated road layer for California. One of our best sources is Tiger/Line road data, but our last vintage is from 2008.  If you could download and assemble the recent 2016 vintage, it would better serve many projects.  Let me know if you have time for this and if you have any questions. 
Thanks!
Megan

To download and assemble 2016 Tiger/Line road data for California:

1. From the US Census Bureau website (https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2016&layergroup=Roads)
- Download primary and secondary roads (a.k.a. major roads) for California.
- Download all roads (a.k.a. local roads) by county for all of California.  Unfortunately, they only do this by county so you will need to download 58 separate zip files.

2. Create a “CA_Tiger_Roads_2016” folder in N:\California\shapes
-Unzip road data and create sub-folder directory by county for all “local” roads.

3. Merge all CA county “local”” roads into one statewide dataset and place in N:\California\data\infrastructure\transportation.gdb.
-Use established naming convention (i.e. CA_ROADS_LOCAL_TIGER_2016).

4. Import “major” roads to same gdb and name “CA_ROADS_MAJOR_TIGER_2016”.

**Comment by cgrainger431** [comment]
Hi Megan - yes, I should have time to do this. I will let you know if I have any questions along the way!

**Comment by cgrainger431** [comment]
Hi Megan, the new Tiger shapefiles are on N in the folders/gdbs you specified above!
