### ISSUE TITLE
Maps for March, 25, 2017 Board Meeting

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#66]
Board meeting time!  The water program is presenting.  I will take the lead on generating the maps, but I would love to have Cori and perhaps Megan's help to refine the maps, make them look good, and handle the minor edits from the team.

So far it looks like two primary maps in two formats (powerpoint and half page printed), so 4 maps total.  Here is the email chain to date:

FROM SANDI--

Hey Kirk,

Thanks for being ready to rally. Here is more info:
•	No ppt template yet. Go ahead and plan for a full slide for the map.
•	Map 1: Groundwater Market Opportunity
o	The goal of the map is to show the scale of the opportunity for groundwater markets to benefit GDEs and interconnected surface waters across the state; and what portion of that is regulated under SGMA, which is a key enabling condition. There are therefore two components: 1) showing GDEs and ISWs (or rivers as a proxy); 2) an overlay of that shows how much of the GDEs and ISW will benefit from SGMA regulation.
•	Map 2: The Fox Canyon Groundwater Market
o	I’d also like for the Fox Canyon map to show Fox Canyon GMA relative to Ventura County and the Santa Clara River Watershed. The point of this map is to 1) help locate Fox Canyon and show the scale of the basin; 2) to show how the jurisdictions inter-relate. This is intended to set up a discussion on what the right scale of markets should be: should it be watershed scale, county scale, basin scale? Is it different for a gw-only market vs. an integrated gw-sw market?

If you want to talk this through a bit, I’m mostly reachable today and tomorrow: 805.746.6664. 

Thx,
Sandi

________________________________________
 
Sandi Matsumoto
Associate Director
CA Water Program
smatsumoto@tnc.org
(916) 596-6671
(805) 746-6664 (Mobile) 
(916) 442-2377 (Fax)	    	 
The Nature Conservancy
555 Capitol Mall, Suite 1290
Sacramento, CA 95814
 
nature.org

	     	 

From: Kirk Klausmeyer <kklausmeyer@TNC.ORG>
Date: Friday, April 28, 2017 at 5:00 PM
To: Sandi Matsumoto <smatsumoto@TNC.ORG>
Cc: "E. Remson" <eremson@TNC.ORG>, Jeanette Howard <jeanette_howard@TNC.ORG>, Cat Burns <cburns@TNC.ORG>, Brian Stranko <bstranko@TNC.ORG>
Subject: RE: Map of Fox Canyon

Sandi-  thanks for the heads up!  I am happy to help out with this.  But I need a little more info for you:
 
-	Do you have a template for the powerpoint?  If so, should I fit the map to the full slide or leave room for a border?  Can you send me a copy of the template?
-	For the two maps below, please send me and idea of what you want the main point of the map to illustrate.  For fox canyon, do you want to show where it is on the planet?  TNC properties?  Groundwater wells?  Even if you can think of a title for the maps, that helps me figure out what to highlight.  
 
From: Sandi Matsumoto 
Sent: Friday, April 28, 2017 4:14 PM
To: Kirk R. Klausmeyer <kklausmeyer@TNC.ORG>
Cc: E.J. Remson <eremson@TNC.ORG>; Jeanette K. Howard <jeanette_howard@TNC.ORG>; Catherine Burns <cburns@TNC.ORG>; Brian Stranko <bstranko@TNC.ORG>
Subject: BoT: Map of Fox Canyon
 
Hey Kirk,
 
We’re heading deep into Board prep for the May 25th meeting. Topic is water trusts, with breakout sessions on groundwater markets (focus on Fox Canyon) and Central Valley Water Sharing iNvestment Partnership.
 
Nearest term deadline is a write-up on the break-out sessions, due next Thursday, including maps.
 
For the groundwater session, I think we’ll need 2 maps: 1) Fox Canyon; and 2) all SGMA regulated basins. We’ll need these in a format consistent w/ the other maps being requested for the meeting from Cat and/or Brian.
 
I’m not sure what the timeline is for the presentations. I’ll keep you posted and let you know if we anticipate needing additional visuals for this.
 
Thx,
Sandi
 
________________________________________
 
Sandi Matsumoto
Associate Director
CA Water Program
smatsumoto@tnc.org
(916) 596-6671
(805) 746-6664 (Mobile) 
(916) 442-2377 (Fax)	    	 
The Nature Conservancy
555 Capitol Mall, Suite 1290
Sacramento, CA 95814
 
nature.org

**Comment by kklausmeyer** [comment]
I will lay out the basic content of the maps and then include Cori in the all the email traffic.

**Comment by kklausmeyer** [comment]
One more thing from Sandi:
Hey Kirk,

One more thing on the maps: they’ll be used in 2 ways. 1) in the presentation; 2) in a one-page write up. For the write up, I’m envisioning a single page for the maps with one on the upper half and the other on the bottom half. Text would be on the reverse side.

Thx,
Sandi

**Comment by kklausmeyer** [comment]
So now it looks like we are doing two slides for the board meeting- groundwater and freshwater.  

Groundwater:
Basic mxd:  N:\Projects\Groundwater\mxds\Board_Map_20170509.mxd
Excel file with chart: N:\Projects\Groundwater\tables\pGDE_v0_4_basins_sum.xlsx
PPT slide:  N:\Projects\Groundwater\admin\Board_Pres_20170509.pptx
Tasks:
1. Send Sandi a list of the basins that are in the "focal" category and also grouped by the color breaks in the map
2. Make the map look better

Freshwater:
MXD: N:\Projects\CA_FWA\mxds\BoardPres_FW_20170509_Cori.mxd
slide: N:\Projects\CA_FWA\admin\Board_Pres_slide_20170510.pptx
Table: N:\Projects\CA_FWA\tables\RWRI_AU.xlsx

Tasks:  
1. Work with Cat on the methods
2. Make the map look better once Cat responds

**Comment by cgrainger431** [comment]
Hi Kirk - can I close this issue?

**Comment by kklausmeyer** [comment]
Yes please do! ☺
