### ISSUE TITLE
Update WSIP map  - Board Meeting May 25, 2017

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#68]
Hi Cori --- 

I just created two WSIP maps for Jennae and the water team.  I don't think there will be any urgent work needed for this. I am just creating this task so that you can make all the BOARD MEETING specific maps look similar and give them the shine it needs. I will upload the dataset in GDRIVE so that you can update them.  

The only thing that might need some tweaking is 'stream/river' layer. 
Thanks
Tanu

**Comment by cgrainger431** [comment]
Hi Tanu - can I close this issue?

**Comment by TB2016** [comment]
yes, absolutely...Thanks a lot Cori..
