### ISSUE TITLE
birdreturns map sets

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#7]
a series of maps will be needed throughout the summer for the birdreturns program, 1 by next Tuesday 8/9 and 1 a week to 10 days after that (I'll update with a due date when I get it).

1. birdreturns is about to begin its Fall 2016 season, and contracts are being drafted.  A map is required to accompany each contract, showing simply the outline/location of the enrolled fields.  I'll attach a previous years' map as an example.  using Data Driven Pages in arcmap is a simple way to create a map template and generate  a set of maps.  

SHP of final boundaries:  birdReturns\2016_Fall_Rice\bids\br_allBids_fall16.shp

Bid ID: take from data
Program Option: take from data
title: Migratory Bird Auction - Monitoring Program Fall 2016 (check title with julia barfield @ka78)
other copy sample map
Also: growers should see only data that they own, not neighbors data

2. same as above but this will be a series show the compliance stakes that have been place at the enrolled fields, for each contract.  compliance stakes are being set in the ground now by the field crew.  There are five programs this summer: AugB, SepA, SepB, OctA and OctB.  The maps for AugB should be ready by 8/11, stay tuned. I'll write a post further down with a better idea of these timelines.

@cgrainger431, both map sets can be placed in Box > bird returns > maps > 2016 Fall contract maps\
@cgrainger431, see if this gets sent to your tnc email address... lmk.

**Comment by ka78** [comment]
@cgrainger431 , would you be able create Sept B compliance maps for Julia for 034 and 094?  There will two more Sept B maps needed, but they had a late harvest so Simon and crew haven’t been able to set stakes yet.  Let me know if you can work this in, thanks.

**Comment by cgrainger431** [comment]
Yes I can! I will have them done by the end of the day.

**Comment by cgrainger431** [comment]
Hi Katie,

It doesn't look like Bid 34 is in the September B program, did you mean 033?

**Comment by ka78** [comment]
Hmm, Julia sent me those numbers, I'll ask her... one sec.

**Comment by ka78** [comment]
Updating this with a note that October A is complete - October B is next, then we're done!

**Comment by ka78** [comment]
I see Oct B is finished - thanks - we're done for Fall :)
