### ISSUE TITLE
Rutherford Ranch Phase III property maps for real estate deal routing and approval

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#71]
Hi Cori,

These maps are needed for routing a preliminary deal abstract and will be similar to the maps you've created for other properties (with a couple of additions).  We are finalizing the property boundary now, but I should have full details by tomorrow 5/26.  These are needed as soon as possible, but realistically I'm hoping to have the maps completed sometime mid-late next week.  Let me know if you are able to help out with this request.

Thanks,
Megan

**Comment by cgrainger431** [comment]
Hi Megan - Yes, I should be able to help you with this request.  Let me know when you have all of the details!

**Comment by megrwebb** [comment]
That’s great, thanks Cori.

Go ahead and make copies of the mxds below to start with since they will have the most up-to-date data sources and styling for the deal maps.

N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\mxds\CA_LAVentura_SantaClaraRiver(LanaiInvestorsLLC)_map1of2_20170419.mxd
N:\South_Coast\Projects\Lav\Sites\Santa_Clara_River\mxds\CA_LAVentura_SantaClaraRiver(LanaiInvestorsLLC)_map2of2_20170419.mxd

Of course, you will need to update the map extents for this property.  In TNC TRACTS, the property TRACTNAME = Rutherford Ranch Phase III.  Follow the same guidelines as in previous deal maps.

Change the map title to:
Santa Ysabel/Julian (Rutherford Ranch Phase III)
San Diego County, CA – South Coast Ecoregion

Save the map files here:
N:\South_Coast\Projects\Sdo\Mxds

and name as

CA_SanDiego_SantaYsabel_Julian(Rutherford Ranch Phase III)_map1of2_20170526 (a.k.a. the regional map)
CA_SanDiego_SantaYsabel_Julian(Rutherford Ranch Phase III)_map2of2_20170526 (a.k.a. the aerial map)

The project lead would also like an aerial map showing both assessor parcels and legal boundaries with labels.  Due to the large size of the property, I don’t think this will be legible on a page size map.  For this request, take the aerial map you’ve created and make a 11 x17 version.  I’m hoping this size will work.

The parcels are here:
N:\South_Coast\Projects\Sdo\Shapes\sdo_Rutherford_Ranch_Phase_III_CoreLogic_Parcels_2016.shp

The document showing the legal boundaries is here:
 N:\South_Coast\Projects\Sdo\Plots\sdo_Rutherford_Ranch_survey.pdf

Use the parcel shapefile to create a new legal parcel dataset (i.e. dissolve by parcels and create a new column with legal parcel names).  You can save this in N:\South_Coast\Projects\Sdo\Shapes\ with a similar name as the parcel shapefile.

Let me know if you have questions, need help, etc.

Thanks again,
Megan

**Comment by megrwebb** [comment]
Thanks for you help with these!
