### ISSUE TITLE
HSR - floodplain protection data package and send

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#76]
Hi Cori – your maps of HSRA are making the rounds.

For the new easements you added this map, can you merge them to the  CCED and package up (and if there are new protected areas you used can you merge those with the CPAD and package that up too) and forward to Abby/Liz?

**Comment by cgrainger431** [comment]
Data here: N:\Central_Coast\Projects\Paj\Shapes\CCED_wAdditionalPajaroFloodplainEasements20170630.shp
