### ISSUE TITLE
Birdreturns -- create maps for Oct A contracts (9/26)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#79]
Every Birdreturns contract requires a map showing the fields under contract. Using data driven pages, create a map for each October B contract; see example mxd in N:\WATER_Program\birdreturns\2017_Fall\contractMaps

The Aug B have already been done; Katie will let you know when the Sep A and Oct A maps are due (Sep A probably due your first week, or second week).  Oct A maps will be due later, prob in mid-September.

**Comment by ka78** [comment]
update: Julia requests the wording on each map to be like this:
Exhibit A
TNC BirdReturns Program Fall 2017, August B
Bid ID: 17-FR-102

**Comment by ka78** [comment]
@connorshank - I did the SepA maps on Monday, but I'll have you do the OctB maps; this is a short task should take roughly an hour (if you haven't worked with data driven pages before). Not due till mid/late September.

**Comment by connorshank** [comment]
OctA maps have been exported to the following folder in pdf format:
N:\WATER_Program\birdreturns\2017_Fall\contractMaps\OctA

**Comment by ka78** [comment]
thanks @connorshank - I added the maps to the Box folders Julia linked us to. closing this.
