### ISSUE TITLE
Add critically overdrafted groundwater basins to webmap (8/31 flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#80]
This need is adding a data layer to our rangeland prioritization web application. Needed by End of Aug.
Step will be to publish the data layer, add to webmap, and configure.

**Comment by TB2016** [comment]
Carrie and Kirk, I am adding myself to this thread since the Ag team needs this dataset as well for San Joaquin Valley. Feel free to untag yourself if it just clutters your email or task list. 

Cheers
Tanu

**Comment by connorshank** [comment]
Saved the updated groundwater layer in an mxd file in the following location:
N:\Projects\Groundwater\mxds\GWB_criticaloverdraft_Connor_8_31_2017.mxd

added a field for Critical_Overdraft where 1 signifies CO and 0 signifies none

**Comment by connorshank** [comment]
The new layer has been successfully added to the webmap, let me know if everything looks alright.

**Comment by cschloss** [comment]
Hi Connor - good work on you first publishing task!

Can you make 2 small adjustments
- change the layer order so this new layer is just above the SGMA basins 
- make the default to be checked-off so it is not displaying initially on load.

Thanks - once those two changes are made I'll close the issue!

**Comment by connorshank** [comment]
For some reason I cannot move that particular up or down in the list, even when I open the 'more options' tab, the up and down arrows are greyed out.

**Comment by cschloss** [comment]
In the web-app or in the webmap? You might be able to move it in the webmap even if not in the web app.

Also - if you can't put it above sgma (which if that was published as a single service with the others you might not be able to, it would be ok to put it below sgma at the bottom).

Let me know if that works and if not we can take a look at it together tomorrow.

**Comment by connorshank** [comment]
It's in the webmap, seems kind of odd, but if you've got time tomorrow afternoon I'm happy to tackle it then.
