### ISSUE TITLE
Make Corrections to Final Maps for Strategic Retirement (9/20)

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#82]
Connor, I will update you on the tasks associated with this as we start working together.

**Comment by TB2016** [comment]
Locate in hard disk the following Arcmap : C/Agriculture/FallowingRegionalAnalysis_8thJune_2017
In the mxd : 
Map 1 = Potential Habitat
Map2 = HbtOvlp_Agland_Tier1.tif
Map 3 = Hbtovlp_agland_T1_PA5km.tif  -- -this map needs to be updated and redo calculations

**If, TB already did this analysis then familiarize with this mxd and dataset to create a webmap.**

1.	D/l new PA layer sent by TB from here 
https://drive.google.com/drive/folders/0B_okb3ppkxGcS3ZtR1BJU2dLZFE?usp=sharing
2.	Clip HbtOvlp_Agland_Tier1.tif  with the new_PA layer  to create Map3
3.	Update Map1, Map2 and Map 3 with new class (PA_within_5km) from the new_PA layer
4.	Calculate Acres under class PA_within_5km for Map from Map 1 , Map2 and Map3 
5.	Reclass Fallowing (fallowYrs.tif) : ONCE and More than Once
6.	Create new maps overlaying new_FALLOW on Map 1, Map2 and Map3
7.	Calculate Acres under new_FALLOW from Map1, Map2 and Map3
8.	Create new map with ONLY Annual_Crop (Crop_Annual_Perenial.tif) overlaid on Map1 , Map2 and Map3 
9.	Calculate Acres under Annual Crop for Map1, Map2 and Map3

Additional datasets to include in the webmap:

![image](https://user-images.githubusercontent.com/17483557/29793600-4ea6741e-8bf9-11e7-987c-9b7d10b32610.png)

**Comment by TB2016** [comment]
The above analysis is completed.

**Comment by TB2016** [comment]
1. Orient yourself with the power point for strategic fallowing with Final Maps.
https://tnc.box.com/s/yx36bjf7wj8006a62png8i3p2x8vv7dj

2. Datasets that went into the map are here or in the hard disk
https://tnc.box.com/s/4stk5ss5dvwj6rfwz09dzv5plmxoy58t

3. Link to Final  mxd 
https://tnc.box.com/s/hzlsk0bgxh21nqcyhkefkbiymvid1wfd

**Comment by ka78** [comment]
Hi @TB2016 what's the ideal due date here? I'm helping Connor plan his September schedule given his task list so far + staff retreat + the Board meeting priority... thanks. Also, is this an internal (flexible if needed) due date or a hard deadline.

**Comment by TB2016** [comment]
@Katie -- deadline in Sept 20th, internal hard deadline, Product to be
delivered to Scott Butterfield and Abby. I did mention them about staff
retreat etc., this is the date they agreed to..

Thanks
Tanu

**Comment by TB2016** [comment]
Morning Connor, 

I sent the partners the slides and maps. You can put this back in your inventory until we get some feedbacks from them, for next round of maps. 

Thanks
Tanu

@ka78 
@connorshank

**Comment by TB2016** [comment]
I am just closing this. I will be completing this myself.

**Comment by TB2016** [comment]
Connor, 

I am re-opening this issue. The final maps are completed and uploaded on box. I am waiting to hear from rest of the team to know if they want a webmap or not. 

For now the task is to d/l everything from BOX and put it on N Driver here 
N:\Projects\Agriculture\projects\Fallowing

BOX Link : https://tnc.box.com/s/zo2x7q44ul12aqa2eoh2tje3bsu13lc2


Move the existing folders in above path as "Archive" before you d/l the box folder below. 
After you copy the folders from BOX to N Drive, 
Copy both the mxd from the mxd folder and place it directly under FALLOWING folder. 
Open both the mxd's and hopefully all the paths will be mapped. 
If not RE-MAP the paths. 

There is also a MapPackage within the MapPackage folder.  Open that as well. 
Some datasets (e.g, county, NASA Fallowing might not be in mapped). Make a list of the missing data layers. I have the main datasets on BOX too. We can d/l it from the main data folders after you have mapped above mxd's. 

Once we have all the datasets, create a .gdb of all the layers (WAIT TILL YOU DO THIS).
Thanks
Tanu

**Comment by TB2016** [comment]
Connor - Check the folder paths for FALLOWINGSUITABILITY_Calculations.mxd FIRST. 

The other two mxd's are a copy of above mxd without the Inset dataframe for California and just the layers for the whitepaper, which I created for making MapPackages. I think if you map the paths to above mxd, we should be good. 

Thanks
Tanu
