### ISSUE TITLE
Update the new SAGBI output from FALL 2017 with Water Districts

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#83]
Update Bids Submitted and Accepted in FALL 2017 with District and ownership information for Julia. Deadline Sept end.

**Comment by ka78** [comment]
@TB2016, to clarify, are you asking that the master fields layer be updated to include a column indicating which district it falls within?

**Comment by TB2016** [comment]
Katie -- were you able  to address Julia's  need about the SAGBI classes?

If not then, I am copying the instructions for Connar from my email to you. 


sagbi_catf | grab all SAGBI cat. Classes that does not start with POOR,   VERY POOR, MOD. POOR OR all fields that has ‘GOOD’ in it
-- | --
FinalScore |  
Spr_2014 | Previous year fields submitted
Fall_2014 | enrolled vs not enrolled
Spr_2015 |  
Fall_2015 |  
Spr_2016 |  
Fall_2016 |  
Wintr_2015 |  
Spr_2017 |  
Fall_2017 |  
f17option |  
f17_bidNum |  
f17_accpt |  
  |

**Comment by ka78** [comment]
@TB2016 - I was not able to find anything named SAGBI_analysis_June22, so I went back to the original SAGBI .tif you sent us, converted it so I could do a tabulate area for the good categories 4, 5 and 6. I'm about to send JB the spreadsheet.

**Comment by TB2016** [comment]
@Katie -- I had to jog back my memory to see why the June22 run was not
located in the N drive for Fall Auction you had created.
I recollected that we ran the script from my hard disk, so I think the
final run is in there..

However, I had a copy of the final run on my computer. I just copied it to
N drive.
Too bad that you had to do the whole analysis..  !!

What you did is what I did too.. but then I went another extra step to
classify each field into diff SAGBI category based on % area under each
category..
There were few fields which had equal area under multiple categories..
Depending on how much area is  occupied by diff sagbi categories  the field
are automatically categorized into different class automatically.

I think the file you provided meets Julia's need.

But if you are interested  *[BRFields_with_SAGBIAnalysis.dbf ]* associated
with the shapefile is the final file, that I wanted you to grab.
It has the attributes I mentioned above.

I made a copy, and saved a file named*
[BRFields_with_SAGBIAnalysis_TB_added_perSAGBI_Aug2017.xlxs] *and have
color coded the fields that are important.
I will update the script before SPRING 2018 to do the % SAGBI calculation..

If JB in future needs a map of all fields under different sagbi category,
or by district etc., then this is the file we should go with..

Thanks
Tanu

**Comment by ka78** [comment]
Okay got it, thanks @TB2016 for copying the data over to Carogis, I've got it now - closing this issue (I sent JB your data file, so now she has the more granular version.

**Comment by ka78** [comment]
N:\WATER_Program\birdreturns\2017_Fall\AuctionFall2017\AuctionMetrics\SAGBI_analysisJune22

**Comment by TB2016** [comment]
@KA78 Thanks Katie, I really liked this pathway on Project tracking here on
GitHub. We should do this for everything else we are working on together.
What do you think?

One this remains is connecting the District information to this final SAGBI
file. Because I ran a new classification than the one I initially provided
to Julia.  It will be good to have Connor  assign district information to
this SAGBI analysis, after he returns.

I can write the task for him.. let me know.

Thanks
Tanu
