### ISSUE TITLE
Remake existing map for Groundwater Report (8/28)

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#84]
Hi Conner-

Please update this mxd to make a new figure (save as a new .mxd with a new name):
"N:\Projects\Groundwater\sites\VenturaCounty\mxds\pGDEs_FoxCanyon_MappingChanges_Cori_Oxnard.mxd"

This is for Melissa Rhode and here are her instructions:

"Is there anyway you can modify this figure for me for the guidance framework.  These are the changes we need:

-change baselayer so that there are no location information available. An all grey or white background would suffice.
-remove groundwater basin labels."

Please save in PDF format to allow for easy editing and incorporation with the rest of the report.

We don't have a due date yet from Melissa, so I would say 1 week from today, or Aug 29th, as a tentative due date.  I will update this issue when I get the due date from Melissa.

**Comment by kklausmeyer** [comment]
Deadline update from Melissa:  Monday, August 28th.  Please send a first draft to her by Friday the 25th if possible.

**Comment by connorshank** [comment]
Task completed, see below for related file locations
pdf locations:
N:\Projects\Groundwater\sites\VenturaCounty\plots\pGDEs_FoxCanyon_MappingChanges_Connor_Oxnard
N:\Projects\Groundwater\sites\VenturaCounty\plots\pGDEs_FoxCanyon_MappingChanges_Connor_Oxnard_Option2

map location:
N:\Projects\Groundwater\sites\VenturaCounty\mxds\pGDEs_FoxCanyon_MappingChanges_Connor_Oxnard

**Comment by connorshank** [comment]
Closing this issue
