### ISSUE TITLE
Data Mgmt - create blank ca_tnc_interests feature class using new data model (8/28 flex)

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#85]
TNC Interests is one of our core data layers I showed you yesterday, it's stored in our enterprise geodatabase (you access it using the egde account **caro_viewer**).  We have a new data model we'd like to use with this feature class; it's described in this document: N:\TNC_GeoDesign\Core Data\InterestsDATAMODEL.docx

Please create a new feature class (in a file geodatabase) that uses the new template.  For fields where there is no change you can use the same field format as the existing feature class (e.g. text, 50).  

You can just start from scratch for find a way to use the existing layer to create a new feature class with renamed and reordered fields.

Due date is flexible. By 8/28 would be great (but even that is flexible).

**Comment by megrwebb** [comment]
Conner,

JSYK, I just made a few changes to the Interest Data Model document.

Added missing TNCL_AN field
Added new GEOMSOURCE field
Increased the text length for CLS_SITENAME, PROP_INT_NAME, AND PUB_ACCESS
Added additional Salesforce “Ownership Status” types

Megan

**Comment by connorshank** [comment]
Created the new feature class within a new gdb.   The fields have been added, deleted, or altered accordingly, but have yet to be populated.   I wasn't sure where it's permanent ho,e would be so I put it in the Core Data file for now, should be easy to move:

N:\TNC_GeoDesign\Core Data\ca_tnc_interests_Connor.gdb

**Comment by ka78** [comment]
Terrific. I'll have a look when I can, and then I'll import it into our enterprise gdb.

**Comment by ka78** [comment]
Connor I imported this to the enterprise gdb today and everything seems to be working great, thanks so much.
