### ISSUE TITLE
Pajaro -- WebMap Updates (9/11 flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#86]
Hi Connor - 

The Pajaro Compass is ready for its first round of annual data updates.  

Updates need to be made in 3 places
1.  Webmap (publish on stratus)
2.  Data package geodatabase available for download
3.  Metadata

We'll start with data that is not a part of the conservation assessment.  Here is the list
1. Add UPLAN scenarios - update BAU to the newer analysis, and add SMART and REDEV scnearios.
Be careful - make sure you go into the 'transfer2016-10' folder for the NEWER data
N:\California\grids\Growth_UPlan_Thorne\transfer2016-10\output_bundle_bau1\
N:\California\grids\Growth_UPlan_Thorne\transfer2016-10\output_bundle_other\output_bundle_other\state_redev
N:\California\grids\Growth_UPlan_Thorne\transfer2016-10\output_bundle_other\output_bundle_other\state_smart

2. Add CALENVIROSCREEN disadvantaged communities: 
For disadvantaged communities defined by CalEPA for SB535, disadvantaged communities are defined as the top 25% scoring areas from CalEnviroScreen, communities that are most affected by many sources of pollution, and where people are often especially vulnerable to pollution’s effects. CalEnviroScreen uses environmental, health, and socioeconomic information to produce scores for census tracts. Looks to be recent. Webmap: http://oehha.maps.arcgis.com/apps/Viewer/index.html?appid=dae2fb1e42674c12a04a2b302a080598

3. Update  water bond disadvantaged communities:
For disadvantaged communities defined by the Department of Water resources, pursuant to Proposition 1 and Proposition 84, disadvantaged communicates are those with a mean house hold income less than 80% of the State's median household income or severely disadvantaged communities less than 60% of the State's median household income.  Mapped to census tracts, block groups and places.  Updated May 2016.  Webmap: https://gis.water.ca.gov/app/dacs/
4. Gilroy ugb's - ask Jake Smith jsmith@openspaceauthority.org
5. Check on release date of groundwater basins (priority) - update if necessary
6. Check on new CPAD to see if we need to update, also update distance to Protected Areas (this may included updates to CPAD beyond the Pajaro Boundary)
8. Any new transporation projects? Check with Ann Calnan and Nancy Siepel. (Carrie emailed 9/18)
9. Add thorne analysis to climate change threats
Add two scenarios: 
 1)warmer wetter
N:\California\grids\UCD_climateExposure\TNC\cwhr\individual\BCM_cnrm_cm5_rcp85\Exposure\rasters_masked\exposure_4069.tif
2) hotter drier
N:\California\grids\UCD_climateExposure\TNC\cwhr\individual\BCM_miroc_esm_rcp85\Exposure\rasters_masked\exposure_4069.tif
10. Update protected area (le-won?  Next to montes) soap lake ranch (CA)

**Comment by connorshank** [comment]
Carrie,
I've created an mxd with the necessary and available layers at the following location:
N:\Central_Coast\Projects\Paj\Mxds\Paj_updates_Fall17_Connor.mxd

I was hoping you could give the layers a quick look-over to make sure everything is correct.  Particularly, the Paj_PA_update layer.   I merged the clipped CPAD and CCED layers (as well as the two easement layers you sent).   From the looks of the Protected Land layer that is currently in the webmap, there are only two displayed attributes (Easement or Fee? and Public Access?).   Do you know if there is a simpler work-around for creating these attributes within the table, or is it just a matter of adding new fields and manually filling them out?

**Comment by cschloss** [comment]
Hi Connor -

For the waterbond DAC layer - is the DAC we are viewing by block/tract/group? I think we probably want to use the most inclusive or a union between layers if they are not nested.

For the CalEPA DAC layer is the top 25% a decision you made in data display or is that cutoff related to what is considered DAC ?

**Comment by connorshank** [comment]
The waterbond DAC is by census tract, that seems to be the most consistently used division across layers and data sources, though there is a layer for census group (subset of tracts) if you would prefer that.

As for the CalEPA DAC, only the top 25% (also by census tract) are displayed on their webapp, hence why I definition queried it down to that subset.

**Comment by cschloss** [comment]
Thats great then.  Thanks. - Still reviewing the other laters and your PA question.  I'll get back to you shortly on the rest

**Comment by cschloss** [comment]
For the uplan scenarios - there is a layer file that has the housing density and land use classes labeled and colored - can you apply the symbology from the layer file should be in this folder: N:\California\grids\Growth_UPlan_Thorne\transfer2016-10\output_bundle_bau1

Exposure - I adjusted the class breaks and colors according to: https://lccnetwork.org/sites/default/files/Resources/California%20Climate%20Vulnerability%20Assessment%20of%20Macrogroup%20Vegetation_01.31.2016_FINAL.pdf  (page 29) can you also change the labels so they are represented as percentages rather than proportions?

**Comment by connorshank** [comment]
The mxd has been published to the following url: http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/Conn/Connectivity_Climate_update11132017/MapServer

There is still an issue with adding the mxd versus the layer (MapServer/0) to the webmap.   I will add a note when this is resolved, for now it is the mxd itself that has been added to the webmap.

**Comment by connorshank** [comment]
The Webmap has been successfully updated, two new services have been published and the configuration of the updated layers pop-ups have been edited to match the older versions where necessary.   The urls for the new services are below:

http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/Paj/Paj_Influences_201711/MapServer

http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/Paj/Paj_Recreation_201711/MapServer

**Comment by ka78** [comment]
that's great @connorshank! 
@cschloss what do you think of having @connorshank do some housekeeping with any old not-relevant-anymore published PAJ layers on stratus (if any exist)?

**Comment by cschloss** [comment]
Hi Connor!  If you area willing to do some housekeeping - that would be great.  Please remove any non relevant pajaro laters.

Thanks!
