### ISSUE TITLE
Connectivity -  3D Cartography (10/13)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#87]
Hi Connor

Can you make a 3D map - potentially one that is interactive in Google Earth of our layer for climate adapted connectivity. This task would be to drape a map of climate adapted connectivity onto a 3D surface with the 3rd dimension defined by elevation

**Comment by connorshank** [comment]
Carrie,
  Do you have the file locations for the climate adapted connectivity layer and a DEM for California?  Thanks!

**Comment by cschloss** [comment]
Hi Connor - 

I had a check-in meeting on our Calendars for tomorrow to talk about this work - I'll see if I can move it to today to get you started on this...

**Comment by cschloss** [comment]
Data sources:

Climate Adapted Connectivity - Draft
n:/projects/connectivity/grids/inputs201704/clipNorm/difs/ca_sumAdaptChnIntThrshPost2.tif

DEM for CA
N:\California\data\elevation\DEMs.gdb\CA_DEM30M

**Comment by cschloss** [comment]
Here is the layer file with the draft colors
N:\Projects\Connectivity\lyrs\ca_climateAdaptedCorridors_wBase_4thresholds

**Comment by connorshank** [comment]
I have created an ArcScene map file, as well as a kml file that can be viewed in Google Earth, located as follows:
N:\Projects\Connectivity\mxds\Connectivity_3D_elevation_090717.sxd
N:\Projects\Connectivity\lyrs\ca_sumAdaptChnIntThrshPost2.kmz

**Comment by cschloss** [comment]
Thanks Connor - this was really helpful in interpreting our output! I'm going to close this for now, but we may reopen when we finalize our output and symbology.

**Comment by cschloss** [comment]
Hi Connor - we got a last minute request to present this information on Monday and if possible I'd like to share the 3d map - I have a new/updated data layer and cartography, would you have time today to switch out the layer for the 3d map?

**Comment by cschloss** [comment]
Update:  it would just be the arcscene product and not the google earth product at this point.
The layer file is here: n:/projects/connectivity/lyrs/ca_climateAdaptedCorridors_greyBase_2models.lyr
and the data is here: n:/projects/connectivity/grids/inputs201705/ca_sumAdaptChnInt2ClimPost4.tif

**Comment by connorshank** [comment]
Carrie,
     I have updated the arcscene map with the requested data layer (the old one is still there, just in case you need it for whatever reason).   Let me know how it looks, I'm happy to tweak the elevation exaggeration or smooth/un-smooth the surface and such if needed to help with the presentation.
N:\Projects\Connectivity\mxds\Connectivity_3D_elevation_090717.sxd

**Comment by cschloss** [comment]
This looks awesome.  Thanks.
