### ISSUE TITLE
Parcel to Property Database (2/9 flex)

### ISSUE THREAD

**Issue by cschloss** [tnc-ca-geo/gd_intern#88]
Hi Connor - We are interested in finishing out a statewide property layer.  Cori started this for the rangeland analysis but the property layer only has the counties that have rangeland.  Using that data as a starting point - this task is to pull in the remaining counties and for counties with poor ownership information, to try to get better data.  To dissolve on owner (within county)  and then combine into one master dataset. 

Once that is complete, we will need to remove all protected lands (non-easement) and create a unique identifier for each property.

Steps:
1. Identify gaps in property dataset
2. Get county parcel data for missing counties and for counties with missing ownership (start with core logic on N drive - if no ownership info in core logic, email county to ask for data)
3. Dissolve on owner name
4. Merge county data with master dataset
5. Remove protected lands (non-easement)
6. Assign unique identifiers

I can provide more context for this project at our meeting next week.

Thanks,
Carrie

**Comment by cschloss** [comment]
N:\California\data\ownership\Parcels

Please sign the data use agreement before you work with this data -  which you will also find in that folder.

**Comment by connorshank** [comment]
Carrie,
     I have successfully dissolved all the most up-to-date county corelogic layers by owner (N:\Projects\Atlas\data\parcels\temp).   I have tried several times to merge these layers together, but have encountered the same problem each time.   ArcMap fails to draw the resulting shapefile whenever I try to upload it into a map or preview it in Catalog.   I am afraid this may be due to the very large file size, but I'm not sure.   I'm now working on erasing out the cpad properties within each of the individual dissolved county layers that I have created and will try merging the resulting, slightly smaller, shapefiles afterwards.   I'll let you know how this goes, but if you have any suggestions or thoughts on the drawing issue please let me know.

**Comment by cschloss** [comment]
Great - you might try remoting into carorgis and doing the analysis on ArcMap on the server for more processing power than your laptop.  If that doesn't work, we are likely going to make a minimum parcel size decision - so we can do that at this step.  Do you need help remoting on to the server or is that something you've done in the past?

**Comment by connorshank** [comment]
I have been doing most of the analysis via the remote server, I'll give it one more go though after I've filtered out the protected lands.

**Comment by ka78** [comment]
did you guys get this worked out?

carrie do you think processing on COGEOPROC server would help (is it a server capacity or data issue)? we can get access for connor if it’s helpful, lmk.

**Comment by connorshank** [comment]
Katie,

               The issue has not been resolved, however, I don’t think it’s a data processing issue, per se.   The merge tool successfully creates a shapefile and adds it to the map, however it cannot be drawn, and therefore cannot be viewed in either ArcMap or Arc Catalog.  I can still open the attribute table and properties window for the resulting layer, so I was going to try querying out all the smaller parcels (<2-5 acres) and see if that helps.   I’ll let you know how it goes.

Sincerely,
Connor Shank

**Comment by cschloss** [comment]
Great, thanks for the update.  At this point it is ok if it doesn’t draw.  Hopefully knocking out those smaller properties will help

**Comment by connorshank** [comment]
Carrie, I wanted to update you on the progress of this project.   I have created shapefiles for each county, dissolved by owner with protected lands removed.  Those can be found here:
N:\Projects\Atlas\data\parcels\shapes\nonPA ownership counties
I have tried filtering out smaller properties and then either merging or appending the shapefiles together, but with no success.   Everything I've found online seems to indicate that ArcMap is simply incapable of rending a single shapefile with an extremely large number of individual features.   I'm not sure how to proceed from here.   Katie has suggested contacting Esri and seeing what their experts have to say.

**Comment by connorshank** [comment]
Update 1/24/2018:   Attempt creating a statewide layer of all parcels >2500 acres

**Comment by connorshank** [comment]
Good news!   I was able to select out all parcels >=2500 acres (dissolved by owner) across all counties and merge them into a single shapefile, located here:
N:\Projects\Atlas\data\parcels\shapes\large_parcel_county_selections\CA_Statewide_Large_Parcels.shp
Just a note, all parcels were dissolved by owner before the acreage selection was made, therefore the included parcels account for all owners who own more than 2500 acres in a given county, even if those parcels are non-contiguous.   Also, I have not dissolved this state wide layer by owner, so if the same entity owns large properties in multiple counties, each of these property groups are listed separately by county.   I wanted to hold off on any further dissolving since there are a lot of discrepancies in names  in the ' Owner' field, especially when it comes to government agencies.

**Comment by connorshank** [comment]
Update (1/26):  I have deleted all of the obvious public properties from the statewide dataset, including federal, state, county, and local entities.   There may still be a few obscurely named county agencies left, but all of the large, obvious parcel groups (i.e. military lands) have been removed.   Furthermore I have dissolved the dataset by owner in order to group parcels with the same ownership across county boundaries.

**Comment by cschloss** [comment]
Great, thanks Connor.  Can you let Dick know when you are ready to share an updated layer with him based on the updates we discussed in our meeting today as I will be out next week?

**Comment by connorshank** [comment]
Sure thing, I can definitely do that early next week.

Sincerely,
Connor Shank

**Comment by connorshank** [comment]
Re-opening for updated analysis.

First stage workflow:
1.) Filter out parcels <5 acres
2.) Filter out protected areas (cpad) and easements? (select by location - centroid)
3.) Dissolve by owner -> not multi-part (look into methods for creating multi-part by proximity)

Current file locations:
N:\Projects\Atlas\data\parcels\shapes

Creating new workspace:
N:\Projects\Atlas\data\parcels\shapes\round2_analysis

**Comment by cschloss** [comment]
Hi Connor - what do you think of this approach?
1. Calculate Acres in GIS to make sure acreage is accurate for the projection we are working in 
2. Dissolve multipart all CPAD to a single shape
3. Intersect with parcel data
4. Dissolve output from step 3  on APN
5. Calculate Acres of the output from step 4
6. Join by attribute the output from step 5 onto the output of step 1 (the parcel data). The join field would be the APN
7. Divide protected acreage (from the joined table) by the total parcel acreage, multiply by 100
8. Remove parcels with >70% protected (this is where we may need to adjust) does this miss some parcels we should have removed?  Would >50% remove some we should have left?)

**Comment by connorshank** [comment]
N:\Projects\Atlas\data\parcels\round2_analysis\scripts

county_loop_test is the current workspace, county_loop has the full list of county abbreviations that will eventually be added to the final script.
