### ISSUE TITLE
Gather TNC data and put in MXD

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#89]

**Comment by kklausmeyer** [comment]
Make an MXD and include features for the following TNC Interests / projects:

American River Headwaters
French Meadows
Independence Lake
Carpenter Valley

Save the .mxd here:
N:\Projects\TNC_Board_Meetings\2017_October\mxds

**Comment by connorshank** [comment]
Kirk,

I just wanted to make sure I have the appropriate shapefiles for these projects, do these look right:
American Rivers Headwaters:  N:\Sierra_Nevada\Projects\AmericanRiverHeadwaters\shapes\American_headwaters_parcels.shp
Independence Lake:
N:\Sierra_Nevada\Projects\From Seth\Map this folder as G drive\Data\TNC_Chico\Northern Sierra\Independence_Lake.shp
Carpenter Valley:
N:\Sierra_Nevada\Projects\CarpenterValley\gdbs\CarpenterValley.gdb
There are a number of shapefiles associated with the Carpenter Valley project file, I wasn't sure which specifically you were interested in though.

If these look right I can go ahead and copy them over to the TNC_Board_Meetings\2017_October location and then add them to the map.

**Comment by kklausmeyer** [comment]
Hi Connor-

These files look right -  I am working from home today so it is a little cumbersome to review them invididually.  Go ahead and drop them in the MXD, add a basemap, and start putting together the layout for a printed page.  Then let me know and I can review the individual shapes for accuracy in the .mxd.

Thanks!

**Comment by connorshank** [comment]
Appropriate layers have been added to the mxd, a rough draft map layout has also been prepared, just adding a few final touches today.
