### ISSUE TITLE
Make Board Book Map: 

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#90]
Map sized to fit on 8.5x11 printed page.  
Draft Title:  "Scaling Up Forest Restoration"
Audience:  The Board and senior leadership
Initial .mxd here:  N:\Projects\TNC_Board_Meetings\2017_October\mxds\Board_book_map.mxd
Team Assignments:
Connor- lead on gathering data and making map
Megan- Review cartography to ensure it is suitable for the board book
Tanu- on call as needed for content / data questions
Kirk - coordinate internal review

**Comment by kklausmeyer** [comment]
Here is an existing map to build on:  
N:\Projects\TNC_Board_Meetings\2017_October\admin\TCSI_mapUpdate-09012017.jpg

**Comment by kklausmeyer** [comment]
The final map must conform to TNC brand guildlines.  See this guide on connect: https://connect.tnc.org/Departments/marketing/BrandMarketing/Documents/TNC_Vis_ID_Guide_2015_06%20(2).pdf
Here is the general visual identity page:  https://connect.tnc.org/Departments/marketing/BrandMarketing/Pages/default.aspx

In particular, use the following fonts:
Chronicle or Georgia
Whitney or Arial

The TNC logo may not be needed on the map since this will be in the board book.  But lets put it in anyway.

**Comment by kklausmeyer** [comment]
Here is the schedule for review
First draft to Kirk:  COB 9/8/17
First draft to David Eddleson / Brea for review: COB 9/11/17
Final draft to David / Brea / Scott:  COB 9/18/17
Final draft dard deadline for board book: COB 9/21/17

**Comment by connorshank** [comment]
Draft map created and located at:
N:\Projects\TNC_Board_Meetings\2017_October\mxds\Board_book_map_Connor_952017.mxd
I've also created a jpeg image in the 2017_October folder.

Let me know what you think, happy to make any necessary changes or add additional data.

**Comment by connorshank** [comment]
Updated the map document based on feedback, and added 2 new jpegs to the plots folder.   The only difference between them is that draft3 has a light border around the A.R. Headwaters polygon to distinguish it more from French Meadows.

**Comment by kklausmeyer** [comment]
Hi Connor-

Here is a distillation of Scott's comments on this map:

1. Change TCSI label to say "Tahoe-Central Sierra Initiative boundary”
2. Double check the the math on the area of the circles.  Scott thought the TSCI circle is too big.
3.  Add large circle with a dotted line that bleeds off the edge of the map to represent the area of the Sierra Nevada ecoregion (Area:  50182545281 sq m).  Consider adding the sierra nevada boundary to the map as well in a thin white dotted line.  Keep the map zoomed to where it is but let the sierra nevada boundary extend beyond the edges of the map.  See the attached powerpoint for Scott's conceptual idea of how to do this.  Ecoregion feature class here: 
 Database:	N:\California\data\bioscience\ecoregions.gdb
Feature Class:	CA_ECOREGION_06_V1
[scales.pptx](https://github.com/tnc-ca-geo/gd_intern/files/1318604/scales.pptx)
4. Add an Asterisk after the Sierra Nevada Ecoregion label and put a note on the bottom of the map that says "Forest restoration is needed across the Sierra Nevada Ecoregion" 
5. Remove the black line around the logo

**Comment by TB2016** [comment]
@connorshank  is the link to the board book map ? 

N:\Projects\TNC_Board_Meetings\2017_October\mxds\Board_book_map_Connor_952017.mxd
I want to keep a copy of all the maps you are making on sac server once you are done completing it.

Thanks
Tanu

**Comment by connorshank** [comment]
Tanu,

Yes, that is the primary board book map for the Northern Sierra/Tahoe focus.   All the board map mxds should be going into this folder.

**Comment by kklausmeyer** [comment]
Great work on this Connor.  Lets call it done when the board book goes out on Friday 9/29.  I don't anticipate any more changes but you never know!

**Comment by kklausmeyer** [comment]
Final maps here:  N:\Projects\TNC_Board_Meetings\2017_October\plots.  Done!
