### ISSUE TITLE
Upload CalVeg Data on Box by Wed Morning 9/6/2017

### ISSUE THREAD

**Issue by TB2016** [tnc-ca-geo/gd_intern#92]
Connor, 

Can you please upload CALVEG data on box for me to access it from here. 

Thanks
Tanu

Here is the link on BOX to upload to https://tnc.box.com/s/gmv8qoq156ox8cxc0rtlvqn22mo3g6l6
Upload everything within LANDCOVER folder on N drive under respective folders.

Statewide CalVeg layer:  N:\California\data\landcover\Vegetation.gdb\CA_VEG_CALVEG2000

You can also use Fveg, which is a gridded compilation of CalVeg and higher resolution data where available that covers the entire state:  N:\California\data\landcover\Vegetation.gdb\CA_VEG_FVEG_2006

Thanks
Tanu

**Comment by TB2016** [comment]
Here is another dataset that I need by tomorrow morning 
N:\California\data\landcover\fveg15_1.gdb\fveg15_1

**Comment by kklausmeyer** [comment]
Direct download available here:  http://frap.fire.ca.gov/data/frapgisdata-sw-fveg_download

**Comment by connorshank** [comment]
The requested files have been uploaded to box

**Comment by connorshank** [comment]
Closing this issue
