### ISSUE TITLE
Data Mgmt - CoreLogic ParcelPoint quarterly updates

### ISSUE THREAD

**Issue by megrwebb** [tnc-ca-geo/gd_intern#95]
Background: Parcel data is useful for many facets of TNC’s work, such as the identification of landowners in priority areas and generating property boundaries for documenting our protection work. The CoreLogic ParcelPoint data product gives us access to current parcel data by county for almost the entire United States. New data is added quarterly and needs to be download to our server for easy access.

1) Sign the ParcelPoint data use agreement;  Go to N:\California\data\ownership\Parcels\# MANDATORY EMPLOYEE DATA USE AGREEMENT and sign a copy of the agreement.  Email a signed copy to Jan Slaats and cc me so we have a local copy for our records.

2) Go to TNC’s internal site to download data by county
    http://mnspatial.tnc.org/parcelpoint/

3) View, select and download **recent updates** for California (I'll also forward an email about the updates). 

4) Unzip data and place shapefiles in N:\California\data\ownership\Parcels by county.  Rename shapefiles using our current naming convention by state, county, source and date (e.g. CA_ALPINE_CoreLogic_20170117).  Note, date is from the date acquired field on the download page.

Let me know if you have any questions, etc.

Thanks,
Megan

**Comment by connorshank** [comment]
I have already signed and scanned a copy of the parcelpoint agreement for employees and placed it in
N:\California\data\ownership\Parcels\# MANDATORY EMPLOYEE DATA USE AGREEMENT\Signed

**Comment by megrwebb** [comment]
Ok, thanks and please send a copy to Jan Slaats if you haven't done so already.

**Comment by connorshank** [comment]
Can do!  Could you forward me Jan's contact info per chance?   Thanks.

**Comment by megrwebb** [comment]
His contact info is on the agreement.

**Comment by connorshank** [comment]
I have sent the email, downloaded the updates CoreLogic county data and added it to the appropriate folders in   N:\California\data\ownership\Parcels

**Comment by megrwebb** [comment]
Thanks Conner!
