### ISSUE TITLE
Powerpoint presentation map for Dan Porter

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#97]

**Comment by kklausmeyer** [comment]
Dan Porter needs a slide that shows the main properties in the northern sierra and the TCSI area.  I think we can use the same map for David, but remove the stuff in the lower part of the map and convert to landscape orientation.  Don't use a title, but add the scale bar and north arrow on the map.  Remove the border.  Make the size 7.5 in by 7.5 inches.  Deliver to Dan in jpg format.

**Comment by connorshank** [comment]
mxd file:
N:\Projects\TNC_Board_Meetings\2017_October\mxds\TCSI_properties_ppt_map_Connor_9252017.mxd

jpegs location:
N:\Projects\TNC_Board_Meetings\2017_October\plots
