### ISSUE TITLE
Wood Processing Infrastructure Map for board presentation by Eric and Rodd

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#99]

**Comment by kklausmeyer** [comment]
Convert and existing map to a powerpoint map and make edits for Eric and Rodd's board presentation.  Dan Porter is also on the review chain for this one.
Here is the existing map:  
[AllFacilities.pdf](https://github.com/tnc-ca-geo/gd_intern/files/1322668/AllFacilities.pdf)

I am not sure where the mxd is to make the data. Tanu and Cori (previous GeoDesign associate) were working on the map.  I have shared the google drive folder with Connor's TNC email account.  

I will write more on this request later today.

**Comment by kklausmeyer** [comment]
Due Date for 1st draft-  Thursday 9/28
Final draft due 10/5 for final draft presentation before the board meeting

Size- lets go with powerpoint slide size of landscape 10x7.5 inches
Title- no title

Content:  Biomass facilities.  Tanu has the key shapefiles and has put them in a google drive folder and likely on the external drive.

Here are the edits requested by Dan:

Here you go. 

	Remove all references to the North Coast Conservation Region
	Remove the Conservation Value layers for the Sierra Nevada and corresponding legend item
	Retain the boundary of the Sierra Nevada Ecoregion
	Add the outline or other representation of TCSI so that it stands out – even at this statewide scale;
	Maintain or delete the map extent that covers Oregon, whatever is easiest – probably better to delete it;
	Mimic (to the degree reasonable given time constraints) the base layers from the second attached map
o	Include major roads, i.e. at least those included in the USFS map;
o	Include the National Forests and other public lands; 
o	I like the convention USFS used – shading the parks in a slightly darker shade of gray – please adopt or suggest an improvement;
o	Include major cities and towns
	Eliminate the non-functional facilities from the map – i.e. on the USFS map “Closed” and “Idle” or “Idle”, “Cancelled”, “Liquidated”, “ND” or “E” on Tanu’s map
	As with the USFS map, create two major categories of symbols in the legend “Primary Wood Processing Facilities” and “Biomass Power Plants”
	For the Biomass Power Plants super category, please retain the grouping “Active Project or Proposal”
	If time allows, make one version of the map without this particular grouping, and one with it so we can illustrate how biomass is experiencing rapid growth
	If short on  time, focus on the one map with all the categories included
	Resize the symbols for the remaining facilities to increase readability, within a Power Point presentation
o	Create enough contrast, either in shape, color or both to have the viewer distinguish primary wood processing from biomass if possible
	No need to number of create a legend for the individual facilities as done on the USFS map
	Retain the USFS map title and legend labels.

**Comment by connorshank** [comment]
mxd file:
N:\Projects\TNC_Board_Meetings\2017_October\mxds\Wood_Processing_Infrastructure_map_92217

jpeg and pdf drafts and final copies:
N:\Projects\TNC_Board_Meetings\2017_October\plots
